canonical_name: "btb_gb"
version: 56000000008
apns {
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|18|20"
    user: "eesecure"
    password: "secure"
    authtype: 1
    protocol: IPV6
    roaming_protocol: IPV4V6
    user_visible: false
  }
  apn {
    name: "Internet"
    value: "everywhere"
    type: DEFAULT
    type: SUPL
    user: "eesecure"
    password: "secure"
    authtype: 1
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_editable: false
  }
  apn {
    name: "MMS"
    value: "eezone"
    type: MMS
    type: XCAP
    user: "eesecure"
    password: "secure"
    authtype: 1
    mmsc: "http://mms/"
    mmsc_proxy: "149.254.201.135"
    mmsc_proxy_port: "8080"
    user_editable: false
  }
  apn {
    name: "EE Emergency"
    value: "sos"
    type: EMERGENCY
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "carrier_cross_sim_ims_available_bool"
    bool_value: false
  }
  config {
    key: "carrier_default_data_roaming_enabled_bool"
    bool_value: true
  }
  config {
    key: "carrier_supports_ss_over_ut_bool"
    bool_value: true
  }
  config {
    key: "carrier_ussd_method_int"
    int_value: 2
  }
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "carrier_wfc_ims_available_bool"
    bool_value: true
  }
  config {
    key: "editable_enhanced_4g_lte_bool"
    bool_value: false
  }
  config {
    key: "editable_wfc_mode_bool"
    bool_value: false
  }
  config {
    key: "hide_enable_2g_bool"
    bool_value: true
  }
  config {
    key: "hide_ims_apn_bool"
    bool_value: true
  }
  config {
    key: "hide_preferred_network_type_bool"
    bool_value: true
  }
  config {
    key: "ims.geolocation_pidf_in_sip_invite_support_int_array"
    int_array {
      item: 4
      item: 2
    }
  }
  config {
    key: "ims.geolocation_pidf_in_sip_register_support_int_array"
    int_array {
      item: 4
      item: 2
    }
  }
  config {
    key: "ims.ims_user_agent_string"
    text_value: "#MANUFACTURE#_#MODEL#_#BUILD#"
  }
  config {
    key: "imsemergency.emergency_over_ims_supported_rats_int_array"
    int_array {
      item: 3
    }
  }
  config {
    key: "imsss.ut_iptype_home_int"
    int_value: 0
  }
  config {
    key: "imsss.ut_iptype_roaming_int"
    int_value: 0
  }
  config {
    key: "imsss.xcap_over_ut_supported_rats_int_array"
    int_array {
      item: 5
      item: 6
      item: 3
      item: 1
      item: 2
    }
  }
  config {
    key: "imsvoice.audio_codec_capability_payload_types_bundle"
    bundle {
      config {
        key: "imsvoice.amrnb_payload_type_int_array"
        int_array {
          item: 98
          item: 103
        }
      }
      config {
        key: "imsvoice.amrwb_payload_type_int_array"
        int_array {
          item: 100
          item: 105
        }
      }
      config {
        key: "imsvoice.dtmfnb_payload_type_int_array"
        int_array {
          item: 97
        }
      }
      config {
        key: "imsvoice.dtmfwb_payload_type_int_array"
        int_array {
          item: 96
        }
      }
    }
  }
  config {
    key: "imswfc.emergency_call_over_emergency_pdn_bool"
    bool_value: true
  }
  config {
    key: "iwlan.ike_rekey_hard_timer_in_sec"
    int_value: 1300
  }
  config {
    key: "iwlan.ike_rekey_soft_timer_sec_int"
    int_value: 1200
  }
  config {
    key: "iwlan.key_error_policy_config_string"
    text_value: "[{\"ApnName\": \"*\",\"ErrorTypes\": [{\"ErrorType\": \"IKE_PROTOCOL_ERROR_TYPE\",\"ErrorDetails\": [\"24\"],\"RetryArray\": [\"10\", \"30\", \"60\", \"120\", \"300\", \"-1\"],\"UnthrottlingEvents\": [\"APM_ENABLE_EVENT\", \"WIFI_DISABLE_EVENT\", \"WIFI_AP_CHANGED_EVENT\", \"WIFI_CALLING_DISABLE_EVENT\"]}]}]"
  }
  config {
    key: "non_roaming_operator_string_array"
    text_array {
      item: "23430"
      item: "23431"
      item: "23432"
      item: "23433"
      item: "23434"
      item: "23486"
    }
  }
  config {
    key: "prefer_2g_bool"
    bool_value: false
  }
  config {
    key: "qns.mms_rat_preference_int"
    int_value: 2
  }
  config {
    key: "qns.sos_transport_type_int"
    int_value: 2
  }
  config {
    key: "show_4g_for_lte_data_icon_bool"
    bool_value: true
  }
  config {
    key: "use_wfc_home_network_mode_in_roaming_network_bool"
    bool_value: true
  }
  config {
    key: "wfc_operator_error_codes_string_array"
    text_array {
      item: "REG09|0"
    }
  }
  config {
    key: "wfc_spn_format_idx_int"
    int_value: 1
  }
}
last_updated {
  seconds: 1706100369
}
