canonical_name: "cellcom_il"
version: 56000000005
apns {
  apn {
    name: "Cellcom Internet"
    value: "sphone"
    type: DEFAULT
    type: SUPL
  }
  apn {
    name: "Cellcom MMS"
    value: "mms"
    type: MMS
    mmsc: "http://mms.cellcom.co.il"
    mmsc_proxy: "vwapm2.ain.co.il"
    mmsc_proxy_port: "8080"
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "cdma_3waycall_flash_delay_int"
    int_value: 0
  }
  config {
    key: "imsemergency.emergency_over_ims_supported_rats_int_array"
    int_array {
      item: 3
    }
  }
  config {
    key: "imsss.xcap_over_ut_supported_rats_int_array"
    int_array {
    }
  }
  config {
    key: "imsvoice.audio_codec_capability_payload_types_bundle"
    bundle {
      config {
        key: "imsvoice.amrnb_payload_type_int_array"
        int_array {
          item: 98
          item: 103
        }
      }
      config {
        key: "imsvoice.amrwb_payload_type_int_array"
        int_array {
          item: 100
          item: 105
        }
      }
      config {
        key: "imsvoice.dtmfnb_payload_type_int_array"
        int_array {
          item: 97
        }
      }
      config {
        key: "imsvoice.dtmfwb_payload_type_int_array"
        int_array {
          item: 96
        }
      }
    }
  }
  config {
    key: "imsvoice.ringback_timer_millis_int"
    int_value: 60000
  }
  config {
    key: "imsvoice.ringing_timer_millis_int"
    int_value: 60000
  }
}
last_updated {
  seconds: 1706100369
}
