canonical_name: "default"
version: 56000000011
configs {
  config {
    key: "carrier_cross_sim_ims_available_bool"
    bool_value: true
  }
  config {
    key: "carrier_data_call_retry_network_requested_max_count_int"
    int_value: 20
  }
  config {
    key: "carrier_eri_file_name_string"
    text_value: "eri.xml"
  }
  config {
    key: "carrier_promote_wfc_on_call_fail_bool"
    bool_value: true
  }
  config {
    key: "carrier_volte_tty_supported_bool"
    bool_value: false
  }
  config {
    key: "cdma_3waycall_flash_delay_int"
    int_value: 0
  }
  config {
    key: "cdma_enhanced_roaming_indicator_for_home_network_int_array"
    int_array {
      item: 1
    }
  }
  config {
    key: "cdma_home_registered_plmn_name_override_bool"
    bool_value: false
  }
  config {
    key: "cdma_home_registered_plmn_name_string"
    text_value: ""
  }
  config {
    key: "config_ims_rcs_package_override_string"
    text_value: "com.google.android.ims"
  }
  config {
    key: "delay_ims_tear_down_until_call_end_bool"
    bool_value: true
  }
  config {
    key: "disable_cdma_activation_code_bool"
    bool_value: false
  }
  config {
    key: "emergency_sms_mode_timer_ms_int"
    int_value: 300000
  }
  config {
    key: "force_home_network_bool"
    bool_value: false
  }
  config {
    key: "force_imei_bool"
    bool_value: false
  }
  config {
    key: "gps.a_glonass_pos_protocol_select"
    text_value: "6"
  }
  config {
    key: "gps.enable_active_sim_emergency_supl"
    bool_value: false
  }
  config {
    key: "gps.longterm_psds_server_1"
    text_value: "https://agnss.goog/lto2.dat"
  }
  config {
    key: "gps.lpp_profile"
    text_value: "2"
  }
  config {
    key: "gps.nfw_proxy_apps"
    text_value: "com.google.android.carrierlocation"
  }
  config {
    key: "gps.normal_psds_server"
    text_value: "https://agnss.goog/pad/xto/prod/rto/2/rto.dat"
  }
  config {
    key: "gps.realtime_psds_server"
    text_value: "https://agnss.goog/rtistatus.dat"
  }
  config {
    key: "gps.supl_ver"
    text_value: "0x20002"
  }
  config {
    key: "ims.ims_user_agent_string"
    text_value: "#MANUFACTURE#_#MODEL#_Android #AV#_#BUILD#"
  }
  config {
    key: "ims.supported_rats_int_array"
    int_array {
      item: 3
      item: 5
      item: 6
    }
  }
  config {
    key: "ims_reasoninfo_mapping_string_array"
    text_array {
      item: "510|Call completed elsewhere|1014"
    }
  }
  config {
    key: "imsemergency.emergency_registration_timer_millis_int"
    int_value: 0
  }
  config {
    key: "imsrtt.text_rr_bandwidth_bps_int"
    int_value: 51
  }
  config {
    key: "imsrtt.text_rs_bandwidth_bps_int"
    int_value: 153
  }
  config {
    key: "imssms.sms_over_ims_supported_rats_int_array"
    int_array {
      item: 3
      item: 6
      item: 5
    }
  }
  config {
    key: "imsss.ut_server_based_services_int_array"
    int_array {
      item: 1
      item: 2
      item: 3
      item: 4
      item: 5
      item: 6
      item: 7
      item: 12
      item: 17
      item: 18
      item: 19
      item: 20
      item: 21
      item: 13
      item: 14
      item: 15
      item: 16
      item: 8
      item: 11
      item: 9
    }
  }
  config {
    key: "imsss.ut_terminal_based_services_int_array"
    int_array {
      item: 0
      item: 10
    }
  }
  config {
    key: "imsss.xcap_over_ut_supported_rats_int_array"
    int_array {
      item: 3
      item: 6
      item: 5
      item: 1
      item: 2
    }
  }
  config {
    key: "imsvoice.amrnb_payload_description_bundle"
    bundle {
      config {
        key: "103"
        bundle {
          config {
            key: "imsvoice.amr_codec_attribute_payload_format_int"
            int_value: 1
          }
        }
      }
    }
  }
  config {
    key: "imsvoice.amrwb_payload_description_bundle"
    bundle {
      config {
        key: "105"
        bundle {
          config {
            key: "imsvoice.amr_codec_attribute_payload_format_int"
            int_value: 1
          }
        }
      }
    }
  }
  config {
    key: "imsvoice.audio_codec_capability_payload_types_bundle"
    bundle {
      config {
        key: "imsvoice.amrnb_payload_type_int_array"
        int_array {
          item: 98
          item: 103
        }
      }
      config {
        key: "imsvoice.amrwb_payload_type_int_array"
        int_array {
          item: 100
          item: 105
        }
      }
      config {
        key: "imsvoice.dtmfnb_payload_type_int_array"
        int_array {
          item: 97
        }
      }
      config {
        key: "imsvoice.dtmfwb_payload_type_int_array"
        int_array {
          item: 96
        }
      }
      config {
        key: "imsvoice.evs_payload_type_int_array"
        int_array {
          item: 127
        }
      }
    }
  }
  config {
    key: "imsvoice.audio_inactivity_call_end_reasons_int_array"
    int_array {
      item: 0
      item: 2
      item: 4
    }
  }
  config {
    key: "imsvoice.evs_payload_description_bundle"
    bundle {
      config {
        key: "127"
        bundle {
          config {
            key: "imsvoice.evs_codec_attribute_bitrate_int_array"
            int_array {
              item: 3
              item: 6
            }
          }
        }
      }
    }
  }
  config {
    key: "imsvt.video_rtcp_inactivity_timer_millis_int"
    int_value: 0
  }
  config {
    key: "imsvt.video_rtp_inactivity_timer_millis_int"
    int_value: 19000
  }
  config {
    key: "imswfc.pidf_short_code_string_array"
    text_array {
    }
  }
  config {
    key: "iwlan.handover_to_wwan_release_delay_second_int"
    int_value: 5
  }
  config {
    key: "iwlan_handover_policy_string_array"
    text_array {
      item: "source=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN|UNKNOWN, target=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN, type=disallowed, capabilities=EIMS|MMS|XCAP|CBS"
      item: "source=IWLAN|UNKNOWN, target=GERAN|UTRAN, type=disallowed, capabilities=IMS"
      item: "source=GERAN|UTRAN, target=IWLAN, type=disallowed, capabilities=IMS"
      item: "source=EUTRAN|NGRAN|IWLAN, target=EUTRAN|NGRAN|IWLAN, type=allowed, capabilities=IMS"
    }
  }
  config {
    key: "qns.block_ipv6_only_wifi_bool"
    bool_value: false
  }
  config {
    key: "qns.fallback_network_quality_evaluation_bool"
    bool_value: false
  }
  config {
    key: "qns.ho_restrict_time_with_low_rtp_quality_int_array"
    int_array {
      item: 60000
      item: 60000
    }
  }
  config {
    key: "qns.idle_eutran_rsrp_int_array"
    int_array {
      item: -115
      item: -120
    }
  }
  config {
    key: "qns.idle_geran_rssi_int_array"
    int_array {
      item: -100
      item: -105
    }
  }
  config {
    key: "qns.idle_ngran_ssrsrp_int_array"
    int_array {
      item: -110
      item: -115
    }
  }
  config {
    key: "qns.idle_utran_rscp_int_array"
    int_array {
      item: -105
      item: -115
    }
  }
  config {
    key: "qns.idle_wifi_rssi_int_array"
    int_array {
      item: -75
      item: -80
    }
  }
  config {
    key: "qns.minimum_handover_guarding_timer_ms_int"
    int_value: 3000
  }
  config {
    key: "qns.mms_rat_preference_int"
    int_value: 3
  }
  config {
    key: "qns.mms_transport_type_int"
    int_value: 2
  }
  config {
    key: "qns.video_eutran_rsrp_int_array"
    int_array {
      item: -115
      item: -120
    }
  }
  config {
    key: "qns.video_geran_rssi_int_array"
    int_array {
      item: -100
      item: -105
    }
  }
  config {
    key: "qns.video_ngran_ssrsrp_int_array"
    int_array {
      item: -110
      item: -115
    }
  }
  config {
    key: "qns.video_utran_rscp_int_array"
    int_array {
      item: -105
      item: -115
    }
  }
  config {
    key: "qns.video_wifi_rssi_int_array"
    int_array {
      item: -75
      item: -80
    }
  }
  config {
    key: "qns.voice_eutran_rsrp_int_array"
    int_array {
      item: -115
      item: -120
    }
  }
  config {
    key: "qns.voice_geran_rssi_int_array"
    int_array {
      item: -100
      item: -105
    }
  }
  config {
    key: "qns.voice_ngran_ssrsrp_int_array"
    int_array {
      item: -110
      item: -115
    }
  }
  config {
    key: "qns.voice_utran_rscp_int_array"
    int_array {
      item: -105
      item: -115
    }
  }
  config {
    key: "qns.voice_wifi_rssi_int_array"
    int_array {
      item: -75
      item: -80
    }
  }
  config {
    key: "qns.xcap_transport_type_int"
    int_value: 2
  }
  config {
    key: "show_apn_setting_cdma_bool"
    bool_value: false
  }
  config {
    key: "show_cdma_choices_bool"
    bool_value: false
  }
  config {
    key: "show_iccid_in_sim_status_bool"
    bool_value: true
  }
  config {
    key: "support_cdma_1x_voice_calls_bool"
    bool_value: false
  }
  config {
    key: "support_swap_after_merge_bool"
    bool_value: true
  }
  config {
    key: "support_tdscdma_bool"
    bool_value: false
  }
  config {
    key: "support_tdscdma_roaming_networks_string_array"
    text_array {
    }
  }
  config {
    key: "telephony_data_setup_retry_rules_string_array"
    text_array {
      item: "capabilities=eims, retry_interval=1000, maximum_retries=20"
      item: "permanent_fail_causes=28|29|30|35|50|51|111|-5|-6|65537|65538|-3|65543|2253|2254, retry_interval=2500"
      item: "capabilities=mms|supl|cbs, retry_interval=2000"
      item: "capabilities=internet|enterprise|dun|ims|fota, retry_interval=2500|3000|5000|10000|15000|20000|40000|60000|120000|240000|600000|1200000|1800000, maximum_retries=20"
    }
  }
  config {
    key: "use_usim_bool"
    bool_value: false
  }
  config {
    key: "world_mode_enabled_bool"
    bool_value: false
  }
}
last_updated {
  seconds: 1709116010
}
