canonical_name: "fizz_ca"
version: 56000000012
apns {
  apn {
    name: "mobile.bm"
    value: "mobile.bm"
    type: DEFAULT
    type: MMS
    type: SUPL
    mmsc: "http://mms.mobile.bm"
    mmsc_proxy: "mmsproxy.mobile.bm"
    mmsc_proxy_port: "80"
    user_editable: false
  }
  apn {
    name: "LTE IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|18|20"
    protocol: IPV6
    roaming_protocol: IPV6
    user_visible: false
    user_editable: false
  }
  apn {
    name: "LTE XCAP"
    value: "xcap"
    type: XCAP
    user_visible: false
    user_editable: false
  }
}
configs {
  config {
    key: "5g_icon_configuration_string"
    text_value: "connected_mmwave:5G_Plus,connected:5G,not_restricted_rrc_idle:5G,not_restricted_rrc_con:5G"
  }
  config {
    key: "additional_nr_advanced_bands_int_array"
    int_array {
      item: 78
    }
  }
  config {
    key: "bsf.bsf_server_port_int"
    int_value: 8080
  }
  config {
    key: "carrier_cross_sim_ims_available_bool"
    bool_value: false
  }
  config {
    key: "carrier_default_wfc_ims_mode_int"
    int_value: 1
  }
  config {
    key: "carrier_default_wfc_ims_roaming_enabled_bool"
    bool_value: true
  }
  config {
    key: "carrier_nr_availabilities_int_array"
    int_array {
      item: 1
    }
  }
  config {
    key: "carrier_supports_ss_over_ut_bool"
    bool_value: true
  }
  config {
    key: "carrier_ussd_method_int"
    int_value: 2
  }
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "editable_enhanced_4g_lte_bool"
    bool_value: false
  }
  config {
    key: "gps.es_extension_sec"
    text_value: "300"
  }
  config {
    key: "hide_lte_plus_data_icon_bool"
    bool_value: false
  }
  config {
    key: "ims.ims_user_agent_string"
    text_value: "Videotron #MODEL# #BUILD#"
  }
  config {
    key: "ims.sip_timer_f_millis_int"
    int_value: 32000
  }
  config {
    key: "ims.sip_timer_j_millis_int"
    int_value: 32000
  }
  config {
    key: "ims_reasoninfo_mapping_string_array"
    text_array {
      item: "510|Call completed elsewhere|1014"
      item: "*|Call is dropped due to Wi-Fi signal is degraded|1407"
    }
  }
  config {
    key: "imsemergency.emergency_over_ims_supported_rats_int_array"
    int_array {
      item: 3
    }
  }
  config {
    key: "imsemergency.emergency_registration_timer_millis_int"
    int_value: 10000
  }
  config {
    key: "imsss.network_initiated_ussd_over_ims_supported_bool"
    bool_value: false
  }
  config {
    key: "imsss.ut_as_server_port_int"
    int_value: 8090
  }
  config {
    key: "imsss.ut_iptype_home_int"
    int_value: 0
  }
  config {
    key: "imsss.ut_iptype_roaming_int"
    int_value: 0
  }
  config {
    key: "imsss.xcap_over_ut_supported_rats_int_array"
    int_array {
      item: 5
      item: 6
      item: 3
      item: 1
      item: 2
    }
  }
  config {
    key: "imsvoice.amrnb_payload_description_bundle"
    bundle {
      config {
        key: "108"
        bundle {
          config {
            key: "imsvoice.amr_codec_attribute_payload_format_int"
            int_value: 1
          }
        }
      }
    }
  }
  config {
    key: "imsvoice.amrwb_payload_description_bundle"
    bundle {
      config {
        key: "110"
        bundle {
          config {
            key: "imsvoice.amr_codec_attribute_payload_format_int"
            int_value: 1
          }
        }
      }
    }
  }
  config {
    key: "imsvoice.audio_codec_capability_payload_types_bundle"
    bundle {
      config {
        key: "imsvoice.amrnb_payload_type_int_array"
        int_array {
          item: 102
          item: 108
        }
      }
      config {
        key: "imsvoice.amrwb_payload_type_int_array"
        int_array {
          item: 104
          item: 110
        }
      }
      config {
        key: "imsvoice.dtmfnb_payload_type_int_array"
        int_array {
          item: 97
        }
      }
      config {
        key: "imsvoice.dtmfwb_payload_type_int_array"
        int_array {
          item: 96
        }
      }
    }
  }
  config {
    key: "imsvoice.conference_factory_uri_string"
    text_value: "conference@factory.ims.mnc500.mcc302.3gppnetwork.org"
  }
  config {
    key: "imsvoice.minimum_session_expires_timer_sec_int"
    int_value: 600
  }
  config {
    key: "imsvoice.prack_supported_for_18x_bool"
    bool_value: true
  }
  config {
    key: "imsvoice.srvcc_type_int_array"
    int_array {
    }
  }
  config {
    key: "imswfc.emergency_call_over_emergency_pdn_bool"
    bool_value: true
  }
  config {
    key: "is_ims_conference_size_enforced_bool"
    bool_value: true
  }
  config {
    key: "iwlan_handover_policy_string_array"
    text_array {
      item: "source=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN|UNKNOWN, target=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN, type=disallowed, capabilities=EIMS|MMS|XCAP|CBS"
      item: "source=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN|UNKNOWN, target=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN, roaming=true, type=disallowed, capabilities=IMS"
      item: "source=IWLAN|UNKNOWN, target=GERAN|UTRAN, type=disallowed, capabilities=IMS"
      item: "source=GERAN|UTRAN, target=IWLAN, type=disallowed, capabilities=IMS"
      item: "source=EUTRAN|NGRAN|IWLAN, target=EUTRAN|NGRAN|IWLAN, type=allowed, capabilities=IMS"
    }
  }
  config {
    key: "lte_plus_threshold_bandwidth_khz_int"
    int_value: 0
  }
  config {
    key: "maxImageHeight"
    int_value: 1944
  }
  config {
    key: "maxImageWidth"
    int_value: 2592
  }
  config {
    key: "maxMessageSize"
    int_value: 3072000
  }
  config {
    key: "maxSubjectLength"
    int_value: 80
  }
  config {
    key: "non_roaming_operator_string_array"
    text_array {
      item: "302"
    }
  }
  config {
    key: "qns.idle_eutran_rsrp_int_array"
    int_array {
      item: -114
      item: -120
    }
  }
  config {
    key: "qns.idle_utran_rscp_int_array"
    int_array {
      item: -103
      item: -110
    }
  }
  config {
    key: "qns.idle_wifi_rssi_int_array"
    int_array {
      item: -74
      item: -80
    }
  }
  config {
    key: "qns.sos_transport_type_int"
    int_value: 2
  }
  config {
    key: "qns.video_eutran_rsrp_int_array"
    int_array {
      item: -114
      item: -120
    }
  }
  config {
    key: "qns.video_utran_rscp_int_array"
    int_array {
      item: -103
      item: -110
    }
  }
  config {
    key: "qns.video_wifi_rssi_int_array"
    int_array {
      item: -74
      item: -80
    }
  }
  config {
    key: "qns.voice_eutran_rsrp_int_array"
    int_array {
      item: -114
      item: -120
    }
  }
  config {
    key: "qns.voice_utran_rscp_int_array"
    int_array {
      item: -103
      item: -110
    }
  }
  config {
    key: "qns.voice_wifi_rssi_int_array"
    int_array {
      item: -74
      item: -80
    }
  }
  config {
    key: "read_only_apn_types_string_array"
    text_array {
    }
  }
  config {
    key: "recipientLimit"
    int_value: 20
  }
  config {
    key: "smsToMmsTextThreshold"
    int_value: 6
  }
  config {
    key: "support_no_reply_timer_for_cfnry_bool"
    bool_value: false
  }
  config {
    key: "use_wfc_home_network_mode_in_roaming_network_bool"
    bool_value: true
  }
  config {
    key: "volte_replacement_rat_int"
    int_value: 3
  }
  config {
    key: "wfc_emergency_address_carrier_app_string"
    text_value: "com.google.android.wfcactivation/.WfcActivationCanadaActivity"
  }
  config {
    key: "wfc_spn_format_idx_int"
    int_value: 1
  }
}
last_updated {
  seconds: 1708635180
}
