canonical_name: "luckymobile_ca"
version: 56000000008
apns {
  apn {
    name: "Lucky Mobile"
    value: "connect"
    type: IA
    type: DEFAULT
    type: DUN
    type: SUPL
    type: MMS
    type: HIPRI
    type: XCAP
    bearer_bitmask: "1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|17|20"
    mmsc: "http://mms.luckymobile.ca/mms/wapenc"
    protocol: IPV4V6
    user_editable: false
  }
  apn {
    name: "Lucky Mobile Apps"
    value: "apps.bell.ca"
    type: MMS
    type: XCAP
    bearer_bitmask: "18"
    mmsc: "http://mms.bell.ca/mms/wapenc"
    protocol: IPV4V6
    user_visible: false
  }
  apn {
    name: "Lucky Mobile IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV6
    roaming_protocol: IPV6
    user_visible: false
  }
  apn {
    name: "Lucky Mobile SOS"
    value: "sos"
    type: EMERGENCY
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "bsf.bsf_server_fqdn_string"
    text_value: "bsf.ims.bell.ca"
  }
  config {
    key: "bsf.bsf_server_port_int"
    int_value: 443
  }
  config {
    key: "bsf.bsf_transport_type_int"
    int_value: 3
  }
  config {
    key: "carrier_cross_sim_ims_available_bool"
    bool_value: false
  }
  config {
    key: "carrier_supports_ss_over_ut_bool"
    bool_value: true
  }
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "emailGatewayNumber"
    text_value: "6245"
  }
  config {
    key: "hide_enhanced_4g_lte_bool"
    bool_value: true
  }
  config {
    key: "hide_lte_plus_data_icon_bool"
    bool_value: false
  }
  config {
    key: "ims.gruu_enabled_bool"
    bool_value: true
  }
  config {
    key: "ims.ims_pdn_enabled_in_no_vops_support_int_array"
    int_array {
      item: 0
      item: 1
    }
  }
  config {
    key: "ims.ims_user_agent_string"
    text_value: "#MANUFACTURE# #MODEL# #BUILD#"
  }
  config {
    key: "ims.registration_subscribe_expiry_timer_sec_int"
    int_value: 86400
  }
  config {
    key: "ims.sip_over_ipsec_enabled_bool"
    bool_value: false
  }
  config {
    key: "ims.sip_timer_f_millis_int"
    int_value: 32000
  }
  config {
    key: "imsemergency.emergency_registration_timer_millis_int"
    int_value: 10000
  }
  config {
    key: "imsss.network_initiated_ussd_over_ims_supported_bool"
    bool_value: false
  }
  config {
    key: "imsss.ut_as_server_fqdn_string"
    text_value: "naf.ims.bell.ca"
  }
  config {
    key: "imsss.ut_as_server_port_int"
    int_value: 443
  }
  config {
    key: "imsss.ut_requires_ims_registration_bool"
    bool_value: true
  }
  config {
    key: "imsss.ut_transport_type_int"
    int_value: 3
  }
  config {
    key: "imsss.xcap_over_ut_supported_rats_int_array"
    int_array {
    }
  }
  config {
    key: "imsvoice.amrnb_payload_description_bundle"
    bundle {
      config {
        key: "101"
        bundle {
          config {
            key: "imsvoice.amr_codec_attribute_payload_format_int"
            int_value: 1
          }
        }
      }
    }
  }
  config {
    key: "imsvoice.amrwb_payload_description_bundle"
    bundle {
      config {
        key: "103"
        bundle {
          config {
            key: "imsvoice.amr_codec_attribute_modeset_int_array"
            int_array {
              item: 0
              item: 1
              item: 2
            }
          }
          config {
            key: "imsvoice.amr_codec_attribute_payload_format_int"
            int_value: 1
          }
        }
      }
      config {
        key: "104"
        bundle {
          config {
            key: "imsvoice.amr_codec_attribute_modeset_int_array"
            int_array {
              item: 0
              item: 1
              item: 2
            }
          }
        }
      }
    }
  }
  config {
    key: "imsvoice.audio_as_bandwidth_kbps_int"
    int_value: 50
  }
  config {
    key: "imsvoice.audio_codec_capability_payload_types_bundle"
    bundle {
      config {
        key: "imsvoice.amrnb_payload_type_int_array"
        int_array {
          item: 102
          item: 101
        }
      }
      config {
        key: "imsvoice.amrwb_payload_type_int_array"
        int_array {
          item: 104
          item: 103
        }
      }
      config {
        key: "imsvoice.dtmfnb_payload_type_int_array"
        int_array {
          item: 97
        }
      }
      config {
        key: "imsvoice.dtmfwb_payload_type_int_array"
        int_array {
          item: 96
        }
      }
      config {
        key: "imsvoice.evs_payload_type_int_array"
        int_array {
          item: 126
        }
      }
    }
  }
  config {
    key: "imsvoice.audio_rr_bandwidth_bps_int"
    int_value: 1875
  }
  config {
    key: "imsvoice.audio_rs_bandwidth_bps_int"
    int_value: 625
  }
  config {
    key: "imsvoice.conference_factory_uri_string"
    text_value: "conf@ims.bell.ca"
  }
  config {
    key: "imsvoice.evs_payload_description_bundle"
    bundle {
      config {
        key: "126"
        bundle {
          config {
            key: "imsvoice.evs_codec_attribute_bitrate_int_array"
            int_array {
              item: 4
              item: 6
            }
          }
          config {
            key: "imsvoice.evs_codec_attribute_ch_aw_recv_int"
            int_value: 2
          }
        }
      }
    }
  }
  config {
    key: "imsvoice.minimum_session_expires_timer_sec_int"
    int_value: 600
  }
  config {
    key: "imsvoice.mo_call_request_timeout_millis_int"
    int_value: 8000
  }
  config {
    key: "imsvoice.ringback_timer_millis_int"
    int_value: 150000
  }
  config {
    key: "imsvoice.ringing_timer_millis_int"
    int_value: 30000
  }
  config {
    key: "imsvoice.session_privacy_type_int"
    int_value: 2
  }
  config {
    key: "imsvoice.srvcc_type_int_array"
    int_array {
      item: 0
      item: 1
      item: 3
    }
  }
  config {
    key: "imswfc.emergency_call_over_emergency_pdn_bool"
    bool_value: true
  }
  config {
    key: "maxImageHeight"
    int_value: 1944
  }
  config {
    key: "maxImageWidth"
    int_value: 2592
  }
  config {
    key: "maxMessageSize"
    int_value: 614400
  }
  config {
    key: "maxSubjectLength"
    int_value: 80
  }
  config {
    key: "non_roaming_operator_string_array"
    text_array {
      item: "302"
    }
  }
  config {
    key: "read_only_apn_types_string_array"
    text_array {
    }
  }
  config {
    key: "recipientLimit"
    int_value: 20
  }
  config {
    key: "smsToMmsTextThreshold"
    int_value: 8
  }
  config {
    key: "voicemail_notification_persistent_bool"
    bool_value: true
  }
}
last_updated {
  seconds: 1709519140
}
