canonical_name: "povo_jp"
version: 56000000008
apns {
  apn {
    name: "povo"
    value: "povo.jp"
    type: DEFAULT
    type: SUPL
    type: HIPRI
    protocol: IPV4V6
    user_editable: false
  }
  apn {
    name: "povo OTA"
    value: "admin.au-net.ne.jp"
    type: FOTA
    bearer_bitmask: "1|2|3|9|10|11|13|14|15|20"
    authtype: 0
    protocol: IPV4V6
    user_visible: false
  }
  apn {
    name: "povo IMS"
    value: "IMS"
    type: IMS
    bearer_bitmask: "14|18|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
  apn {
    name: "povo Emergency"
    value: "sos"
    type: EMERGENCY
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
  apn {
    name: "povo XCAP"
    value: "xcap"
    type: XCAP
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "5g_icon_configuration_string"
    text_value: "connected_mmwave:5G,connected:5G,not_restricted_rrc_idle:5G"
  }
  config {
    key: "5g_icon_display_grace_period_string"
    text_value: "connected_mmwave,legacy,31;connected,legacy,31;connected_mmwave,not_restricted_rrc_con,31;connected,not_restricted_rrc_con,31;not_restricted_rrc_idle,not_restricted_rrc_con,15"
  }
  config {
    key: "5g_nr_ssrsrp_thresholds_int_array"
    int_array {
      item: -128
      item: -118
      item: -108
      item: -98
    }
  }
  config {
    key: "allow_emergency_numbers_in_call_log_bool"
    bool_value: true
  }
  config {
    key: "allow_hold_call_during_emergency_bool"
    bool_value: false
  }
  config {
    key: "allow_metered_network_for_cert_download_bool"
    bool_value: false
  }
  config {
    key: "call_forwarding_when_busy_supported_bool"
    bool_value: false
  }
  config {
    key: "call_forwarding_when_unanswered_supported_bool"
    bool_value: false
  }
  config {
    key: "call_forwarding_when_unreachable_supported_bool"
    bool_value: false
  }
  config {
    key: "carrier_additional_cbs_channels_strings"
    text_array {
      item: "0xA003:type=other, emergency=true"
    }
  }
  config {
    key: "carrier_certificate_string_array"
    text_array {
      item: "108897103871B684844AA7C791E0C812AB3966576FB5D3713C2D11794C0600AD:com.kddi.cs.app001"
      item: "5EA3181DF228B4F8B0DECC10B21783F8C6C397F1290F2395FE3E6FDB2B52E991:jp.uqmobile.uqmobileportalapp"
      item: "891ABE3F0A0D794AD46200DC2374AFF61AFA82711C360EE0CB49C3E6BB2BA006:jp.auone.wallet"
      item: "1001568BB4A4E65F68C8B0F2E5C9EBC97FF719898F39E421DAF29A8DACEAAF1B:com.kddi.android.cmail"
    }
  }
  config {
    key: "carrier_name_override_bool"
    bool_value: true
  }
  config {
    key: "carrier_name_string"
    text_value: "povo"
  }
  config {
    key: "carrier_nr_availabilities_int_array"
    int_array {
      item: 1
      item: 2
    }
  }
  config {
    key: "carrier_supports_ss_over_ut_bool"
    bool_value: true
  }
  config {
    key: "carrier_ussd_method_int"
    int_value: 2
  }
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "default_vm_number_string"
    text_value: "1417"
  }
  config {
    key: "disable_dun_apn_while_roaming_with_preset_apn_bool"
    bool_value: true
  }
  config {
    key: "emergency_number_prefix_string_array"
    text_array {
      item: "184"
      item: "186"
    }
  }
  config {
    key: "enabledMMS"
    bool_value: false
  }
  config {
    key: "format_incoming_number_to_national_for_jp_bool"
    bool_value: true
  }
  config {
    key: "gps.es_extension_sec"
    text_value: "300"
  }
  config {
    key: "gps.lpp_profile"
    text_value: "1"
  }
  config {
    key: "gps.supl_ver"
    text_value: "0x20002"
  }
  config {
    key: "hide_enhanced_4g_lte_bool"
    bool_value: true
  }
  config {
    key: "ims.ims_user_agent_string"
    text_value: "#MODEL#_#BUILD#"
  }
  config {
    key: "ims.ipsec_encryption_algorithms_int_array"
    int_array {
      item: 0
    }
  }
  config {
    key: "ims.ipv4_sip_mtu_size_cellular_int"
    int_value: 1440
  }
  config {
    key: "ims.ipv6_sip_mtu_size_cellular_int"
    int_value: 1440
  }
  config {
    key: "ims.registration_retry_base_timer_millis_int"
    int_value: 10000
  }
  config {
    key: "ims.request_uri_type_int"
    int_value: 1
  }
  config {
    key: "ims.sip_preferred_transport_int"
    int_value: 0
  }
  config {
    key: "ims.sip_timer_b_millis_int"
    int_value: 10000
  }
  config {
    key: "ims.sip_timer_c_millis_int"
    int_value: 180000
  }
  config {
    key: "ims.sip_timer_d_millis_int"
    int_value: 128000
  }
  config {
    key: "ims.sip_timer_f_millis_int"
    int_value: 30000
  }
  config {
    key: "ims.sip_timer_h_millis_int"
    int_value: 30000
  }
  config {
    key: "ims.sip_timer_j_millis_int"
    int_value: 30000
  }
  config {
    key: "ims.sip_timer_t1_millis_int"
    int_value: 3000
  }
  config {
    key: "ims_conference_size_limit_int"
    int_value: 2
  }
  config {
    key: "imsemergency.emergency_over_ims_supported_rats_int_array"
    int_array {
      item: 3
    }
  }
  config {
    key: "imsi_key_availability_int"
    int_value: 0
  }
  config {
    key: "imsi_key_download_url_string"
    text_value: ""
  }
  config {
    key: "imsss.network_initiated_ussd_over_ims_supported_bool"
    bool_value: false
  }
  config {
    key: "imsss.ut_as_server_port_int"
    int_value: 8090
  }
  config {
    key: "imsss.ut_server_based_services_int_array"
    int_array {
      item: 1
      item: 3
      item: 4
      item: 7
      item: 6
      item: 5
      item: 2
      item: 0
    }
  }
  config {
    key: "imsss.ut_terminal_based_services_int_array"
    int_array {
      item: 10
    }
  }
  config {
    key: "imsss.xcap_over_ut_supported_rats_int_array"
    int_array {
      item: 6
      item: 3
    }
  }
  config {
    key: "imsvoice.amrwb_payload_description_bundle"
    bundle {
      config {
        key: "104"
        bundle {
          config {
            key: "imsvoice.amr_codec_attribute_modeset_int_array"
            int_array {
              item: 0
              item: 1
              item: 2
            }
          }
        }
      }
    }
  }
  config {
    key: "imsvoice.audio_codec_capability_payload_types_bundle"
    bundle {
      config {
        key: "imsvoice.amrnb_payload_type_int_array"
        int_array {
          item: 102
        }
      }
      config {
        key: "imsvoice.amrwb_payload_type_int_array"
        int_array {
          item: 104
        }
      }
      config {
        key: "imsvoice.dtmfnb_payload_type_int_array"
        int_array {
          item: 97
        }
      }
      config {
        key: "imsvoice.dtmfwb_payload_type_int_array"
        int_array {
          item: 96
        }
      }
      config {
        key: "imsvoice.evs_payload_type_int_array"
        int_array {
          item: 127
        }
      }
    }
  }
  config {
    key: "imsvoice.audio_rr_bandwidth_bps_int"
    int_value: 0
  }
  config {
    key: "imsvoice.audio_rs_bandwidth_bps_int"
    int_value: 0
  }
  config {
    key: "imsvoice.conference_factory_uri_string"
    text_value: "mmtel@3pty-factory.ims.mnc051.mcc440.3gppnetwork.org"
  }
  config {
    key: "imsvoice.dedicated_bearer_wait_timer_millis_int"
    int_value: 10000
  }
  config {
    key: "imsvoice.evs_payload_description_bundle"
    bundle {
      config {
        key: "127"
        bundle {
          config {
            key: "imsvoice.evs_codec_attribute_bandwidth_int"
            int_value: 2
          }
          config {
            key: "imsvoice.evs_codec_attribute_bitrate_int_array"
            int_array {
              item: 4
              item: 4
            }
          }
          config {
            key: "imsvoice.evs_codec_attribute_ch_aw_recv_int"
            int_value: 2
          }
        }
      }
    }
  }
  config {
    key: "imsvoice.mo_call_request_timeout_millis_int"
    int_value: 10000
  }
  config {
    key: "imsvoice.prack_supported_for_18x_bool"
    bool_value: true
  }
  config {
    key: "imsvoice.ringback_timer_millis_int"
    int_value: 3600000
  }
  config {
    key: "imsvoice.ringing_timer_millis_int"
    int_value: 80000
  }
  config {
    key: "imsvoice.session_privacy_type_int"
    int_value: 2
  }
  config {
    key: "imsvoice.srvcc_type_int_array"
    int_array {
    }
  }
  config {
    key: "is_ims_conference_size_enforced_bool"
    bool_value: true
  }
  config {
    key: "lte_endc_using_user_data_for_rrc_detection_bool"
    bool_value: true
  }
  config {
    key: "min_udp_port_4500_nat_timeout_sec_int"
    int_value: 120
  }
  config {
    key: "nr_timers_reset_if_non_endc_and_rrc_idle_bool"
    bool_value: true
  }
  config {
    key: "prefer_2g_bool"
    bool_value: false
  }
  config {
    key: "preferred_ike_protocol_int"
    int_value: 40
  }
  config {
    key: "show_4g_for_lte_data_icon_bool"
    bool_value: true
  }
  config {
    key: "show_blocking_pay_phone_option_bool"
    bool_value: true
  }
  config {
    key: "support_clir_network_default_bool"
    bool_value: false
  }
  config {
    key: "support_ims_conference_event_package_bool"
    bool_value: false
  }
  config {
    key: "wifi.carrier_profiles_version_int"
    int_value: -1
  }
  config {
    key: "wifi.network_profiles_string_array"
    text_array {
    }
  }
}
last_updated {
  seconds: 1706100369
}
