canonical_name: "test001_zz"
version: 62000000003
apns {
  apn {
    name: "TEST_DEFAULT"
    value: "default"
    type: DEFAULT
  }
}
configs {
  config {
    key: "carrier_nr_availabilities_int_array"
    int_array {
      item: 1
      item: 2
    }
  }
  config {
    key: "imsemergency.emergency_over_ims_supported_rats_int_array"
    int_array {
      item: 3
    }
  }
  config {
    key: "imsss.xcap_over_ut_supported_rats_int_array"
    int_array {
    }
  }
  config {
    key: "imsvoice.evs_payload_description_bundle"
    bundle {
      config {
        key: "127"
        bundle {
          config {
            key: "imsvoice.evs_codec_attribute_bitrate_int_array"
            int_array {
              item: 0
              item: 6
            }
          }
        }
      }
    }
  }
  config {
    key: "vendor.ims.carrier_config_use_aosp_ims_config_bool"
    bool_value: false
  }
}
last_updated {
  seconds: 1724979935
}
