canonical_name: "tmobile_cz"
version: 56000000012
apns {
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|18|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
    lingering_network_type_bitmask: "1|2|3|8|9|10|13|14|15|18|20"
  }
  apn {
    name: "HOS"
    value: "hos"
    type: MMS
    type: XCAP
    authtype: 1
    mmsc: "http://mms"
    mmsc_proxy: "10.0.0.10"
    mmsc_proxy_port: "80"
    protocol: IPV4V6
    user_visible: false
  }
  apn {
    name: "Internet"
    value: "internet.t-mobile.cz"
    type: DEFAULT
    type: SUPL
    authtype: 1
    protocol: IPV4V6
  }
}
configs {
  config {
    key: "carrier_supports_ss_over_ut_bool"
    bool_value: true
  }
  config {
    key: "carrier_ussd_method_int"
    int_value: 1
  }
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "carrier_wfc_ims_available_bool"
    bool_value: true
  }
  config {
    key: "display_hd_audio_property_bool"
    bool_value: false
  }
  config {
    key: "hide_enhanced_4g_lte_bool"
    bool_value: true
  }
  config {
    key: "ims.ims_user_agent_string"
    text_value: "#MANUFACTURE# - #MODEL# - #BUILD#"
  }
  config {
    key: "ims.keep_pdn_up_in_no_vops_bool"
    bool_value: true
  }
  config {
    key: "ims.request_uri_type_int"
    int_value: 1
  }
  config {
    key: "imsemergency.emergency_over_ims_supported_rats_int_array"
    int_array {
      item: 3
    }
  }
  config {
    key: "imsemergency.emergency_registration_timer_millis_int"
    int_value: 3000
  }
  config {
    key: "imsss.ut_iptype_roaming_int"
    int_value: 0
  }
  config {
    key: "imsss.xcap_over_ut_supported_rats_int_array"
    int_array {
      item: 5
      item: 6
      item: 3
      item: 1
      item: 2
    }
  }
  config {
    key: "imsvoice.audio_codec_capability_payload_types_bundle"
    bundle {
      config {
        key: "imsvoice.amrnb_payload_type_int_array"
        int_array {
          item: 102
        }
      }
      config {
        key: "imsvoice.amrwb_payload_type_int_array"
        int_array {
          item: 104
        }
      }
      config {
        key: "imsvoice.dtmfnb_payload_type_int_array"
        int_array {
          item: 97
        }
      }
      config {
        key: "imsvoice.dtmfwb_payload_type_int_array"
        int_array {
          item: 96
        }
      }
      config {
        key: "imsvoice.evs_payload_type_int_array"
        int_array {
          item: 126
        }
      }
    }
  }
  config {
    key: "imsvoice.evs_payload_description_bundle"
    bundle {
      config {
        key: "126"
        bundle {
          config {
            key: "imsvoice.evs_codec_attribute_bitrate_int_array"
            int_array {
              item: 0
              item: 6
            }
          }
        }
      }
    }
  }
  config {
    key: "telephony_data_setup_retry_rules_string_array"
    text_array {
      item: "capabilities=eims, retry_interval=1000, maximum_retries=20"
      item: "permanent_fail_causes=8|27|28|29|30|32|35|50|51|111|-5|-6|65537|65538|-3|65543|2253|2254, retry_interval=2500"
      item: "capabilities=mms|supl|cbs, retry_interval=2000"
      item: "capabilities=internet|enterprise|dun|ims|fota, retry_interval=2500|3000|5000|10000|15000|20000|40000|60000|120000|240000|600000|1200000|1800000, maximum_retries=20"
    }
  }
  config {
    key: "volte_replacement_rat_int"
    int_value: 3
  }
  config {
    key: "wfc_spn_format_idx_int"
    int_value: 1
  }
}
last_updated {
  seconds: 1707299261
}
