canonical_name: "turkcell_tr"
version: 56000000001
apns {
  apn {
    name: "TURKCELL INTERNET"
    value: "internet"
    type: DEFAULT
    type: SUPL
  }
  apn {
    name: "TURKCELL MMS"
    value: "mms"
    type: MMS
    user: "mms"
    password: "mms"
    authtype: 1
    mmsc: "http://mms.turkcell.com.tr/servlets/mms"
    mmsc_proxy: "212.252.169.217"
    mmsc_proxy_port: "8080"
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "maxImageHeight"
    int_value: 1944
  }
  config {
    key: "maxImageWidth"
    int_value: 2592
  }
  config {
    key: "maxMessageSize"
    int_value: 512000
  }
}
last_updated {
  seconds: 1708635195
}
