canonical_name: "a1_mk"
version: 56000000002
apns {
  apn {
    name: "Internet"
    value: "vipoperator"
    type: DEFAULT
    type: SUPL
    proxy: "78.40.0.1"
    port: "8080"
    user: "vipoperator"
    password: "vipoperator"
  }
  apn {
    name: "MMS"
    value: "vipoperator.mms"
    type: MMS
    user: "vipoperator"
    password: "vipoperator"
    mmsc: "http://mmsc.vipoperator.com.mk"
    mmsc_proxy: "78.40.0.1"
    mmsc_proxy_port: "8080"
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    user_visible: false
  }
  apn {
    name: "hos"
    value: "hos"
    type: XCAP
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "carrier_supports_ss_over_ut_bool"
    bool_value: true
  }
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "hide_enhanced_4g_lte_bool"
    bool_value: true
  }
  config {
    key: "maxImageHeight"
    int_value: 1944
  }
  config {
    key: "maxImageWidth"
    int_value: 2592
  }
  config {
    key: "maxMessageSize"
    int_value: 256000
  }
}
last_updated {
  seconds: 1708635204
}
