canonical_name: "kddimvno_jp"
version: 56000000005
apns {
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|18|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
  apn {
    name: "Rakuten mobile"
    value: "a.rmobile.jp"
    type: DEFAULT
    type: SUPL
    user: "rakuten@vdm"
    password: "0000"
    authtype: 3
  }
  apn {
    name: "KDDI JP Emergency"
    value: "sos"
    type: EMERGENCY
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "5g_nr_ssrsrp_thresholds_int_array"
    int_array {
      item: -128
      item: -118
      item: -108
      item: -98
    }
  }
  config {
    key: "allow_emergency_numbers_in_call_log_bool"
    bool_value: true
  }
  config {
    key: "allow_hold_call_during_emergency_bool"
    bool_value: false
  }
  config {
    key: "carrier_additional_cbs_channels_strings"
    text_array {
      item: "0xA003:type=other, emergency=true"
    }
  }
  config {
    key: "carrier_ussd_method_int"
    int_value: 2
  }
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "default_vm_number_string"
    text_value: "1417"
  }
  config {
    key: "hide_enhanced_4g_lte_bool"
    bool_value: true
  }
  config {
    key: "ims.ims_user_agent_string"
    text_value: "#MODEL#_#BUILD#"
  }
  config {
    key: "ims.ipsec_encryption_algorithms_int_array"
    int_array {
      item: 0
    }
  }
  config {
    key: "ims.ipv4_sip_mtu_size_cellular_int"
    int_value: 1440
  }
  config {
    key: "ims.ipv6_sip_mtu_size_cellular_int"
    int_value: 1440
  }
  config {
    key: "ims.registration_retry_base_timer_millis_int"
    int_value: 10000
  }
  config {
    key: "ims.request_uri_type_int"
    int_value: 1
  }
  config {
    key: "ims.sip_preferred_transport_int"
    int_value: 0
  }
  config {
    key: "ims.sip_timer_b_millis_int"
    int_value: 10000
  }
  config {
    key: "ims.sip_timer_c_millis_int"
    int_value: 180000
  }
  config {
    key: "ims.sip_timer_d_millis_int"
    int_value: 128000
  }
  config {
    key: "ims.sip_timer_f_millis_int"
    int_value: 30000
  }
  config {
    key: "ims.sip_timer_h_millis_int"
    int_value: 30000
  }
  config {
    key: "ims.sip_timer_j_millis_int"
    int_value: 30000
  }
  config {
    key: "ims.sip_timer_t1_millis_int"
    int_value: 3000
  }
  config {
    key: "ims_conference_size_limit_int"
    int_value: 2
  }
  config {
    key: "imsemergency.emergency_over_ims_supported_rats_int_array"
    int_array {
      item: 3
    }
  }
  config {
    key: "imsss.network_initiated_ussd_over_ims_supported_bool"
    bool_value: false
  }
  config {
    key: "imsss.ut_as_server_port_int"
    int_value: 8090
  }
  config {
    key: "imsss.ut_server_based_services_int_array"
    int_array {
      item: 1
      item: 3
      item: 4
      item: 7
      item: 6
      item: 5
      item: 2
      item: 0
    }
  }
  config {
    key: "imsss.ut_terminal_based_services_int_array"
    int_array {
      item: 10
    }
  }
  config {
    key: "imsss.xcap_over_ut_supported_rats_int_array"
    int_array {
    }
  }
  config {
    key: "imsvoice.amrwb_payload_description_bundle"
    bundle {
      config {
        key: "104"
        bundle {
          config {
            key: "imsvoice.amr_codec_attribute_modeset_int_array"
            int_array {
              item: 0
              item: 1
              item: 2
            }
          }
        }
      }
    }
  }
  config {
    key: "imsvoice.audio_codec_capability_payload_types_bundle"
    bundle {
      config {
        key: "imsvoice.amrnb_payload_type_int_array"
        int_array {
          item: 102
        }
      }
      config {
        key: "imsvoice.amrwb_payload_type_int_array"
        int_array {
          item: 104
        }
      }
      config {
        key: "imsvoice.dtmfnb_payload_type_int_array"
        int_array {
          item: 97
        }
      }
      config {
        key: "imsvoice.dtmfwb_payload_type_int_array"
        int_array {
          item: 96
        }
      }
      config {
        key: "imsvoice.evs_payload_type_int_array"
        int_array {
          item: 127
        }
      }
    }
  }
  config {
    key: "imsvoice.audio_rr_bandwidth_bps_int"
    int_value: 0
  }
  config {
    key: "imsvoice.audio_rs_bandwidth_bps_int"
    int_value: 0
  }
  config {
    key: "imsvoice.conference_factory_uri_string"
    text_value: "mmtel@3pty-factory.ims.mnc051.mcc440.3gppnetwork.org"
  }
  config {
    key: "imsvoice.dedicated_bearer_wait_timer_millis_int"
    int_value: 10000
  }
  config {
    key: "imsvoice.evs_payload_description_bundle"
    bundle {
      config {
        key: "127"
        bundle {
          config {
            key: "imsvoice.evs_codec_attribute_bandwidth_int"
            int_value: 2
          }
          config {
            key: "imsvoice.evs_codec_attribute_bitrate_int_array"
            int_array {
              item: 4
              item: 4
            }
          }
          config {
            key: "imsvoice.evs_codec_attribute_ch_aw_recv_int"
            int_value: 2
          }
        }
      }
    }
  }
  config {
    key: "imsvoice.mo_call_request_timeout_millis_int"
    int_value: 10000
  }
  config {
    key: "imsvoice.prack_supported_for_18x_bool"
    bool_value: true
  }
  config {
    key: "imsvoice.ringback_timer_millis_int"
    int_value: 3600000
  }
  config {
    key: "imsvoice.ringing_timer_millis_int"
    int_value: 80000
  }
  config {
    key: "imsvoice.session_privacy_type_int"
    int_value: 2
  }
  config {
    key: "imsvoice.srvcc_type_int_array"
    int_array {
    }
  }
  config {
    key: "is_ims_conference_size_enforced_bool"
    bool_value: true
  }
  config {
    key: "read_only_apn_types_string_array"
    text_array {
    }
  }
  config {
    key: "show_4g_for_lte_data_icon_bool"
    bool_value: true
  }
  config {
    key: "show_blocking_pay_phone_option_bool"
    bool_value: true
  }
  config {
    key: "support_ims_conference_event_package_bool"
    bool_value: false
  }
  config {
    key: "vendor.ims.carrier_config_use_aosp_ims_config_bool"
    bool_value: true
  }
}
last_updated {
  seconds: 1706100394
}
