canonical_name: "mobifone_vn"
version: 60000000001
apns {
  apn {
    name: "Mobi-wap-gprs 2"
    value: "m-wap"
    type: DEFAULT
    type: SUPL
    user: "mms"
    password: "mms"
    authtype: 1
  }
  apn {
    name: "Mobi-gprs-mms"
    value: "m-i090"
    type: MMS
    user: "mms"
    password: "mms"
    authtype: 1
    mmsc: "http://203.162.21.114/mmsc"
    mmsc_proxy: "203.162.21.114"
    mmsc_proxy_port: "8080"
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
}
last_updated {
  seconds: 1720164596
}
