canonical_name: "spectrummsotest_us"
version: 62000000001
apns {
  apn {
    name: "XM LAB1"
    value: "internet"
    type: DEFAULT
    protocol: IPV4V6
  }
  apn {
    name: "XM LAB1"
    value: "admin.comcast"
    type: DEFAULT
    protocol: IPV4V6
  }
}
configs {
  config {
    key: "always_show_primary_signal_bar_in_opportunistic_network_boolean"
    bool_value: true
  }
  config {
    key: "boosted_lte_earfcns_string_array"
    text_array {
      item: "600-1199"
      item: "1950-2399"
    }
  }
  config {
    key: "carrier_nr_availabilities_int_array"
    int_array {
      item: 1
    }
  }
  config {
    key: "lte_earfcns_rsrp_boost_int"
    int_value: 6
  }
  config {
    key: "lte_rsrp_thresholds_int_array"
    int_array {
      item: -115
      item: -105
      item: -95
      item: -85
    }
  }
  config {
    key: "opportunistic_network_data_switch_exit_hysteresis_time_long"
    long_value: 2000
  }
  config {
    key: "opportunistic_network_data_switch_hysteresis_time_long"
    long_value: 2000
  }
  config {
    key: "opportunistic_network_entry_threshold_rsrp_int"
    int_value: -111
  }
  config {
    key: "opportunistic_network_entry_threshold_rssnr_int"
    int_value: 10
  }
  config {
    key: "opportunistic_network_exit_threshold_rsrp_int"
    int_value: -120
  }
  config {
    key: "opportunistic_network_exit_threshold_rssnr_int"
    int_value: 9
  }
}
last_updated {
  seconds: 1725936032
}
