canonical_name: "swisscom_li"
version: 56000000008
apns {
  apn {
    name: "Swisscom MMS"
    value: "event.swisscom.ch"
    type: MMS
    mmsc: "http://mms.natel.ch:8079"
    mmsc_proxy: "192.168.210.2"
    mmsc_proxy_port: "8080"
  }
  apn {
    name: "Swisscom Services"
    value: "gprs.swisscom.ch"
    type: DEFAULT
    type: SUPL
  }
  apn {
    name: "ims"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|18|20"
    protocol: IPV6
    roaming_protocol: IPV4V6
    user_visible: false
  }
  apn {
    name: "HOS"
    value: "hos"
    type: XCAP
    user_visible: false
  }
}
configs {
  config {
    key: "allow_metered_network_for_cert_download_bool"
    bool_value: true
  }
  config {
    key: "bsf.bsf_server_fqdn_string"
    text_value: "bsf.mnc001.mcc228.pub.3gppnetwork.org"
  }
  config {
    key: "bsf.bsf_server_port_int"
    int_value: 8081
  }
  config {
    key: "carrier_allow_transfer_ims_call_bool"
    bool_value: true
  }
  config {
    key: "carrier_default_wfc_ims_enabled_bool"
    bool_value: false
  }
  config {
    key: "carrier_default_wfc_ims_mode_int"
    int_value: 1
  }
  config {
    key: "carrier_default_wfc_ims_roaming_enabled_bool"
    bool_value: true
  }
  config {
    key: "carrier_default_wfc_ims_roaming_mode_int"
    int_value: 1
  }
  config {
    key: "carrier_ims_gba_required_bool"
    bool_value: true
  }
  config {
    key: "carrier_nr_availabilities_int_array"
    int_array {
      item: 1
    }
  }
  config {
    key: "carrier_supports_ss_over_ut_bool"
    bool_value: true
  }
  config {
    key: "carrier_ussd_method_int"
    int_value: 2
  }
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "carrier_wfc_ims_available_bool"
    bool_value: true
  }
  config {
    key: "editable_wfc_mode_bool"
    bool_value: true
  }
  config {
    key: "enabledMMS"
    bool_value: true
  }
  config {
    key: "ims.gruu_enabled_bool"
    bool_value: true
  }
  config {
    key: "ims.request_uri_type_int"
    int_value: 1
  }
  config {
    key: "imsi_key_availability_int"
    int_value: 2
  }
  config {
    key: "imsi_key_download_url_string"
    text_value: "https://preview.pwlan.ch/assets/cer/imsiencrypt.json"
  }
  config {
    key: "imsss.network_initiated_ussd_over_ims_supported_bool"
    bool_value: false
  }
  config {
    key: "imsss.ut_as_server_fqdn_string"
    text_value: "xcap.ims.mnc001.mcc228.pub.3gppnetwork.org"
  }
  config {
    key: "imsss.ut_as_server_port_int"
    int_value: 8080
  }
  config {
    key: "imsss.ut_iptype_home_int"
    int_value: 0
  }
  config {
    key: "imsss.ut_iptype_roaming_int"
    int_value: 0
  }
  config {
    key: "imsss.xcap_over_ut_supported_rats_int_array"
    int_array {
      item: 6
      item: 3
      item: 5
      item: 1
      item: 2
    }
  }
  config {
    key: "imsvoice.audio_codec_capability_payload_types_bundle"
    bundle {
      config {
        key: "imsvoice.amrnb_payload_type_int_array"
        int_array {
          item: 102
        }
      }
      config {
        key: "imsvoice.amrwb_payload_type_int_array"
        int_array {
          item: 104
        }
      }
      config {
        key: "imsvoice.dtmfnb_payload_type_int_array"
        int_array {
          item: 97
        }
      }
      config {
        key: "imsvoice.dtmfwb_payload_type_int_array"
        int_array {
          item: 96
        }
      }
      config {
        key: "imsvoice.evs_payload_type_int_array"
        int_array {
          item: 106
        }
      }
    }
  }
  config {
    key: "imsvoice.conference_factory_uri_string"
    text_value: "mmtel@conf-factory.ims.mnc001.mcc228.3gppnetwork.org"
  }
  config {
    key: "imsvoice.evs_payload_description_bundle"
    bundle {
      config {
        key: "106"
        bundle {
          config {
            key: "imsvoice.evs_codec_attribute_bitrate_int_array"
            int_array {
              item: 3
              item: 6
            }
          }
          config {
            key: "imsvoice.evs_codec_attribute_ch_aw_recv_int"
            int_value: 255
          }
          config {
            key: "imsvoice.evs_codec_attribute_hf_only_int"
            int_value: 1
          }
        }
      }
    }
  }
  config {
    key: "imsvoice.minimum_session_expires_timer_sec_int"
    int_value: 600
  }
  config {
    key: "imsvoice.ringback_timer_millis_int"
    int_value: 180000
  }
  config {
    key: "imsvoice.ringing_timer_millis_int"
    int_value: 180000
  }
  config {
    key: "iwlan.child_sa_rekey_hard_timer_sec_int"
    int_value: 14500
  }
  config {
    key: "iwlan.child_sa_rekey_soft_timer_sec_int"
    int_value: 14400
  }
  config {
    key: "iwlan.diffie_hellman_groups_int_array"
    int_array {
      item: 15
      item: 2
    }
  }
  config {
    key: "iwlan.epdg_address_priority_int_array"
    int_array {
      item: 0
    }
  }
  config {
    key: "iwlan.epdg_static_address_string"
    text_value: "epdg.epc.mnc001.mcc228.pub.3gppnetwork.org"
  }
  config {
    key: "iwlan.ike_rekey_hard_timer_in_sec"
    int_value: 82900
  }
  config {
    key: "iwlan.ike_rekey_soft_timer_sec_int"
    int_value: 82800
  }
  config {
    key: "iwlan.ike_remote_id_type_int"
    int_value: 11
  }
  config {
    key: "qns.condition_rove_in_idle_cell_pref_home_guarding_none_string_array"
    text_array {
      item: "Condition:IWLAN_GOOD,EUTRAN_BAD"
      item: "Condition:IWLAN_GOOD,UTRAN_BAD"
      item: "Condition:IWLAN_GOOD,GERAN_BAD"
    }
  }
  config {
    key: "qns.condition_rove_in_idle_cell_pref_home_guarding_wifi_string_array"
    text_array {
      item: "Condition:IWLAN_GOOD,EUTRAN_BAD"
      item: "Condition:IWLAN_GOOD,UTRAN_BAD"
      item: "Condition:IWLAN_GOOD,GERAN_BAD"
    }
  }
  config {
    key: "qns.condition_rove_in_idle_wifi_pref_home_guarding_none_string_array"
    text_array {
      item: "Condition:IWLAN_GOOD"
    }
  }
  config {
    key: "qns.condition_rove_in_idle_wifi_pref_home_guarding_wifi_string_array"
    text_array {
      item: "Condition:IWLAN_GOOD"
    }
  }
  config {
    key: "qns.condition_rove_in_voice_cell_pref_home_guarding_none_string_array"
    text_array {
      item: "Condition:IWLAN_GOOD,EUTRAN_BAD"
    }
  }
  config {
    key: "qns.condition_rove_in_voice_cell_pref_home_guarding_wifi_string_array"
    text_array {
      item: "Condition:IWLAN_GOOD,EUTRAN_BAD"
    }
  }
  config {
    key: "qns.condition_rove_in_voice_wifi_pref_home_guarding_none_string_array"
    text_array {
      item: "Condition:IWLAN_GOOD"
    }
  }
  config {
    key: "qns.condition_rove_in_voice_wifi_pref_home_guarding_wifi_string_array"
    text_array {
      item: "Condition:IWLAN_GOOD"
    }
  }
  config {
    key: "qns.condition_rove_out_idle_cell_pref_home_guarding_cell_string_array"
    text_array {
      item: "Condition:IWLAN_BAD,EUTRAN_GOOD"
      item: "Condition:IWLAN_BAD,UTRAN_GOOD"
      item: "Condition:IWLAN_BAD,GERAN_GOOD"
    }
  }
  config {
    key: "qns.condition_rove_out_idle_cell_pref_home_guarding_none_string_array"
    text_array {
      item: "Condition:EUTRAN_GOOD"
      item: "Condition:UTRAN_GOOD"
      item: "Condition:GERAN_GOOD"
    }
  }
  config {
    key: "qns.condition_rove_out_idle_wifi_pref_home_guarding_cell_string_array"
    text_array {
      item: "Condition:IWLAN_BAD"
    }
  }
  config {
    key: "qns.condition_rove_out_idle_wifi_pref_home_guarding_none_string_array"
    text_array {
      item: "Condition:IWLAN_BAD"
    }
  }
  config {
    key: "qns.condition_rove_out_voice_cell_pref_home_guarding_cell_string_array"
    text_array {
      item: "Condition:IWLAN_BAD,EUTRAN_GOOD"
    }
  }
  config {
    key: "qns.condition_rove_out_voice_cell_pref_home_guarding_none_string_array"
    text_array {
      item: "Condition:EUTRAN_GOOD"
    }
  }
  config {
    key: "qns.condition_rove_out_voice_wifi_pref_home_guarding_cell_string_array"
    text_array {
      item: "Condition:IWLAN_BAD"
    }
  }
  config {
    key: "qns.condition_rove_out_voice_wifi_pref_home_guarding_none_string_array"
    text_array {
      item: "Condition:IWLAN_BAD"
    }
  }
  config {
    key: "qns.idle_eutran_rsrp_int_array"
    int_array {
      item: -105
      item: -122
    }
  }
  config {
    key: "qns.idle_geran_rssi_int_array"
    int_array {
      item: -92
      item: -100
    }
  }
  config {
    key: "qns.idle_utran_rscp_int_array"
    int_array {
      item: -105
      item: -114
    }
  }
  config {
    key: "qns.idle_wifi_rssi_int_array"
    int_array {
      item: -60
      item: -78
    }
  }
  config {
    key: "qns.ims_wlan_hysteresis_timer_ms_int_array"
    int_array {
      item: 12000
      item: 12000
      item: 12000
    }
  }
  config {
    key: "qns.ims_wwan_hysteresis_timer_ms_int_array"
    int_array {
      item: 12000
      item: 12000
      item: 12000
    }
  }
  config {
    key: "qns.rove_in_threshold_gap_with_guard_timer_string_array"
    text_array {
      item: "eutran:rsrp:-2"
      item: "utran:rscp:-2"
      item: "geran:rssi:-2"
    }
  }
  config {
    key: "qns.voice_eutran_rsrp_int_array"
    int_array {
      item: -105
      item: -122
    }
  }
  config {
    key: "qns.voice_wifi_rssi_int_array"
    int_array {
      item: -55
      item: -75
    }
  }
  config {
    key: "show_4g_for_lte_data_icon_bool"
    bool_value: true
  }
  config {
    key: "vendor.ims.carrier_config_use_aosp_ims_config_bool"
    bool_value: true
  }
  config {
    key: "wfc_spn_format_idx_int"
    int_value: 1
  }
  config {
    key: "wifi.carrier_profiles_version_int"
    int_value: 1
  }
  config {
    key: "wifi.network_profiles_string_array"
    text_array {
      item: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><WifiNetwork><SSID>Swisscom_Auto_Login</SSID><Credential><SIM><EAPType>23</EAPType></SIM></Credential></WifiNetwork>"
    }
  }
}
last_updated {
  seconds: 1703668392
}
