canonical_name: "truphone_us"
version: 56000000001
apns {
  apn {
    name: "Truphone"
    value: "truphone.com"
    type: DEFAULT
    type: SUPL
    type: MMS
    type: DUN
    mmsc: "http://mmsc.truphone.com:1981/mm1"
    user_editable: false
  }
  apn {
    name: "Truphone IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
  }
}
configs {
  config {
    key: "carrier_volte_available_bool"
    bool_value: false
  }
  config {
    key: "show_4g_for_lte_data_icon_bool"
    bool_value: true
  }
}
last_updated {
  seconds: 1709690429
}
