canonical_name: "unionwireless_us"
version: 56000000002
apns {
  apn {
    name: "Union Wireless Data"
    value: "smart.com"
    type: DEFAULT
    type: SUPL
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_editable: false
  }
  apn {
    name: "Union Wireless MMS"
    value: "union.mms.com"
    type: MMS
    mmsc: "http://mms.unionwireless.com/"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_editable: false
  }
  apn {
    name: "HOS"
    value: "hos"
    type: XCAP
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_editable: false
  }
  apn {
    name: "SOS"
    value: "sos"
    type: EMERGENCY
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_editable: false
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "carrier_supports_ss_over_ut_bool"
    bool_value: true
  }
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "hide_enhanced_4g_lte_bool"
    bool_value: true
  }
}
last_updated {
  seconds: 1709116031
}
