canonical_name: "unitedwireless_us"
version: 62000000002
apns {
  apn {
    name: "United Wireless Internet"
    value: "unitedwireless"
    type: DEFAULT
    type: MMS
    mmsc: "http://mms.unitedwireless.com"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_editable: false
  }
  apn {
    name: "United Wireless Tethering"
    value: "dun.unitedwireless"
    type: DUN
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_editable: false
  }
  apn {
    name: "United Wireless HOS"
    value: "hos"
    type: XCAP
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_editable: false
  }
  apn {
    name: "United Wireless FOTA"
    value: "ota.unitedwireless"
    type: FOTA
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_editable: false
  }
  apn {
    name: "United IMS"
    value: "IMS"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "default_vm_number_string"
    text_value: "*86"
  }
  config {
    key: "dial_string_replace_string_array"
    text_array {
      item: "*86:+1MDN"
    }
  }
  config {
    key: "hide_enhanced_4g_lte_bool"
    bool_value: true
  }
}
last_updated {
  seconds: 1724912516
}
