canonical_name: "airbus_fr"
version: 60000000001
apns {
  apn {
    name: "aircraft"
    value: "aircraft"
    type: DEFAULT
    protocol: IPV4V6
    roaming_protocol: IPV4V6
  }
  apn {
    name: "industrial"
    value: "nin"
    type: DEFAULT
    authtype: 1
    protocol: IPV4V6
    roaming_protocol: IPV4V6
  }
  apn {
    name: "internet"
    value: "internet"
    type: DEFAULT
    protocol: IPV4V6
    roaming_protocol: IPV4V6
  }
  apn {
    name: "iot"
    value: "iot"
    type: DEFAULT
    protocol: IPV4V6
    roaming_protocol: IPV4V6
  }
  apn {
    name: "manuf"
    value: "manuf"
    type: DEFAULT
    protocol: IPV4V6
    roaming_protocol: IPV4V6
  }
  apn {
    name: "mcs"
    value: "mcs"
    type: DEFAULT
    protocol: IPV4V6
    roaming_protocol: IPV4V6
  }
}
configs {
  config {
    key: "cellular_usage_setting_int"
    int_value: 2
  }
  config {
    key: "show_4g_for_lte_data_icon_bool"
    bool_value: true
  }
}
last_updated {
  seconds: 1715771948
}
