canonical_name: "bouygues_fr"
version: 56000000011
apns {
  apn {
    name: "Bouygues Telecom"
    value: "mmsbouygtel.com"
    type: DEFAULT
    type: SUPL
    type: MMS
    authtype: 1
    mmsc: "http://mms.bouyguestelecom.fr/mms/wapenc"
    protocol: IPV6
  }
  apn {
    name: "Bouygues XCAP"
    value: "mmsbouygtel.com"
    type: XCAP
    authtype: 1
    protocol: IPV6
    user_visible: false
  }
  apn {
    name: "Bouygues Telecom IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|18|20"
    protocol: IPV4V6
    user_visible: false
    lingering_network_type_bitmask: "1|2|3|8|9|10|13|14|15|18|20"
  }
}
configs {
  config {
    key: "bsf.bsf_server_port_int"
    int_value: 4001
  }
  config {
    key: "carrier_certificate_string_array"
    text_array {
      item: "A0058F6467628EA2031C4C9D8519ABECB2671F6A1752B15A89369CDCB8D2952B"
    }
  }
  config {
    key: "carrier_default_wfc_ims_enabled_bool"
    bool_value: true
  }
  config {
    key: "carrier_default_wfc_ims_mode_int"
    int_value: 1
  }
  config {
    key: "carrier_nr_availabilities_int_array"
    int_array {
      item: 1
    }
  }
  config {
    key: "carrier_supports_ss_over_ut_bool"
    bool_value: true
  }
  config {
    key: "carrier_ussd_method_int"
    int_value: 2
  }
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "carrier_wfc_ims_available_bool"
    bool_value: true
  }
  config {
    key: "editable_wfc_mode_bool"
    bool_value: false
  }
  config {
    key: "hide_enhanced_4g_lte_bool"
    bool_value: true
  }
  config {
    key: "ims.ims_user_agent_string"
    text_value: "#MANUFACTURE# #MODEL# Android #AV# #BUILD# EU00745"
  }
  config {
    key: "ims.ipv4_sip_mtu_size_cellular_int"
    int_value: 1354
  }
  config {
    key: "ims.ipv6_sip_mtu_size_cellular_int"
    int_value: 1354
  }
  config {
    key: "ims.request_uri_type_int"
    int_value: 1
  }
  config {
    key: "ims_conference_size_limit_int"
    int_value: 2
  }
  config {
    key: "imsss.network_initiated_ussd_over_ims_supported_bool"
    bool_value: false
  }
  config {
    key: "imsss.ut_as_server_port_int"
    int_value: 4000
  }
  config {
    key: "imsss.ut_iptype_home_int"
    int_value: 1
  }
  config {
    key: "imsss.ut_iptype_roaming_int"
    int_value: 1
  }
  config {
    key: "imsss.ut_requires_ims_registration_bool"
    bool_value: true
  }
  config {
    key: "imsss.ut_supported_when_roaming_bool"
    bool_value: false
  }
  config {
    key: "imsss.xcap_over_ut_supported_rats_int_array"
    int_array {
      item: 6
      item: 3
      item: 1
      item: 2
    }
  }
  config {
    key: "imsvoice.audio_codec_capability_payload_types_bundle"
    bundle {
      config {
        key: "imsvoice.amrnb_payload_type_int_array"
        int_array {
          item: 102
        }
      }
      config {
        key: "imsvoice.amrwb_payload_type_int_array"
        int_array {
          item: 104
        }
      }
      config {
        key: "imsvoice.dtmfnb_payload_type_int_array"
        int_array {
          item: 97
        }
      }
      config {
        key: "imsvoice.dtmfwb_payload_type_int_array"
        int_array {
          item: 96
        }
      }
    }
  }
  config {
    key: "imsvoice.conference_subscribe_type_int"
    int_value: 0
  }
  config {
    key: "imsvoice.minimum_session_expires_timer_sec_int"
    int_value: 900
  }
  config {
    key: "imsvoice.ringback_timer_millis_int"
    int_value: 40000
  }
  config {
    key: "imsvoice.ringing_timer_millis_int"
    int_value: 40000
  }
  config {
    key: "imsvoice.session_refresher_type_int"
    int_value: 2
  }
  config {
    key: "is_ims_conference_size_enforced_bool"
    bool_value: true
  }
  config {
    key: "iwlan.child_sa_rekey_hard_timer_sec_int"
    int_value: 7400
  }
  config {
    key: "iwlan.child_sa_rekey_soft_timer_sec_int"
    int_value: 7300
  }
  config {
    key: "iwlan.diffie_hellman_groups_int_array"
    int_array {
      item: 14
    }
  }
  config {
    key: "iwlan.ike_rekey_hard_timer_in_sec"
    int_value: 14800
  }
  config {
    key: "iwlan.ike_rekey_soft_timer_sec_int"
    int_value: 14700
  }
  config {
    key: "iwlan.key_error_policy_config_string"
    text_value: "[{\"ApnName\": \"*\",\"ErrorTypes\": [{\"ErrorType\": \"IKE_PROTOCOL_ERROR_TYPE\",\"ErrorDetails\": [\"9000\", \"10000\"],\"RetryArray\": [\"0\", \"0\"],\"UnthrottlingEvents\": [\"APM_ENABLE_EVENT\", \"WIFI_DISABLE_EVENT\", \"WIFI_AP_CHANGED_EVENT\", \"WIFI_CALLING_DISABLE_EVENT\"]}, {\"ErrorType\": \"IKE_PROTOCOL_ERROR_TYPE\",\"ErrorDetails\": [\"10500\"],\"RetryArray\": [\"3600\", \"-1\"],\"UnthrottlingEvents\": [\"APM_ENABLE_EVENT\", \"WIFI_DISABLE_EVENT\", \"WIFI_AP_CHANGED_EVENT\", \"WIFI_CALLING_DISABLE_EVENT\"]}, {\"ErrorType\": \"IKE_PROTOCOL_ERROR_TYPE\",\"ErrorDetails\": [\"11002\", \"11003\"],\"RetryArray\": [],\"UnthrottlingEvents\": [\"APM_ENABLE_EVENT\", \"WIFI_DISABLE_EVENT\", \"WIFI_AP_CHANGED_EVENT\", \"WIFI_CALLING_DISABLE_EVENT\"]}]}]"
  }
  config {
    key: "maxImageHeight"
    int_value: 1944
  }
  config {
    key: "maxImageWidth"
    int_value: 2592
  }
  config {
    key: "maxMessageSize"
    int_value: 614400
  }
  config {
    key: "prefer_3g_visibility_bool"
    bool_value: false
  }
  config {
    key: "qns.idle_eutran_rsrp_int_array"
    int_array {
      item: -110
      item: -120
    }
  }
  config {
    key: "qns.idle_geran_rssi_int_array"
    int_array {
      item: -60
      item: -70
    }
  }
  config {
    key: "qns.idle_utran_rscp_int_array"
    int_array {
      item: -90
      item: -100
    }
  }
  config {
    key: "qns.idle_wifi_rssi_int_array"
    int_array {
      item: -70
      item: -79
    }
  }
  config {
    key: "qns.ims_cellular_allowed_rat_string_array"
    text_array {
      item: "LTE"
      item: "NR"
      item: "3G"
      item: "2G"
    }
  }
  config {
    key: "qns.mms_rat_preference_int"
    int_value: 0
  }
  config {
    key: "qns.mms_transport_type_int"
    int_value: 0
  }
  config {
    key: "qns.voice_eutran_rsrp_int_array"
    int_array {
      item: -110
      item: -120
    }
  }
  config {
    key: "qns.voice_geran_rssi_int_array"
    int_array {
      item: -60
      item: -70
    }
  }
  config {
    key: "qns.voice_utran_rscp_int_array"
    int_array {
      item: -90
      item: -100
    }
  }
  config {
    key: "qns.voice_wifi_rssi_int_array"
    int_array {
      item: -70
      item: -79
    }
  }
  config {
    key: "qns.xcap_transport_type_int"
    int_value: 0
  }
  config {
    key: "show_4g_for_lte_data_icon_bool"
    bool_value: true
  }
  config {
    key: "supportHttpCharsetHeader"
    bool_value: false
  }
}
last_updated {
  seconds: 1707299267
}
