canonical_name: "docomo_jp"
version: 56000000017
apns {
  apn {
    name: "sp\343\203\242\343\203\274\343\203\211"
    value: "spmode.ne.jp"
    type: DEFAULT
    type: SUPL
    protocol: IPV4V6
    user_editable: false
  }
  apn {
    name: "lte_ims"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
    user_editable: false
  }
  apn {
    name: "mopera U"
    value: "mopera.net"
    type: DEFAULT
    type: SUPL
  }
}
configs {
  config {
    key: "5g_icon_configuration_string"
    text_value: "connected_mmwave:5G,connected:5G,not_restricted_rrc_idle:5G"
  }
  config {
    key: "5g_icon_display_grace_period_string"
    text_value: "connected_mmwave,legacy,31;connected,legacy,31;connected_mmwave,not_restricted_rrc_con,31;connected,not_restricted_rrc_con,31;not_restricted_rrc_idle,not_restricted_rrc_con,15"
  }
  config {
    key: "5g_nr_ssrsrp_thresholds_int_array"
    int_array {
      item: -128
      item: -118
      item: -108
      item: -98
    }
  }
  config {
    key: "allow_emergency_numbers_in_call_log_bool"
    bool_value: true
  }
  config {
    key: "allow_hold_call_during_emergency_bool"
    bool_value: false
  }
  config {
    key: "allow_metered_network_for_cert_download_bool"
    bool_value: true
  }
  config {
    key: "always_show_emergency_alert_onoff_bool"
    bool_value: true
  }
  config {
    key: "call_waiting_service_class_int"
    int_value: 0
  }
  config {
    key: "carrier_additional_cbs_channels_strings"
    text_array {
      item: "0xA001-0xA002:type=other, emergency=true"
      item: "0xA004-0xA3FF:type=other, emergency=true"
    }
  }
  config {
    key: "carrier_cross_sim_ims_available_bool"
    bool_value: false
  }
  config {
    key: "carrier_force_disable_etws_cmas_test_bool"
    bool_value: false
  }
  config {
    key: "carrier_nr_availabilities_int_array"
    int_array {
      item: 1
    }
  }
  config {
    key: "carrier_ussd_method_int"
    int_value: 1
  }
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "default_vm_number_string"
    text_value: "1417"
  }
  config {
    key: "display_hd_plus_icon_bool"
    bool_value: true
  }
  config {
    key: "enabledMMS"
    bool_value: false
  }
  config {
    key: "gps.es_extension_sec"
    text_value: "300"
  }
  config {
    key: "hide_enhanced_4g_lte_bool"
    bool_value: true
  }
  config {
    key: "hide_ims_apn_bool"
    bool_value: true
  }
  config {
    key: "hide_lte_plus_data_icon_bool"
    bool_value: false
  }
  config {
    key: "ignore_data_enabled_changed_for_video_calls"
    bool_value: true
  }
  config {
    key: "ims.request_uri_type_int"
    int_value: 1
  }
  config {
    key: "ims_reasoninfo_mapping_string_array"
    text_array {
      item: "332||510"
      item: "510|Call completed elsewhere|1014"
    }
  }
  config {
    key: "imsemergency.emergency_over_ims_supported_rats_int_array"
    int_array {
      item: 3
    }
  }
  config {
    key: "imsi_key_availability_int"
    int_value: 2
  }
  config {
    key: "imsi_key_download_url_string"
    text_value: "https://cert.m-zone.jp/getPublicKeyForAndroid"
  }
  config {
    key: "imsss.ut_server_based_services_int_array"
    int_array {
      item: 20
      item: 12
      item: 18
      item: 14
      item: 19
      item: 21
      item: 15
      item: 16
      item: 17
      item: 13
      item: 1
      item: 3
      item: 4
      item: 7
      item: 6
      item: 5
      item: 2
      item: 0
      item: 8
      item: 9
      item: 11
    }
  }
  config {
    key: "imsss.ut_terminal_based_services_int_array"
    int_array {
      item: 10
    }
  }
  config {
    key: "imsss.xcap_over_ut_supported_rats_int_array"
    int_array {
    }
  }
  config {
    key: "imsvoice.audio_rtp_inactivity_timer_millis_int"
    int_value: 12000
  }
  config {
    key: "imsvoice.conference_subscribe_type_int"
    int_value: 0
  }
  config {
    key: "imsvoice.session_privacy_type_int"
    int_value: 2
  }
  config {
    key: "imsvoice.session_timer_supported_bool"
    bool_value: false
  }
  config {
    key: "lte_endc_using_user_data_for_rrc_detection_bool"
    bool_value: true
  }
  config {
    key: "min_udp_port_4500_nat_timeout_sec_int"
    int_value: 120
  }
  config {
    key: "nr_timers_reset_if_non_endc_and_rrc_idle_bool"
    bool_value: true
  }
  config {
    key: "prefer_3g_visibility_bool"
    bool_value: false
  }
  config {
    key: "preferred_ike_protocol_int"
    int_value: 40
  }
  config {
    key: "read_only_apn_types_string_array"
    text_array {
      item: "dun"
      item: "ims"
    }
  }
  config {
    key: "show_4g_for_lte_data_icon_bool"
    bool_value: true
  }
  config {
    key: "show_blocking_pay_phone_option_bool"
    bool_value: true
  }
  config {
    key: "support_ims_conference_call_bool"
    bool_value: false
  }
  config {
    key: "support_ims_conference_event_package_bool"
    bool_value: false
  }
  config {
    key: "tty_supported_bool"
    bool_value: false
  }
  config {
    key: "use_call_forwarding_ussd_bool"
    bool_value: true
  }
  config {
    key: "use_call_waiting_ussd_bool"
    bool_value: true
  }
  config {
    key: "use_caller_id_ussd_bool"
    bool_value: true
  }
  config {
    key: "vilte_data_is_metered_bool"
    bool_value: false
  }
  config {
    key: "volte_replacement_rat_int"
    int_value: 3
  }
  config {
    key: "wifi.carrier_profiles_version_int"
    int_value: 1
  }
  config {
    key: "wifi.network_profiles_string_array"
    text_array {
      item: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><WifiNetwork><SSID>0001docomo</SSID><Credential><SIM><EAPType>50</EAPType></SIM></Credential></WifiNetwork>"
    }
  }
}
last_updated {
  seconds: 1708635187
}
