canonical_name: "vodafone_pt"
version: 56000000012
apns {
  apn {
    name: "Vodafone Net2"
    value: ""
    type: IA
  }
  apn {
    name: "Vodafone Net2"
    value: "net2.vodafone.pt"
    type: DEFAULT
    type: MMS
    type: SUPL
    type: XCAP
    user: "vodafone"
    password: "vodafone"
    authtype: 1
    mmsc: "http://mms.vodafone.pt/servlets/mms"
    mmsc_proxy: "iproxy.vodafone.pt"
    mmsc_proxy_port: "80"
    protocol: IPV4V6
  }
  apn {
    name: "Vodafone Internet"
    value: "internet.vodafone.pt"
    type: DUN
    authtype: 0
    protocol: IPV4V6
    user_editable: false
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "carrier_nr_availabilities_int_array"
    int_array {
      item: 1
    }
  }
  config {
    key: "carrier_supports_ss_over_ut_bool"
    bool_value: true
  }
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "default_vm_number_string"
    text_value: "123"
  }
  config {
    key: "feature_access_codes_string_array"
    text_array {
      item: "231"
      item: "45"
      item: "46"
      item: "112"
      item: "121"
      item: "132"
      item: "611"
      item: "621"
      item: "155"
      item: "157"
      item: "211"
      item: "221"
      item: "321"
      item: "51"
      item: "114"
      item: "311"
    }
  }
  config {
    key: "hide_enhanced_4g_lte_bool"
    bool_value: true
  }
  config {
    key: "ims.ipsec_authentication_algorithms_int_array"
    int_array {
      item: 1
    }
  }
  config {
    key: "ims.ipsec_encryption_algorithms_int_array"
    int_array {
      item: 0
      item: 2
    }
  }
  config {
    key: "imsemergency.emergency_over_ims_supported_rats_int_array"
    int_array {
      item: 3
    }
  }
  config {
    key: "imssms.sms_over_ims_supported_rats_int_array"
    int_array {
    }
  }
  config {
    key: "imsss.network_initiated_ussd_over_ims_supported_bool"
    bool_value: false
  }
  config {
    key: "imsss.xcap_over_ut_supported_rats_int_array"
    int_array {
      item: 6
      item: 3
      item: 5
      item: 1
      item: 2
    }
  }
  config {
    key: "imsvoice.evs_payload_description_bundle"
    bundle {
      config {
        key: "127"
        bundle {
          config {
            key: "imsvoice.evs_codec_attribute_bitrate_int_array"
            int_array {
              item: 0
              item: 6
            }
          }
          config {
            key: "imsvoice.evs_codec_attribute_ch_aw_recv_int"
            int_value: 2
          }
        }
      }
    }
  }
  config {
    key: "show_4g_for_lte_data_icon_bool"
    bool_value: true
  }
  config {
    key: "volte_replacement_rat_int"
    int_value: 3
  }
}
last_updated {
  seconds: 1706100379
}
