canonical_name: "windtre_it"
version: 56000000014
apns {
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|18|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
    lingering_network_type_bitmask: "1|2|3|8|9|10|13|14|15|18|20"
  }
  apn {
    name: "Internet"
    value: "internet.it"
    type: DEFAULT
    type: SUPL
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_editable: false
  }
  apn {
    name: "XCAP"
    value: "xcap"
    type: XCAP
    user_visible: false
  }
  apn {
    name: "MMS"
    value: "mms.it"
    type: MMS
    mmsc: "http://mms.windtre.it"
    mmsc_proxy: "mmsproxy.windtre.it"
    mmsc_proxy_port: "8080"
  }
}
configs {
  config {
    key: "call_barring_visibility_bool"
    bool_value: true
  }
  config {
    key: "carrier_certificate_string_array"
    text_array {
      item: "7A6D2E2EDEA23A93FA95A447535675CFB543919698196FB720B1520658D25DC7"
      item: "A69A419CFB5FB8344D2AEDCED6BC2A7FCB74F85161BCA9265C54E95E478839C3"
      item: "998DA7CED0E1A3A14E51FAEF1F8608A494BDA791B6609A1C5E599F9B64F01674"
    }
  }
  config {
    key: "carrier_default_wfc_ims_enabled_bool"
    bool_value: true
  }
  config {
    key: "carrier_default_wfc_ims_mode_int"
    int_value: 1
  }
  config {
    key: "carrier_nr_availabilities_int_array"
    int_array {
      item: 1
    }
  }
  config {
    key: "carrier_supports_ss_over_ut_bool"
    bool_value: true
  }
  config {
    key: "carrier_ussd_method_int"
    int_value: 2
  }
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "carrier_wfc_ims_available_bool"
    bool_value: true
  }
  config {
    key: "default_vm_number_string"
    text_value: "4200"
  }
  config {
    key: "hide_enhanced_4g_lte_bool"
    bool_value: true
  }
  config {
    key: "hide_ims_apn_bool"
    bool_value: true
  }
  config {
    key: "ims.ipv4_sip_mtu_size_cellular_int"
    int_value: 1450
  }
  config {
    key: "ims.ipv6_sip_mtu_size_cellular_int"
    int_value: 1450
  }
  config {
    key: "ims.registration_retry_max_timer_millis_int"
    int_value: 300000
  }
  config {
    key: "ims.request_uri_type_int"
    int_value: 1
  }
  config {
    key: "imsemergency.emergency_over_ims_supported_rats_int_array"
    int_array {
      item: 3
    }
  }
  config {
    key: "imssms.sms_over_ims_supported_rats_int_array"
    int_array {
    }
  }
  config {
    key: "imsss.network_initiated_ussd_over_ims_supported_bool"
    bool_value: false
  }
  config {
    key: "imsss.ut_iptype_home_int"
    int_value: 0
  }
  config {
    key: "imsss.ut_requires_ims_registration_bool"
    bool_value: true
  }
  config {
    key: "imsss.ut_supported_when_roaming_bool"
    bool_value: false
  }
  config {
    key: "imsss.xcap_over_ut_supported_rats_int_array"
    int_array {
      item: 5
      item: 6
      item: 3
      item: 1
      item: 2
    }
  }
  config {
    key: "imsvoice.audio_rtcp_inactivity_timer_millis_int"
    int_value: 10000
  }
  config {
    key: "imsvoice.audio_rtp_inactivity_timer_millis_int"
    int_value: 10000
  }
  config {
    key: "imsvoice.conference_subscribe_type_int"
    int_value: 0
  }
  config {
    key: "imsvoice.evs_payload_description_bundle"
    bundle {
      config {
        key: "127"
        bundle {
          config {
            key: "imsvoice.evs_codec_attribute_bitrate_int_array"
            int_array {
              item: 0
              item: 6
            }
          }
          config {
            key: "imsvoice.evs_codec_attribute_ch_aw_recv_int"
            int_value: -1
          }
        }
      }
    }
  }
  config {
    key: "imsvoice.prack_supported_for_18x_bool"
    bool_value: true
  }
  config {
    key: "imsvoice.ringback_timer_millis_int"
    int_value: 67000
  }
  config {
    key: "imsvoice.ringing_timer_millis_int"
    int_value: 65000
  }
  config {
    key: "iwlan.diffie_hellman_groups_int_array"
    int_array {
      item: 14
      item: 15
      item: 16
      item: 2
      item: 5
    }
  }
  config {
    key: "iwlan.dpd_timer_sec_int"
    int_value: 600
  }
  config {
    key: "qns.idle_eutran_rsrp_int_array"
    int_array {
      item: -104
      item: -110
    }
  }
  config {
    key: "qns.idle_wifi_rssi_int_array"
    int_array {
      item: -70
      item: -80
    }
  }
  config {
    key: "qns.rtp_metrics_int_array"
    int_array {
      item: 120
      item: 40
      item: 3000
      item: 2000
    }
  }
  config {
    key: "qns.support_wfc_during_airplane_mode_bool"
    bool_value: false
  }
  config {
    key: "qns.voice_eutran_rsrp_int_array"
    int_array {
      item: -104
      item: -110
    }
  }
  config {
    key: "qns.voice_wifi_rssi_int_array"
    int_array {
      item: -70
      item: -80
    }
  }
  config {
    key: "show_4g_for_lte_data_icon_bool"
    bool_value: true
  }
  config {
    key: "smsToMmsTextThreshold"
    int_value: 10
  }
  config {
    key: "wfc_spn_format_idx_int"
    int_value: 1
  }
}
last_updated {
  seconds: 1706100379
}
