canonical_name: "yoigo_es"
version: 56000000013
apns {
  apn {
    name: "Internet"
    value: "internet"
    type: DEFAULT
    type: SUPL
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
  apn {
    name: "hos"
    value: "hos"
    type: XCAP
    user_visible: false
  }
}
configs {
  config {
    key: "carrier_nr_availabilities_int_array"
    int_array {
      item: 1
    }
  }
  config {
    key: "carrier_supports_ss_over_ut_bool"
    bool_value: true
  }
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "default_vm_number_string"
    text_value: "633"
  }
  config {
    key: "enabledMMS"
    bool_value: false
  }
  config {
    key: "imsemergency.emergency_over_ims_supported_rats_int_array"
    int_array {
      item: 3
    }
  }
  config {
    key: "imsss.xcap_over_ut_supported_rats_int_array"
    int_array {
      item: 6
      item: 3
      item: 5
      item: 1
      item: 2
    }
  }
  config {
    key: "imsvoice.audio_codec_capability_payload_types_bundle"
    bundle {
      config {
        key: "imsvoice.amrnb_payload_type_int_array"
        int_array {
          item: 98
          item: 103
        }
      }
      config {
        key: "imsvoice.amrwb_payload_type_int_array"
        int_array {
          item: 100
          item: 105
        }
      }
      config {
        key: "imsvoice.dtmfnb_payload_type_int_array"
        int_array {
          item: 97
        }
      }
      config {
        key: "imsvoice.dtmfwb_payload_type_int_array"
        int_array {
          item: 96
        }
      }
    }
  }
  config {
    key: "non_roaming_operator_string_array"
    text_array {
      item: "21401"
      item: "21402"
      item: "21403"
      item: "21405"
      item: "21406"
      item: "21407"
      item: "21408"
      item: "21409"
      item: "214010"
      item: "214011"
      item: "214012"
      item: "214013"
      item: "214014"
      item: "214015"
      item: "214016"
      item: "214017"
      item: "214018"
      item: "214019"
      item: "214020"
      item: "214021"
    }
  }
  config {
    key: "show_4g_for_lte_data_icon_bool"
    bool_value: true
  }
  config {
    key: "unloggable_numbers_string_array"
    text_array {
      item: "900018018"
      item: "016"
      item: "021"
      item: "024"
      item: "028"
      item: "116000"
      item: "116111"
      item: "900202010"
    }
  }
}
last_updated {
  seconds: 1709519146
}
