canonical_name: "1and1_de"
version: 56000000017
apns {
  apn {
    name: "1&1 Internet"
    value: "internet"
    type: DEFAULT
    type: SUPL
    authtype: 1
    protocol: IPV4V6
    roaming_protocol: IPV4V6
  }
  apn {
    name: "1&1 DE IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|18|20"
    protocol: IPV6
    roaming_protocol: IPV4V6
    user_visible: false
  }
  apn {
    name: "xcap"
    value: "hos"
    type: XCAP
    bearer_bitmask: "14"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
  apn {
    name: "MMS"
    value: "mms"
    type: MMS
    mmsc: "http://mms.1und1-mobilfunk.de/"
    mmsc_proxy: "2a00:0fbc:2200:c999:0109:1f87:2:1"
    mmsc_proxy_port: "80"
    protocol: IPV6
    roaming_protocol: IPV6
  }
}
configs {
  config {
    key: "call_barring_visibility_bool"
    bool_value: true
  }
  config {
    key: "carrier_nr_availabilities_int_array"
    int_array {
      item: 1
    }
  }
  config {
    key: "carrier_supports_ss_over_ut_bool"
    bool_value: true
  }
  config {
    key: "carrier_ussd_method_int"
    int_value: 1
  }
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "carrier_wfc_ims_available_bool"
    bool_value: true
  }
  config {
    key: "default_vm_number_string"
    text_value: "+4915566000333"
  }
  config {
    key: "hide_ims_apn_bool"
    bool_value: true
  }
  config {
    key: "hide_lte_plus_data_icon_bool"
    bool_value: false
  }
  config {
    key: "ims.ims_user_agent_string"
    text_value: "#MANUFACTURE# #MODEL# Android #AV# #BUILD# EU02536"
  }
  config {
    key: "ims.ipv4_sip_mtu_size_cellular_int"
    int_value: 1300
  }
  config {
    key: "ims.ipv6_sip_mtu_size_cellular_int"
    int_value: 1300
  }
  config {
    key: "ims.sip_timer_j_millis_int"
    int_value: 32000
  }
  config {
    key: "ims_reasoninfo_mapping_string_array"
    text_array {
      item: "510|Call completed elsewhere|1014"
      item: "*|Call is dropped due to Wi-Fi signal is degraded|1407"
    }
  }
  config {
    key: "imsemergency.emergency_over_ims_supported_rats_int_array"
    int_array {
      item: 3
    }
  }
  config {
    key: "imsemergency.emergency_qos_precondition_supported_bool"
    bool_value: false
  }
  config {
    key: "imsemergency.emergency_registration_timer_millis_int"
    int_value: 10000
  }
  config {
    key: "imsrtt.text_qos_precondition_supported_bool"
    bool_value: false
  }
  config {
    key: "imsss.xcap_over_ut_supported_rats_int_array"
    int_array {
      item: 3
    }
  }
  config {
    key: "imsvoice.audio_codec_capability_payload_types_bundle"
    bundle {
      config {
        key: "imsvoice.amrnb_payload_type_int_array"
        int_array {
          item: 102
        }
      }
      config {
        key: "imsvoice.amrwb_payload_type_int_array"
        int_array {
          item: 104
        }
      }
      config {
        key: "imsvoice.dtmfnb_payload_type_int_array"
        int_array {
          item: 97
        }
      }
      config {
        key: "imsvoice.dtmfwb_payload_type_int_array"
        int_array {
          item: 96
        }
      }
    }
  }
  config {
    key: "imsvoice.audio_rtp_inactivity_timer_millis_int"
    int_value: 10000
  }
  config {
    key: "imsvoice.conference_factory_uri_string"
    text_value: "mmtel@conf-factory.1und1-mobilfunk.de"
  }
  config {
    key: "imsvoice.oip_source_from_header_bool"
    bool_value: true
  }
  config {
    key: "imsvoice.prack_supported_for_18x_bool"
    bool_value: true
  }
  config {
    key: "imsvoice.ringback_timer_millis_int"
    int_value: 35000
  }
  config {
    key: "imsvoice.ringing_timer_millis_int"
    int_value: 30000
  }
  config {
    key: "imsvoice.srvcc_type_int_array"
    int_array {
      item: 0
      item: 1
      item: 3
    }
  }
  config {
    key: "imsvoice.voice_qos_precondition_supported_bool"
    bool_value: false
  }
  config {
    key: "imsvt.video_qos_precondition_supported_bool"
    bool_value: false
  }
  config {
    key: "iwlan.diffie_hellman_groups_int_array"
    int_array {
      item: 14
    }
  }
  config {
    key: "iwlan.epdg_address_priority_int_array"
    int_array {
      item: 0
    }
  }
  config {
    key: "iwlan.epdg_static_address_string"
    text_value: "epdg.epc.mnc023.mcc262.pub.3gppnetwork.org"
  }
  config {
    key: "iwlan.ike_rekey_hard_timer_in_sec"
    int_value: 86500
  }
  config {
    key: "iwlan.ike_rekey_soft_timer_sec_int"
    int_value: 86400
  }
  config {
    key: "maxImageHeight"
    int_value: 1944
  }
  config {
    key: "maxImageWidth"
    int_value: 2592
  }
  config {
    key: "maxMessageSize"
    int_value: 614400
  }
  config {
    key: "non_roaming_operator_string_array"
    text_array {
      item: "26203"
      item: "26207"
    }
  }
  config {
    key: "prefer_2g_bool"
    bool_value: true
  }
  config {
    key: "qns.condition_rove_in_idle_wifi_pref_home_string_array"
    text_array {
      item: "Condition:WIFI_GOOD"
    }
  }
  config {
    key: "qns.condition_rove_in_idle_wifi_pref_roam_string_array"
    text_array {
      item: "Condition:WIFI_GOOD"
    }
  }
  config {
    key: "qns.condition_rove_out_idle_wifi_pref_home_string_array"
    text_array {
      item: "Condition:WIFI_BAD"
    }
  }
  config {
    key: "qns.condition_rove_out_idle_wifi_pref_roam_string_array"
    text_array {
      item: "Condition:WIFI_BAD"
    }
  }
  config {
    key: "qns.override_cell_pref_to_ims_pref_home"
    bool_value: true
  }
  config {
    key: "qns.rtp_metrics_int_array"
    int_array {
      item: 120
      item: 40
      item: 3000
      item: 2000
    }
  }
  config {
    key: "qns.xcap_transport_type_int"
    int_value: 0
  }
  config {
    key: "use_only_dialed_sim_ecc_list_bool"
    bool_value: true
  }
  config {
    key: "wfc_spn_format_idx_int"
    int_value: 9
  }
}
last_updated {
  seconds: 1708635164
}
