canonical_name: "a1_bg"
version: 56000000001
apns {
  apn {
    name: "Mtel Internet"
    value: "wap-gprs.mtel.bg"
    type: DEFAULT
    type: SUPL
  }
  apn {
    name: "MTel MMS"
    value: "mms-gprs.mtel.bg"
    type: MMS
    user: "mtel"
    password: "mtel"
    mmsc: "http://mmsc/"
    mmsc_proxy: "10.150.0.33"
    mmsc_proxy_port: "8080"
  }
}
configs {
  config {
    key: "carrier_nr_availabilities_int_array"
    int_array {
    }
  }
}
last_updated {
  seconds: 1709690400
}
