canonical_name: "esn_gb"
version: 56000000017
apns {
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    type: XCAP
    bearer_bitmask: "14|20"
    protocol: IPV6
    roaming_protocol: IPV6
    user_visible: false
  }
}
configs {
  config {
    key: "carrier_cross_sim_ims_available_bool"
    bool_value: false
  }
  config {
    key: "carrier_default_data_roaming_enabled_bool"
    bool_value: true
  }
  config {
    key: "carrier_name_override_bool"
    bool_value: false
  }
  config {
    key: "carrier_name_string"
    text_value: ""
  }
  config {
    key: "carrier_nr_availabilities_int_array"
    int_array {
    }
  }
  config {
    key: "carrier_supports_ss_over_ut_bool"
    bool_value: true
  }
  config {
    key: "carrier_ussd_method_int"
    int_value: 2
  }
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "carrier_wfc_ims_available_bool"
    bool_value: false
  }
  config {
    key: "display_voicemail_number_as_default_call_forwarding_number"
    bool_value: true
  }
  config {
    key: "editable_enhanced_4g_lte_bool"
    bool_value: false
  }
  config {
    key: "editable_wfc_mode_bool"
    bool_value: false
  }
  config {
    key: "hide_enhanced_4g_lte_bool"
    bool_value: true
  }
  config {
    key: "hide_ims_apn_bool"
    bool_value: true
  }
  config {
    key: "hide_preferred_network_type_bool"
    bool_value: true
  }
  config {
    key: "ims.ipsec_authentication_algorithms_int_array"
    int_array {
      item: 1
    }
  }
  config {
    key: "ims.ipsec_encryption_algorithms_int_array"
    int_array {
      item: 2
    }
  }
  config {
    key: "ims.ipv4_sip_mtu_size_cellular_int"
    int_value: 1200
  }
  config {
    key: "ims.ipv6_sip_mtu_size_cellular_int"
    int_value: 1200
  }
  config {
    key: "ims.sip_timer_f_millis_int"
    int_value: 32000
  }
  config {
    key: "ims.sip_timer_j_millis_int"
    int_value: 32000
  }
  config {
    key: "imsemergency.emergency_over_ims_supported_rats_int_array"
    int_array {
      item: 3
    }
  }
  config {
    key: "imssms.sms_over_ims_supported_rats_int_array"
    int_array {
      item: 3
      item: 6
    }
  }
  config {
    key: "imsss.network_initiated_ussd_over_ims_supported_bool"
    bool_value: false
  }
  config {
    key: "imsss.ut_iptype_home_int"
    int_value: 1
  }
  config {
    key: "imsss.ut_iptype_roaming_int"
    int_value: 1
  }
  config {
    key: "imsss.ut_requires_ims_registration_bool"
    bool_value: true
  }
  config {
    key: "imsss.xcap_over_ut_supported_rats_int_array"
    int_array {
      item: 6
      item: 3
    }
  }
  config {
    key: "imsvoice.audio_codec_capability_payload_types_bundle"
    bundle {
      config {
        key: "imsvoice.amrnb_payload_type_int_array"
        int_array {
          item: 102
        }
      }
      config {
        key: "imsvoice.amrwb_payload_type_int_array"
        int_array {
          item: 104
        }
      }
      config {
        key: "imsvoice.dtmfnb_payload_type_int_array"
        int_array {
          item: 97
        }
      }
      config {
        key: "imsvoice.dtmfwb_payload_type_int_array"
        int_array {
          item: 96
        }
      }
      config {
        key: "imsvoice.evs_payload_type_int_array"
        int_array {
          item: 127
        }
      }
    }
  }
  config {
    key: "imsvoice.conference_subscribe_type_int"
    int_value: 0
  }
  config {
    key: "imsvoice.evs_payload_description_bundle"
    bundle {
      config {
        key: "127"
        bundle {
          config {
            key: "imsvoice.evs_codec_attribute_bitrate_int_array"
            int_array {
              item: 0
              item: 6
            }
          }
          config {
            key: "imsvoice.evs_codec_attribute_ch_aw_recv_int"
            int_value: 2
          }
        }
      }
    }
  }
  config {
    key: "imsvoice.minimum_session_expires_timer_sec_int"
    int_value: 600
  }
  config {
    key: "imsvoice.ringback_timer_millis_int"
    int_value: 130000
  }
  config {
    key: "imsvoice.ringing_timer_millis_int"
    int_value: 60000
  }
  config {
    key: "imsvoice.session_expires_timer_sec_int"
    int_value: 2000
  }
  config {
    key: "iwlan.ike_rekey_hard_timer_in_sec"
    int_value: 1300
  }
  config {
    key: "iwlan.ike_rekey_soft_timer_sec_int"
    int_value: 1200
  }
  config {
    key: "iwlan.key_error_policy_config_string"
    text_value: "[{\"ApnName\": \"*\",\"ErrorTypes\": [{\"ErrorType\": \"IKE_PROTOCOL_ERROR_TYPE\",\"ErrorDetails\": [\"24\"],\"RetryArray\": [\"10\", \"30\", \"60\", \"120\", \"300\", \"-1\"],\"UnthrottlingEvents\": [\"APM_ENABLE_EVENT\", \"WIFI_DISABLE_EVENT\", \"WIFI_AP_CHANGED_EVENT\", \"WIFI_CALLING_DISABLE_EVENT\"]}]}]"
  }
  config {
    key: "iwlan_handover_policy_string_array"
    text_array {
      item: "source=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN|UNKNOWN, target=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN, type=disallowed, capabilities=MMS|XCAP|CBS"
      item: "source=GERAN|UTRAN|EUTRAN|NGRAN|UNKNOWN, target=IWLAN, type=disallowed, capabilities=EIMS"
      item: "source=IWLAN|UNKNOWN, target=GERAN|UTRAN, type=disallowed, capabilities=EIMS"
      item: "source=IWLAN, target=EUTRAN|NGRAN, type=allowed, capabilities=EIMS"
      item: "source=IWLAN|UNKNOWN, target=GERAN|UTRAN, type=disallowed, capabilities=IMS"
      item: "source=GERAN|UTRAN, target=IWLAN, type=disallowed, capabilities=IMS"
      item: "source=EUTRAN|NGRAN|IWLAN, target=EUTRAN|NGRAN|IWLAN, type=allowed, capabilities=IMS"
    }
  }
  config {
    key: "non_roaming_operator_string_array"
    text_array {
      item: "23430"
      item: "23431"
      item: "23432"
      item: "23433"
      item: "23434"
      item: "23486"
    }
  }
  config {
    key: "prefer_2g_bool"
    bool_value: false
  }
  config {
    key: "preferred_ike_protocol_int"
    int_value: 40
  }
  config {
    key: "qns.mms_rat_preference_int"
    int_value: 2
  }
  config {
    key: "qns.sos_transport_type_int"
    int_value: 2
  }
  config {
    key: "qns.xcap_rat_preference_int"
    int_value: 2
  }
  config {
    key: "show_4g_for_lte_data_icon_bool"
    bool_value: true
  }
  config {
    key: "use_wfc_home_network_mode_in_roaming_network_bool"
    bool_value: true
  }
  config {
    key: "wfc_operator_error_codes_string_array"
    text_array {
      item: "REG09|0"
    }
  }
  config {
    key: "wfc_spn_format_idx_int"
    int_value: 1
  }
}
last_updated {
  seconds: 1706100353
}
