canonical_name: "free_re"
version: 56000000001
apns {
  apn {
    name: "Free Re"
    value: "free.re"
    type: DEFAULT
    type: DUN
    type: SUPL
    type: MMS
    mmsc: "http://mms.free.re"
    protocol: IPV4V6
  }
}
configs {
  config {
    key: "read_only_apn_types_string_array"
    text_array {
    }
  }
}
last_updated {
  seconds: 1706698770
}
