canonical_name: "giga_sg"
version: 56000000010
apns {
  apn {
    name: "giga"
    value: "giga"
    type: DEFAULT
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "bsf.bsf_server_fqdn_string"
    text_value: "bsf.ims.mnc005.mcc525.pub.3gppnetwork.org"
  }
  config {
    key: "bsf.bsf_server_port_int"
    int_value: 8081
  }
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "gsm_cdma_calls_can_be_hd_audio"
    bool_value: true
  }
  config {
    key: "ims.ipsec_encryption_algorithms_int_array"
    int_array {
      item: 0
    }
  }
  config {
    key: "ims.registration_retry_base_timer_millis_int"
    int_value: 120000
  }
  config {
    key: "ims.registration_retry_max_timer_millis_int"
    int_value: 7200000
  }
  config {
    key: "ims.request_uri_type_int"
    int_value: 1
  }
  config {
    key: "ims.sip_timer_c_millis_int"
    int_value: 180000
  }
  config {
    key: "ims.sip_timer_f_millis_int"
    int_value: 32000
  }
  config {
    key: "ims.sip_timer_j_millis_int"
    int_value: 32000
  }
  config {
    key: "ims.sip_timer_t4_millis_int"
    int_value: 20000
  }
  config {
    key: "imsemergency.emergency_over_ims_supported_rats_int_array"
    int_array {
      item: 3
    }
  }
  config {
    key: "imsss.network_initiated_ussd_over_ims_supported_bool"
    bool_value: false
  }
  config {
    key: "imsss.ut_as_server_fqdn_string"
    text_value: "shxcap.ims.mnc005.mcc525.pub.3gppnetwork.org"
  }
  config {
    key: "imsss.ut_as_server_port_int"
    int_value: 8080
  }
  config {
    key: "imsss.ut_iptype_home_int"
    int_value: 0
  }
  config {
    key: "imsss.ut_iptype_roaming_int"
    int_value: 0
  }
  config {
    key: "imsss.ut_supported_when_roaming_bool"
    bool_value: false
  }
  config {
    key: "imsss.xcap_over_ut_supported_rats_int_array"
    int_array {
    }
  }
  config {
    key: "imsvoice.audio_codec_capability_payload_types_bundle"
    bundle {
      config {
        key: "imsvoice.amrnb_payload_type_int_array"
        int_array {
          item: 98
          item: 103
        }
      }
      config {
        key: "imsvoice.amrwb_payload_type_int_array"
        int_array {
          item: 100
          item: 105
        }
      }
      config {
        key: "imsvoice.dtmfnb_payload_type_int_array"
        int_array {
          item: 97
        }
      }
      config {
        key: "imsvoice.dtmfwb_payload_type_int_array"
        int_array {
          item: 96
        }
      }
    }
  }
  config {
    key: "imsvoice.conference_factory_uri_string"
    text_value: "shconf@ims.mnc005.mcc525.3gppnetwork.org"
  }
  config {
    key: "imsvoice.minimum_session_expires_timer_sec_int"
    int_value: 600
  }
  config {
    key: "imsvoice.ringing_timer_millis_int"
    int_value: 45000
  }
  config {
    key: "imswfc.emergency_call_over_emergency_pdn_bool"
    bool_value: true
  }
  config {
    key: "show_4g_for_lte_data_icon_bool"
    bool_value: true
  }
}
last_updated {
  seconds: 1706100353
}
