canonical_name: "lifecell_ua"
version: 56000000001
apns {
  apn {
    name: "Lifecell Internet"
    value: "internet"
    type: DEFAULT
    type: DUN
    type: HIPRI
    type: SUPL
    type: FOTA
    type: CBS
    authtype: 1
    protocol: IPV4V6
    roaming_protocol: IPV4V6
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV6
    roaming_protocol: IPV6
    user_visible: false
  }
}
configs {
  config {
    key: "read_only_apn_types_string_array"
    text_array {
    }
  }
}
last_updated {
  seconds: 1709519128
}
