canonical_name: "mucho_ch"
version: 62000000001
apns {
  apn {
    name: "Mucho"
    value: "internet"
    type: DEFAULT
    type: SUPL
    user_editable: false
  }
}
configs {
  config {
    key: "enabledMMS"
    bool_value: false
  }
}
last_updated {
  seconds: 1724289888
}
