canonical_name: "o2prepaid_de"
version: 56000000020
apns {
  apn {
    name: "o2 DE IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|18|20"
    user_visible: false
  }
  apn {
    name: "o2 Internet"
    value: "internet"
    type: DEFAULT
    type: MMS
    type: XCAP
    mmsc: "http://10.81.0.7:8002"
    mmsc_proxy: "82.113.100.5"
    mmsc_proxy_port: "8080"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
  }
}
configs {
  config {
    key: "call_barring_visibility_bool"
    bool_value: true
  }
  config {
    key: "carrier_default_wfc_ims_roaming_enabled_bool"
    bool_value: true
  }
  config {
    key: "carrier_nr_availabilities_int_array"
    int_array {
      item: 1
    }
  }
  config {
    key: "carrier_supports_ss_over_ut_bool"
    bool_value: true
  }
  config {
    key: "carrier_ussd_method_int"
    int_value: 2
  }
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "carrier_wfc_ims_available_bool"
    bool_value: true
  }
  config {
    key: "default_vm_number_string"
    text_value: "+491793000333"
  }
  config {
    key: "hide_ims_apn_bool"
    bool_value: true
  }
  config {
    key: "hide_lte_plus_data_icon_bool"
    bool_value: false
  }
  config {
    key: "ims.ims_user_agent_string"
    text_value: "#MANUFACTURE# #MODEL# Android #AV# #BUILD# EU01454"
  }
  config {
    key: "ims.ipv4_sip_mtu_size_cellular_int"
    int_value: 1300
  }
  config {
    key: "ims.ipv6_sip_mtu_size_cellular_int"
    int_value: 1300
  }
  config {
    key: "ims.sip_timer_f_millis_int"
    int_value: 32000
  }
  config {
    key: "ims.sip_timer_j_millis_int"
    int_value: 32000
  }
  config {
    key: "ims_reasoninfo_mapping_string_array"
    text_array {
      item: "510|Call completed elsewhere|1014"
      item: "*|Call is dropped due to Wi-Fi signal is degraded|1407"
    }
  }
  config {
    key: "imsss.network_initiated_ussd_over_ims_supported_bool"
    bool_value: false
  }
  config {
    key: "imsss.ut_iptype_home_int"
    int_value: 0
  }
  config {
    key: "imsss.ut_supported_when_ps_data_off_bool"
    bool_value: false
  }
  config {
    key: "imsss.xcap_over_ut_supported_rats_int_array"
    int_array {
    }
  }
  config {
    key: "imsvoice.audio_codec_capability_payload_types_bundle"
    bundle {
      config {
        key: "imsvoice.amrnb_payload_type_int_array"
        int_array {
          item: 102
        }
      }
      config {
        key: "imsvoice.amrwb_payload_type_int_array"
        int_array {
          item: 104
        }
      }
      config {
        key: "imsvoice.dtmfnb_payload_type_int_array"
        int_array {
          item: 97
        }
      }
      config {
        key: "imsvoice.dtmfwb_payload_type_int_array"
        int_array {
          item: 96
        }
      }
      config {
        key: "imsvoice.evs_payload_type_int_array"
        int_array {
          item: 126
        }
      }
    }
  }
  config {
    key: "imsvoice.audio_rtp_inactivity_timer_millis_int"
    int_value: 10000
  }
  config {
    key: "imsvoice.conference_factory_uri_string"
    text_value: "teleconferenceuri-factory@telefonica.de"
  }
  config {
    key: "imsvoice.evs_payload_description_bundle"
    bundle {
      config {
        key: "126"
        bundle {
          config {
            key: "imsvoice.evs_codec_attribute_bitrate_int_array"
            int_array {
              item: 0
              item: 6
            }
          }
          config {
            key: "imsvoice.evs_codec_attribute_ch_aw_recv_int"
            int_value: 2
          }
          config {
            key: "imsvoice.evs_codec_attribute_dtx_bool"
            bool_value: false
          }
          config {
            key: "imsvoice.evs_codec_attribute_dtx_recv_bool"
            bool_value: false
          }
          config {
            key: "imsvoice.evs_codec_attribute_hf_only_int"
            int_value: 1
          }
        }
      }
    }
  }
  config {
    key: "imsvoice.minimum_session_expires_timer_sec_int"
    int_value: 600
  }
  config {
    key: "imsvoice.oip_source_from_header_bool"
    bool_value: true
  }
  config {
    key: "imsvoice.prack_supported_for_18x_bool"
    bool_value: true
  }
  config {
    key: "imsvoice.ringback_timer_millis_int"
    int_value: 180000
  }
  config {
    key: "imsvoice.ringing_timer_millis_int"
    int_value: 180000
  }
  config {
    key: "imsvoice.session_refresher_type_int"
    int_value: 0
  }
  config {
    key: "iwlan.add_ke_to_child_session_rekey_bool"
    bool_value: true
  }
  config {
    key: "iwlan.child_sa_rekey_hard_timer_sec_int"
    int_value: 86500
  }
  config {
    key: "iwlan.child_sa_rekey_soft_timer_sec_int"
    int_value: 86400
  }
  config {
    key: "iwlan.diffie_hellman_groups_int_array"
    int_array {
      item: 14
      item: 2
      item: 5
    }
  }
  config {
    key: "iwlan.dpd_timer_sec_int"
    int_value: 60
  }
  config {
    key: "iwlan.ike_rekey_hard_timer_in_sec"
    int_value: 86500
  }
  config {
    key: "iwlan.ike_rekey_soft_timer_sec_int"
    int_value: 86400
  }
  config {
    key: "iwlan_handover_policy_string_array"
    text_array {
      item: "source=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN|UNKNOWN, target=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN, type=disallowed, capabilities=EIMS|MMS|XCAP|CBS"
      item: "source=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN|UNKNOWN, target=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN, roaming=true, type=disallowed, capabilities=IMS"
      item: "source=IWLAN|UNKNOWN, target=GERAN|UTRAN, type=disallowed, capabilities=IMS"
      item: "source=GERAN|UTRAN, target=IWLAN, type=disallowed, capabilities=IMS"
      item: "source=EUTRAN|NGRAN|IWLAN, target=EUTRAN|NGRAN|IWLAN, type=allowed, capabilities=IMS"
    }
  }
  config {
    key: "maxImageHeight"
    int_value: 1944
  }
  config {
    key: "maxImageWidth"
    int_value: 2592
  }
  config {
    key: "maxMessageSize"
    int_value: 614400
  }
  config {
    key: "non_roaming_operator_string_array"
    text_array {
      item: "26203"
      item: "26205"
      item: "26212"
      item: "26217"
      item: "26220"
    }
  }
  config {
    key: "prefer_2g_bool"
    bool_value: true
  }
  config {
    key: "qns.rtp_metrics_int_array"
    int_array {
      item: 120
      item: 40
      item: 3000
      item: 2000
    }
  }
  config {
    key: "qns.xcap_transport_type_int"
    int_value: 0
  }
  config {
    key: "use_only_dialed_sim_ecc_list_bool"
    bool_value: true
  }
  config {
    key: "wfc_spn_format_idx_int"
    int_value: 1
  }
}
last_updated {
  seconds: 1711427670
}
