canonical_name: "smart_ph"
version: 62000000004
apns {
  apn {
    name: "SMARTLTE"
    value: "smartlte"
    type: DEFAULT
    type: SUPL
  }
  apn {
    name: "SMART INTERNET"
    value: "internet"
    type: DEFAULT
    type: SUPL
  }
  apn {
    name: "Smart GPRS"
    value: "Smart1"
    type: DEFAULT
    type: SUPL
    proxy: "10.102.61.46"
    port: "8080"
  }
  apn {
    name: "Smart MMS"
    value: "mms"
    type: MMS
    mmsc: "http://10.102.61.238:8002"
    mmsc_proxy: "10.102.61.46"
    mmsc_proxy_port: "8080"
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "carrier_nr_availabilities_int_array"
    int_array {
    }
  }
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "hide_enhanced_4g_lte_bool"
    bool_value: true
  }
  config {
    key: "imsemergency.emergency_over_ims_supported_rats_int_array"
    int_array {
      item: 3
    }
  }
  config {
    key: "imsss.ut_server_based_services_int_array"
    int_array {
    }
  }
  config {
    key: "imsss.ut_terminal_based_services_int_array"
    int_array {
      item: 0
    }
  }
  config {
    key: "imsss.xcap_over_ut_supported_rats_int_array"
    int_array {
    }
  }
  config {
    key: "imsvoice.audio_codec_capability_payload_types_bundle"
    bundle {
      config {
        key: "imsvoice.amrnb_payload_type_int_array"
        int_array {
          item: 98
          item: 103
        }
      }
      config {
        key: "imsvoice.amrwb_payload_type_int_array"
        int_array {
          item: 100
          item: 105
        }
      }
      config {
        key: "imsvoice.dtmfnb_payload_type_int_array"
        int_array {
          item: 97
        }
      }
      config {
        key: "imsvoice.dtmfwb_payload_type_int_array"
        int_array {
          item: 96
        }
      }
    }
  }
  config {
    key: "show_4g_for_lte_data_icon_bool"
    bool_value: true
  }
}
last_updated {
  seconds: 1724912460
}
