canonical_name: "tele2_ee"
version: 56000000007
apns {
  apn {
    name: "Tele2 Internet"
    value: "internet.tele2.ee"
    type: DEFAULT
    type: SUPL
    type: MMS
    mmsc: "http://mmsc.tele2.ee"
    mmsc_proxy: "193.12.40.6"
    mmsc_proxy_port: "8080"
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|18|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
  apn {
    name: "xcap"
    value: "hos"
    type: XCAP
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "bsf.bsf_server_fqdn_string"
    text_value: "bsf.ims.mnc003.mcc248.pub.3gppnetwork.org"
  }
  config {
    key: "bsf.bsf_server_port_int"
    int_value: 8081
  }
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "imsemergency.emergency_over_ims_supported_rats_int_array"
    int_array {
      item: 3
    }
  }
  config {
    key: "imsss.ut_as_server_fqdn_string"
    text_value: "xcap.ims.mnc003.mcc248.pub.3gppnetwork.org"
  }
  config {
    key: "imsss.ut_requires_ims_registration_bool"
    bool_value: true
  }
  config {
    key: "imsss.ut_server_based_services_int_array"
    int_array {
      item: 20
      item: 12
      item: 18
      item: 14
      item: 19
      item: 21
      item: 15
      item: 16
      item: 17
      item: 13
      item: 1
      item: 3
      item: 4
      item: 7
      item: 6
      item: 5
      item: 2
      item: 8
      item: 10
      item: 9
      item: 11
    }
  }
  config {
    key: "imsss.ut_terminal_based_services_int_array"
    int_array {
      item: 0
    }
  }
  config {
    key: "imsss.xcap_over_ut_supported_rats_int_array"
    int_array {
      item: 6
      item: 3
      item: 5
      item: 1
      item: 2
    }
  }
  config {
    key: "imsvoice.audio_codec_capability_payload_types_bundle"
    bundle {
      config {
        key: "imsvoice.amrnb_payload_type_int_array"
        int_array {
          item: 98
          item: 103
        }
      }
      config {
        key: "imsvoice.amrwb_payload_type_int_array"
        int_array {
          item: 100
          item: 105
        }
      }
      config {
        key: "imsvoice.dtmfnb_payload_type_int_array"
        int_array {
          item: 97
        }
      }
      config {
        key: "imsvoice.dtmfwb_payload_type_int_array"
        int_array {
          item: 96
        }
      }
    }
  }
  config {
    key: "iwlan.diffie_hellman_groups_int_array"
    int_array {
      item: 14
    }
  }
  config {
    key: "wfc_spn_format_idx_int"
    int_value: 1
  }
}
last_updated {
  seconds: 1708635164
}
