canonical_name: "yettel_bg"
version: 56000000001
apns {
  apn {
    name: "Telenor Internet"
    value: "telenorbg"
    type: DEFAULT
    type: SUPL
    authtype: 0
  }
  apn {
    name: "Telenor MMS"
    value: "mms"
    type: MMS
    user: "mms"
    authtype: 1
    mmsc: "http://mmsc"
    mmsc_proxy: "192.168.87.11"
    mmsc_proxy_port: "8004"
  }
}
configs {
  config {
    key: "carrier_nr_availabilities_int_array"
    int_array {
    }
  }
}
last_updated {
  seconds: 1709690400
}
