device:
  name: barbet
  build_id: AP2A.240805.005.S4
  platform_security_patch_level_override: 2024-09-01

platform:
  product_makefile: device/google/barbet/aosp_barbet.mk

includes:
  - common/gen5pixel.yml
