canonical_name: "docomopacific_us"
version: 62000000002
apns {
  apn {
    name: "Docomo Pacific"
    value: "internet"
    type: DEFAULT
    type: SUPL
    type: DUN
    bearer_bitmask: "14"
    user_editable: false
  }
  apn {
    name: "DPAC IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14"
    user_visible: false
  }
  apn {
    name: "DPAC XCAP"
    value: "xcap"
    type: XCAP
    user_visible: false
  }
}
configs {
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "imsvoice.evs_payload_description_bundle"
    bundle {
      config {
        key: "127"
        bundle {
          config {
            key: "imsvoice.evs_codec_attribute_bitrate_int_array"
            int_array {
              item: 4
              item: 4
            }
          }
          config {
            key: "imsvoice.evs_codec_attribute_ch_aw_recv_int"
            int_value: 2
          }
        }
      }
    }
  }
}
last_updated {
  seconds: 1725936038
}
