canonical_name: "h3_ie"
version: 56000000014
apns {
  apn {
    name: "3"
    value: "3ireland.ie"
    type: DEFAULT
    type: MMS
    type: SUPL
    mmsc: "http://mms.um.3ireland.ie:10021/mmsc"
    mmsc_proxy: "mms.3ireland.ie"
    mmsc_proxy_port: "8799"
  }
  apn {
    name: "ims"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|18|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "bsf.bsf_server_fqdn_string"
    text_value: "bsf.three.ie"
  }
  config {
    key: "bsf.bsf_server_port_int"
    int_value: 443
  }
  config {
    key: "bsf.bsf_transport_type_int"
    int_value: 3
  }
  config {
    key: "carrier_default_wfc_ims_enabled_bool"
    bool_value: true
  }
  config {
    key: "carrier_default_wfc_ims_mode_int"
    int_value: 1
  }
  config {
    key: "carrier_nr_availabilities_int_array"
    int_array {
      item: 1
    }
  }
  config {
    key: "carrier_supports_ss_over_ut_bool"
    bool_value: false
  }
  config {
    key: "carrier_volte_available_bool"
    bool_value: false
  }
  config {
    key: "carrier_wfc_ims_available_bool"
    bool_value: false
  }
  config {
    key: "default_vm_number_string"
    text_value: "171"
  }
  config {
    key: "ims.registration_expiry_timer_sec_int"
    int_value: 36000
  }
  config {
    key: "imsemergency.emergency_over_ims_supported_rats_int_array"
    int_array {
      item: 3
    }
  }
  config {
    key: "imsss.ut_as_server_fqdn_string"
    text_value: "xcap.three.ie"
  }
  config {
    key: "imsss.ut_as_server_port_int"
    int_value: 443
  }
  config {
    key: "imsss.ut_iptype_roaming_int"
    int_value: 0
  }
  config {
    key: "imsss.ut_requires_ims_registration_bool"
    bool_value: true
  }
  config {
    key: "imsss.ut_transport_type_int"
    int_value: 3
  }
  config {
    key: "imsss.xcap_over_ut_supported_rats_int_array"
    int_array {
      item: 6
      item: 3
    }
  }
  config {
    key: "imsvoice.evs_payload_description_bundle"
    bundle {
      config {
        key: "127"
        bundle {
          config {
            key: "imsvoice.evs_codec_attribute_bitrate_int_array"
            int_array {
              item: 3
              item: 6
            }
          }
          config {
            key: "imsvoice.evs_codec_attribute_ch_aw_recv_int"
            int_value: 255
          }
        }
      }
    }
  }
  config {
    key: "imsvoice.minimum_session_expires_timer_sec_int"
    int_value: 600
  }
  config {
    key: "imsvoice.oip_source_from_header_bool"
    bool_value: true
  }
  config {
    key: "iwlan.child_sa_rekey_hard_timer_sec_int"
    int_value: 43200
  }
  config {
    key: "iwlan.child_sa_rekey_soft_timer_sec_int"
    int_value: 43100
  }
  config {
    key: "iwlan.diffie_hellman_groups_int_array"
    int_array {
      item: 14
    }
  }
  config {
    key: "iwlan.epdg_address_priority_int_array"
    int_array {
      item: 0
    }
  }
  config {
    key: "iwlan.epdg_static_address_string"
    text_value: "epdg.three.ie"
  }
  config {
    key: "iwlan.ike_rekey_hard_timer_in_sec"
    int_value: 43200
  }
  config {
    key: "iwlan.ike_rekey_soft_timer_sec_int"
    int_value: 43100
  }
  config {
    key: "show_4g_for_lte_data_icon_bool"
    bool_value: true
  }
  config {
    key: "wfc_spn_format_idx_int"
    int_value: 1
  }
}
last_updated {
  seconds: 1708635149
}
