canonical_name: "jazztel_es"
version: 56000000004
apns {
  apn {
    name: "jazzinternet"
    value: "jazzinternet"
    type: DEFAULT
    type: SUPL
  }
  apn {
    name: "MMS"
    value: "jazzmms"
    type: MMS
    authtype: 1
    mmsc: "http://jazztelmms.com/servlets/mms"
  }
  apn {
    name: "jazzinternet"
    value: ""
    type: IA
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|18|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "carrier_use_ims_first_for_emergency_bool"
    bool_value: false
  }
  config {
    key: "ims.ims_user_agent_string"
    text_value: "#MANUFACTURE# #MODEL# Android #AV# #BUILD# EU02369"
  }
  config {
    key: "ims.ipv4_sip_mtu_size_cellular_int"
    int_value: 1300
  }
  config {
    key: "ims.ipv6_sip_mtu_size_cellular_int"
    int_value: 1300
  }
  config {
    key: "ims.request_uri_type_int"
    int_value: 1
  }
  config {
    key: "imssms.sms_over_ims_supported_rats_int_array"
    int_array {
    }
  }
  config {
    key: "imsss.network_initiated_ussd_over_ims_supported_bool"
    bool_value: false
  }
  config {
    key: "imsss.ut_server_based_services_int_array"
    int_array {
    }
  }
  config {
    key: "imsss.xcap_over_ut_supported_rats_int_array"
    int_array {
    }
  }
  config {
    key: "imsvoice.amrnb_payload_description_bundle"
    bundle {
      config {
        key: "100"
        bundle {
          config {
            key: "imsvoice.amr_codec_attribute_modeset_int_array"
            int_array {
              item: 0
              item: 3
              item: 6
            }
          }
        }
      }
      config {
        key: "101"
        bundle {
          config {
            key: "imsvoice.amr_codec_attribute_modeset_int_array"
            int_array {
              item: 0
              item: 3
              item: 6
            }
          }
          config {
            key: "imsvoice.amr_codec_attribute_payload_format_int"
            int_value: 1
          }
        }
      }
    }
  }
  config {
    key: "imsvoice.amrwb_payload_description_bundle"
    bundle {
      config {
        key: "99"
        bundle {
          config {
            key: "imsvoice.amr_codec_attribute_payload_format_int"
            int_value: 1
          }
        }
      }
    }
  }
  config {
    key: "imsvoice.audio_codec_capability_payload_types_bundle"
    bundle {
      config {
        key: "imsvoice.amrnb_payload_type_int_array"
        int_array {
          item: 100
          item: 101
        }
      }
      config {
        key: "imsvoice.amrwb_payload_type_int_array"
        int_array {
          item: 98
          item: 99
        }
      }
      config {
        key: "imsvoice.dtmfnb_payload_type_int_array"
        int_array {
          item: 106
        }
      }
      config {
        key: "imsvoice.dtmfwb_payload_type_int_array"
        int_array {
          item: 105
        }
      }
      config {
        key: "imsvoice.evs_payload_type_int_array"
        int_array {
          item: 96
          item: 97
        }
      }
    }
  }
  config {
    key: "imsvoice.evs_payload_description_bundle"
    bundle {
      config {
        key: "96"
        bundle {
          config {
            key: "imsvoice.evs_codec_attribute_bandwidth_int"
            int_value: 2
          }
          config {
            key: "imsvoice.evs_codec_attribute_bitrate_int_array"
            int_array {
              item: 3
              item: 6
            }
          }
        }
      }
      config {
        key: "97"
        bundle {
          config {
            key: "imsvoice.evs_codec_attribute_bitrate_int_array"
            int_array {
              item: 0
              item: 6
            }
          }
        }
      }
    }
  }
  config {
    key: "imsvoice.minimum_session_expires_timer_sec_int"
    int_value: 600
  }
  config {
    key: "imsvoice.mo_call_request_timeout_millis_int"
    int_value: 3000
  }
  config {
    key: "imsvoice.oip_source_from_header_bool"
    bool_value: true
  }
  config {
    key: "imsvoice.ringback_timer_millis_int"
    int_value: 60000
  }
  config {
    key: "imsvoice.ringing_timer_millis_int"
    int_value: 60000
  }
  config {
    key: "maxImageHeight"
    int_value: 1944
  }
  config {
    key: "maxImageWidth"
    int_value: 2592
  }
  config {
    key: "maxMessageSize"
    int_value: 512000
  }
  config {
    key: "non_roaming_operator_string_array"
    text_array {
      item: "21401"
      item: "21402"
      item: "21403"
      item: "21404"
      item: "21405"
      item: "21406"
      item: "21407"
      item: "21408"
      item: "21409"
      item: "214010"
      item: "214011"
      item: "214012"
      item: "214013"
      item: "214014"
      item: "214015"
      item: "214016"
      item: "214017"
      item: "214018"
      item: "214019"
      item: "214020"
    }
  }
  config {
    key: "show_4g_for_lte_data_icon_bool"
    bool_value: true
  }
  config {
    key: "unloggable_numbers_string_array"
    text_array {
      item: "900018018"
      item: "016"
      item: "021"
      item: "024"
      item: "028"
      item: "116000"
      item: "116111"
      item: "900202010"
    }
  }
  config {
    key: "wfc_spn_format_idx_int"
    int_value: 1
  }
}
last_updated {
  seconds: 1709519115
}
