canonical_name: "sky_gb"
version: 56000000012
apns {
  apn {
    name: "SKY MMS"
    value: "mms.mobile.sky"
    type: MMS
    bearer_bitmask: "1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|17|20"
    mmsc: "http://185.110.178.96:38090/was"
    mmsc_proxy: "185.110.178.97"
    mmsc_proxy_port: "9028"
  }
  apn {
    name: "SKY WiFi MMS"
    value: "wifi.mms.mobile.sky"
    type: MMS
    bearer_bitmask: "18"
    mmsc: "http://185.110.178.96:38090/was"
    mmsc_proxy: "185.110.178.97"
    mmsc_proxy_port: "9028"
    user_editable: false
  }
  apn {
    name: "SKY Internet"
    value: "mobile.sky"
    type: DEFAULT
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|18|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "bsf.bsf_server_fqdn_string"
    text_value: "bsf.ims.mnc057.mcc234.pub.3gppnetwork.org"
  }
  config {
    key: "carrier_nr_availabilities_int_array"
    int_array {
      item: 1
    }
  }
  config {
    key: "editable_wfc_mode_bool"
    bool_value: false
  }
  config {
    key: "ims.ipv4_sip_mtu_size_cellular_int"
    int_value: 1280
  }
  config {
    key: "ims.ipv6_sip_mtu_size_cellular_int"
    int_value: 1280
  }
  config {
    key: "ims.sip_timer_b_millis_int"
    int_value: 90000
  }
  config {
    key: "ims.sip_timer_f_millis_int"
    int_value: 32000
  }
  config {
    key: "ims.sip_timer_j_millis_int"
    int_value: 32000
  }
  config {
    key: "imsss.network_initiated_ussd_over_ims_supported_bool"
    bool_value: false
  }
  config {
    key: "imsss.ut_as_server_fqdn_string"
    text_value: "xcap.ims.mnc057.mcc234.pub.3gppnetwork.org"
  }
  config {
    key: "imsss.xcap_over_ut_supported_rats_int_array"
    int_array {
      item: 5
      item: 6
      item: 3
      item: 1
      item: 2
    }
  }
  config {
    key: "imsvoice.audio_codec_capability_payload_types_bundle"
    bundle {
      config {
        key: "imsvoice.amrnb_payload_type_int_array"
        int_array {
          item: 102
        }
      }
      config {
        key: "imsvoice.amrwb_payload_type_int_array"
        int_array {
          item: 104
        }
      }
      config {
        key: "imsvoice.dtmfnb_payload_type_int_array"
        int_array {
          item: 97
        }
      }
      config {
        key: "imsvoice.dtmfwb_payload_type_int_array"
        int_array {
          item: 96
        }
      }
      config {
        key: "imsvoice.evs_payload_type_int_array"
        int_array {
          item: 126
        }
      }
    }
  }
  config {
    key: "imsvoice.conference_subscribe_type_int"
    int_value: 0
  }
  config {
    key: "imsvoice.dedicated_bearer_wait_timer_millis_int"
    int_value: 10000
  }
  config {
    key: "imsvoice.evs_payload_description_bundle"
    bundle {
      config {
        key: "126"
        bundle {
          config {
            key: "imsvoice.evs_codec_attribute_bitrate_int_array"
            int_array {
              item: 0
              item: 6
            }
          }
          config {
            key: "imsvoice.evs_codec_attribute_ch_aw_recv_int"
            int_value: 3
          }
        }
      }
    }
  }
  config {
    key: "imsvoice.minimum_session_expires_timer_sec_int"
    int_value: 600
  }
  config {
    key: "imsvoice.oip_source_from_header_bool"
    bool_value: true
  }
  config {
    key: "imsvoice.prack_supported_for_18x_bool"
    bool_value: true
  }
  config {
    key: "non_roaming_operator_string_array"
    text_array {
      item: "23410"
      item: "23426"
      item: "23430"
      item: "23431"
      item: "23432"
      item: "23433"
      item: "23434"
      item: "23486"
    }
  }
  config {
    key: "prefer_2g_bool"
    bool_value: false
  }
  config {
    key: "show_4g_for_lte_data_icon_bool"
    bool_value: true
  }
  config {
    key: "sim_country_iso_override_string"
    text_value: "gb"
  }
  config {
    key: "wfc_spn_format_idx_int"
    int_value: 1
  }
}
last_updated {
  seconds: 1709519115
}
