canonical_name: "tracfoneatt_us"
version: 56000000013
apns {
  apn {
    name: "Tracfone AT&T"
    value: "ereseller"
    type: DEFAULT
    type: MMS
    type: SUPL
    type: FOTA
    mmsc: "http://mmsc.mobile.att.net"
    mmsc_proxy: "proxy.mobile.att.net"
    mmsc_proxy_port: "80"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_editable: false
  }
  apn {
    name: "Tracfone AT&T"
    value: "resellermht"
    type: DUN
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
  apn {
    name: "ATT IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "3|9|10|11|14|15|18|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "5g_icon_configuration_string"
    text_value: "connected_mmwave:5G_Plus,connected:5G,not_restricted_rrc_idle:5G,not_restricted_rrc_con:5G"
  }
  config {
    key: "5g_icon_display_grace_period_string"
    text_value: "connected_mmwave,any,30"
  }
  config {
    key: "5g_nr_ssrsrp_thresholds_int_array"
    int_array {
      item: -117
      item: -111
      item: -105
      item: -99
    }
  }
  config {
    key: "additional_nr_advanced_bands_int_array"
    int_array {
      item: 77
    }
  }
  config {
    key: "allow_hold_call_during_emergency_bool"
    bool_value: false
  }
  config {
    key: "allow_merging_rtt_calls_bool"
    bool_value: true
  }
  config {
    key: "apn.settings_default_protocol_string"
    text_value: "IPV4V6"
  }
  config {
    key: "apn.settings_default_roaming_protocol_string"
    text_value: "IPV4V6"
  }
  config {
    key: "apn_settings_default_apn_types_string_array"
    text_array {
      item: "default"
    }
  }
  config {
    key: "carrier_auto_cancel_cs_notification"
    bool_value: false
  }
  config {
    key: "carrier_certificate_string_array"
    text_array {
      item: "E751E163E91E041382839556D31302DB7058C44D9DF1B5B27FC43BD8F0EE2BBA"
      item: "4AD124DE517BC6BA915B88C17F0AADF764469842156325C26B7CD8B888C41C71"
      item: "55BB3B316919620008AA76A4891E90384BFF2A76AE95C395FE738C2AC609F13F"
    }
  }
  config {
    key: "carrier_default_data_roaming_enabled_bool"
    bool_value: true
  }
  config {
    key: "carrier_default_wfc_ims_mode_int"
    int_value: 1
  }
  config {
    key: "carrier_default_wfc_ims_roaming_enabled_bool"
    bool_value: true
  }
  config {
    key: "carrier_metered_apn_types_strings"
    text_array {
      item: "default"
      item: "dun"
      item: "supl"
    }
  }
  config {
    key: "carrier_metered_roaming_apn_types_strings"
    text_array {
      item: "default"
      item: "dun"
      item: "supl"
    }
  }
  config {
    key: "carrier_name_override_bool"
    bool_value: true
  }
  config {
    key: "carrier_name_string"
    text_value: "Tracfone"
  }
  config {
    key: "carrier_nr_availabilities_int_array"
    int_array {
    }
  }
  config {
    key: "carrier_supports_ss_over_ut_bool"
    bool_value: true
  }
  config {
    key: "carrier_ussd_method_int"
    int_value: 1
  }
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "carrier_wfc_ims_available_bool"
    bool_value: false
  }
  config {
    key: "csp_enabled_bool"
    bool_value: true
  }
  config {
    key: "emergency_number_prefix_string_array"
    text_array {
      item: "*67"
      item: "*82"
      item: "*272"
    }
  }
  config {
    key: "enableSMSDeliveryReports"
    bool_value: false
  }
  config {
    key: "gsm_rssi_thresholds_int_array"
    int_array {
      item: -108
      item: -104
      item: -98
      item: -90
    }
  }
  config {
    key: "hide_enhanced_4g_lte_bool"
    bool_value: false
  }
  config {
    key: "hide_preferred_network_type_bool"
    bool_value: false
  }
  config {
    key: "ignore_rtt_mode_setting_bool"
    bool_value: true
  }
  config {
    key: "ims.geolocation_pidf_in_sip_invite_support_int_array"
    int_array {
      item: 4
      item: 2
    }
  }
  config {
    key: "ims.geolocation_pidf_in_sip_register_support_int_array"
    int_array {
      item: 4
      item: 2
    }
  }
  config {
    key: "ims.ims_pdn_enabled_in_no_vops_support_int_array"
    int_array {
      item: 0
      item: 1
    }
  }
  config {
    key: "ims.ipv4_sip_mtu_size_cellular_int"
    int_value: 1430
  }
  config {
    key: "ims.ipv6_sip_mtu_size_cellular_int"
    int_value: 1430
  }
  config {
    key: "ims.registration_retry_base_timer_millis_int"
    int_value: 120000
  }
  config {
    key: "ims.registration_retry_max_timer_millis_int"
    int_value: 7200000
  }
  config {
    key: "ims.request_uri_type_int"
    int_value: 1
  }
  config {
    key: "ims.sip_timer_b_millis_int"
    int_value: 32000
  }
  config {
    key: "ims.sip_timer_d_millis_int"
    int_value: 32000
  }
  config {
    key: "ims.sip_timer_f_millis_int"
    int_value: 32000
  }
  config {
    key: "ims.sip_timer_h_millis_int"
    int_value: 32000
  }
  config {
    key: "ims.sip_timer_j_millis_int"
    int_value: 32000
  }
  config {
    key: "ims.supported_rats_int_array"
    int_array {
      item: 3
      item: 2
      item: 5
      item: 6
    }
  }
  config {
    key: "ims_dtmf_tone_delay_int"
    int_value: 120
  }
  config {
    key: "ims_reasoninfo_mapping_string_array"
    text_array {
      item: "332|service not allowed in this location|1623"
      item: "352|emergency calls over wifi not allowed in this location|1622"
      item: "510|Call completed elsewhere|1014"
      item: "*|Call is dropped due to Wi-Fi signal is degraded|1407"
    }
  }
  config {
    key: "imsemergency.emergency_qos_precondition_supported_bool"
    bool_value: false
  }
  config {
    key: "imsemergency.emergency_registration_timer_millis_int"
    int_value: 10000
  }
  config {
    key: "imsrtt.text_on_default_bearer_supported_bool"
    bool_value: true
  }
  config {
    key: "imsrtt.text_qos_precondition_supported_bool"
    bool_value: false
  }
  config {
    key: "imsrtt.text_rr_bandwidth_bps_int"
    int_value: 300
  }
  config {
    key: "imsrtt.text_rs_bandwidth_bps_int"
    int_value: 100
  }
  config {
    key: "imssms.sms_csfb_retry_on_failure_bool"
    bool_value: false
  }
  config {
    key: "imssms.sms_over_ims_supported_rats_int_array"
    int_array {
      item: 1
      item: 2
      item: 3
      item: 6
      item: 5
    }
  }
  config {
    key: "imsss.ut_server_based_services_int_array"
    int_array {
      item: 20
      item: 12
      item: 18
      item: 14
      item: 19
      item: 21
      item: 15
      item: 16
      item: 17
      item: 13
      item: 1
      item: 3
      item: 4
      item: 7
      item: 6
      item: 5
      item: 2
      item: 0
      item: 8
      item: 9
      item: 11
    }
  }
  config {
    key: "imsss.ut_terminal_based_services_int_array"
    int_array {
      item: 10
    }
  }
  config {
    key: "imsss.xcap_over_ut_supported_rats_int_array"
    int_array {
      item: 5
      item: 6
      item: 3
      item: 1
      item: 2
    }
  }
  config {
    key: "imsvoice.audio_as_bandwidth_kbps_int"
    int_value: 49
  }
  config {
    key: "imsvoice.audio_codec_capability_payload_types_bundle"
    bundle {
      config {
        key: "imsvoice.amrnb_payload_type_int_array"
        int_array {
          item: 110
        }
      }
      config {
        key: "imsvoice.amrwb_payload_type_int_array"
        int_array {
          item: 104
        }
      }
      config {
        key: "imsvoice.dtmfnb_payload_type_int_array"
        int_array {
          item: 97
        }
      }
      config {
        key: "imsvoice.dtmfwb_payload_type_int_array"
        int_array {
          item: 96
        }
      }
      config {
        key: "imsvoice.evs_payload_type_int_array"
        int_array {
          item: 127
        }
      }
    }
  }
  config {
    key: "imsvoice.evs_payload_description_bundle"
    bundle {
      config {
        key: "127"
        bundle {
          config {
            key: "imsvoice.evs_codec_attribute_bitrate_int_array"
            int_array {
              item: 0
              item: 4
            }
          }
          config {
            key: "imsvoice.evs_codec_attribute_ch_aw_recv_int"
            int_value: 2
          }
        }
      }
    }
  }
  config {
    key: "imsvoice.include_caller_id_service_codes_in_sip_invite_bool"
    bool_value: true
  }
  config {
    key: "imsvoice.mo_call_request_timeout_millis_int"
    int_value: 0
  }
  config {
    key: "imsvoice.ringback_timer_millis_int"
    int_value: 180000
  }
  config {
    key: "imsvoice.ringing_timer_millis_int"
    int_value: 45000
  }
  config {
    key: "imsvoice.rtp_jitter_threshold_millis_int"
    int_value: 100
  }
  config {
    key: "imsvoice.rtp_packet_loss_rate_threshold_int"
    int_value: 30
  }
  config {
    key: "imsvoice.session_timer_supported_bool"
    bool_value: false
  }
  config {
    key: "imsvoice.srvcc_type_int_array"
    int_array {
      item: 0
      item: 1
      item: 2
    }
  }
  config {
    key: "imsvoice.voice_on_default_bearer_supported_bool"
    bool_value: true
  }
  config {
    key: "imsvoice.voice_qos_precondition_supported_bool"
    bool_value: false
  }
  config {
    key: "imsvt.video_as_bandwidth_kbps_int"
    int_value: 416
  }
  config {
    key: "imsvt.video_on_default_bearer_supported_bool"
    bool_value: true
  }
  config {
    key: "imsvt.video_qos_precondition_supported_bool"
    bool_value: false
  }
  config {
    key: "imswfc.emergency_call_over_emergency_pdn_bool"
    bool_value: true
  }
  config {
    key: "inflate_signal_strength_bool"
    bool_value: true
  }
  config {
    key: "iwlan.diffie_hellman_groups_int_array"
    int_array {
      item: 14
    }
  }
  config {
    key: "iwlan.epdg_address_priority_int_array"
    int_array {
      item: 0
    }
  }
  config {
    key: "iwlan.epdg_static_address_string"
    text_value: "epdg.epc.att.net"
  }
  config {
    key: "iwlan.key_error_policy_config_string"
    text_value: "[{\"ApnName\": \"*\",\"ErrorTypes\": [{\"ErrorType\": \"IKE_PROTOCOL_ERROR_TYPE\",\"ErrorDetails\": [\"9000\", \"9001\", \"11011\", \"9003\", \"11001\", \"9006\", \"8192\"],\"RetryArray\": [],\"UnthrottlingEvents\": []}, {\"ErrorType\": \"IKE_PROTOCOL_ERROR_TYPE\",\"ErrorDetails\": [\"*\"],\"RetryArray\": [\"10\", \"60\", \"120\", \"240\", \"-1\"],\"UnthrottlingEvents\": [\"APM_ENABLE_EVENT\", \"WIFI_DISABLE_EVENT\", \"WIFI_CALLING_DISABLE_EVENT\"]}]}]"
  }
  config {
    key: "iwlan_handover_policy_string_array"
    text_array {
      item: "source=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN|UNKNOWN, target=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN, type=disallowed, capabilities=EIMS|MMS|XCAP|CBS"
      item: "source=IWLAN|UNKNOWN, target=GERAN, type=disallowed, capabilities=IMS"
      item: "source=GERAN, target=IWLAN, type=disallowed, capabilities=IMS"
      item: "source=UTRAN|EUTRAN|NGRAN|IWLAN, target=UTRAN|EUTRAN|NGRAN|IWLAN, type=allowed, capabilities=IMS"
    }
  }
  config {
    key: "lte_rsrp_thresholds_int_array"
    int_array {
      item: -120
      item: -110
      item: -100
      item: -90
    }
  }
  config {
    key: "maxImageHeight"
    int_value: 1944
  }
  config {
    key: "maxImageWidth"
    int_value: 2592
  }
  config {
    key: "maxMessageSize"
    int_value: 1048576
  }
  config {
    key: "maxSubjectLength"
    int_value: 0
  }
  config {
    key: "min_udp_port_4500_nat_timeout_sec_int"
    int_value: 600
  }
  config {
    key: "mmi_two_digit_number_pattern_string_array"
    text_array {
      item: "0"
      item: "00"
      item: "*0"
      item: "*1"
      item: "*2"
      item: "*3"
      item: "*4"
      item: "*5"
      item: "*6"
      item: "*7"
      item: "*8"
      item: "*9"
      item: "#0"
      item: "#1"
      item: "#2"
      item: "#3"
      item: "#4"
      item: "#5"
      item: "#6"
      item: "#7"
      item: "#8"
      item: "#9"
    }
  }
  config {
    key: "non_roaming_operator_string_array"
    text_array {
      item: "310"
      item: "311"
      item: "312"
      item: "313"
      item: "314"
      item: "315"
      item: "316"
    }
  }
  config {
    key: "nr_advanced_threshold_bandwidth_khz_int"
    int_value: 50000
  }
  config {
    key: "operator_name_filter_pattern_string"
    text_value: "(.*)\\.{3}[12]$"
  }
  config {
    key: "prefer_2g_bool"
    bool_value: false
  }
  config {
    key: "preferred_ike_protocol_int"
    int_value: 40
  }
  config {
    key: "qns.choose_wfc_preferred_transport_in_both_bad_condition_int_array"
    int_array {
      item: 1
    }
  }
  config {
    key: "qns.fallback_network_quality_evaluation_bool"
    bool_value: false
  }
  config {
    key: "qns.idle_eutran_rsrp_int_array"
    int_array {
      item: -90
      item: -108
    }
  }
  config {
    key: "qns.idle_eutran_rssnr_int_array"
    int_array {
      item: 2
      item: -3
    }
  }
  config {
    key: "qns.idle_ngran_ssrsrp_int_array"
    int_array {
      item: -90
      item: -108
    }
  }
  config {
    key: "qns.idle_ngran_sssinr_int_array"
    int_array {
      item: 2
      item: -3
    }
  }
  config {
    key: "qns.idle_utran_ecno_int_array"
    int_array {
      item: -11
      item: -15
    }
  }
  config {
    key: "qns.idle_utran_rscp_int_array"
    int_array {
      item: -73
      item: -93
    }
  }
  config {
    key: "qns.ims_cellular_allowed_rat_string_array"
    text_array {
      item: "LTE"
      item: "NR"
      item: "3G"
    }
  }
  config {
    key: "qns.ims_wlan_hysteresis_timer_ms_int_array"
    int_array {
      item: 5000
      item: 0
      item: 0
    }
  }
  config {
    key: "qns.ims_wwan_hysteresis_timer_ms_int_array"
    int_array {
      item: 5000
      item: 0
      item: 0
    }
  }
  config {
    key: "qns.in_call_rovein_allowed_and_fallback_reason_int_array"
    int_array {
      item: 1
      item: 2
    }
  }
  config {
    key: "qns.media_threshold_rtp_packet_loss_time_millis"
    int_value: 12000
  }
  config {
    key: "qns.prefer_current_transport_type_in_voice_call_bool"
    bool_value: true
  }
  config {
    key: "qns.rtp_metrics_int_array"
    int_array {
      item: 100
      item: 30
      item: 5000
      item: 2000
    }
  }
  config {
    key: "qns.sos_transport_type_int"
    int_value: 2
  }
  config {
    key: "qns.support_vops_notavailable_priority_iwlan_bool"
    bool_value: false
  }
  config {
    key: "qns.voice_eutran_rsrp_int_array"
    int_array {
      item: 65535
      item: -108
    }
  }
  config {
    key: "qns.voice_eutran_rssnr_int_array"
    int_array {
      item: 65535
      item: -3
    }
  }
  config {
    key: "qns.voice_ngran_ssrsrp_int_array"
    int_array {
      item: 65535
      item: -108
    }
  }
  config {
    key: "qns.voice_ngran_sssinr_int_array"
    int_array {
      item: 65535
      item: -3
    }
  }
  config {
    key: "qns.wifi_rssi_thresholdbackhaul_timer_int"
    int_value: 0
  }
  config {
    key: "qns.xcap_rat_preference_int"
    int_value: 3
  }
  config {
    key: "rcs_request_forbidden_by_sip_489_bool"
    bool_value: true
  }
  config {
    key: "read_only_apn_types_string_array"
    text_array {
      item: "dun"
      item: "ims"
    }
  }
  config {
    key: "recipientLimit"
    int_value: 10
  }
  config {
    key: "roaming_operator_string_array"
    text_array {
      item: "310110"
      item: "310140"
      item: "310400"
      item: "310470"
      item: "311170"
    }
  }
  config {
    key: "rtt_downgrade_supported_bool"
    bool_value: true
  }
  config {
    key: "rtt_supported_bool"
    bool_value: true
  }
  config {
    key: "rtt_supported_while_roaming_bool"
    bool_value: true
  }
  config {
    key: "show_4g_for_3g_data_icon_bool"
    bool_value: true
  }
  config {
    key: "show_carrier_data_icon_pattern_string"
    text_value: ""
  }
  config {
    key: "skip_cf_fail_to_disable_dialog_bool"
    bool_value: true
  }
  config {
    key: "support_pause_ims_video_calls_bool"
    bool_value: false
  }
  config {
    key: "tty_supported_bool"
    bool_value: false
  }
  config {
    key: "volte_replacement_rat_int"
    int_value: 3
  }
  config {
    key: "wcdma_default_signal_strength_measurement_string"
    text_value: "rscp"
  }
  config {
    key: "wcdma_rscp_thresholds_int_array"
    int_array {
      item: -105
      item: -99
      item: -89
      item: -79
    }
  }
  config {
    key: "wfc_emergency_address_carrier_app_string"
    text_value: "com.google.android.wfcactivation/.WfcActivationActivity"
  }
  config {
    key: "wfc_spn_format_idx_int"
    int_value: 1
  }
  config {
    key: "wifi.carrier_profiles_version_int"
    int_value: 1
  }
  config {
    key: "wifi.passpoint_profiles_string_array"
    text_array {
      item: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><PasspointProfile><PPSMO><![CDATA[<MgmtTree xmlns=\"syncml:dmddf1.2\"><VerDTD>1.2</VerDTD><Node><NodeName>PerProviderSubscription</NodeName><RTProperties><Type><DDFName>urn:wfa:mo:hotspot2dot0-perprovidersubscription:1.0</DDFName></Type></RTProperties><Node><NodeName>i001</NodeName><Node><NodeName>HomeSP</NodeName><Node><NodeName>FriendlyName</NodeName><Value>AT&amp;T Passpoint</Value></Node><Node><NodeName>FQDN</NodeName><Value>attwifi.com</Value></Node></Node><Node><NodeName>Credential</NodeName><Node><NodeName>Realm</NodeName><Value>wlan.mnc410.mcc310.3gppnetwork.org</Value></Node><Node><NodeName>SIM</NodeName><Node><NodeName>IMSI</NodeName><Value>310410*</Value></Node><Node><NodeName>EAPType</NodeName><Value>23</Value></Node></Node></Node></Node></Node></MgmtTree>]]></PPSMO></PasspointProfile>"
    }
  }
}
last_updated {
  seconds: 1707299235
}
