canonical_name: "vodafone_nl"
version: 56000000460
apns {
  apn {
    name: "Internet"
    value: "live.vodafone.com"
    type: DEFAULT
    type: SUPL
    user: "vodafone"
    password: "vodafone"
    authtype: 1
  }
  apn {
    name: "ims"
    value: "IMS"
    type: IMS
    bearer_bitmask: "14|18|20"
    user_visible: false
  }
}
configs {
  config {
    key: "auto_retry_failed_wifi_emergency_call"
    bool_value: true
  }
  config {
    key: "bsf.bsf_server_port_int"
    int_value: 10080
  }
  config {
    key: "carrier_default_wfc_ims_enabled_bool"
    bool_value: true
  }
  config {
    key: "carrier_default_wfc_ims_mode_int"
    int_value: 1
  }
  config {
    key: "carrier_nr_availabilities_int_array"
    int_array {
      item: 1
    }
  }
  config {
    key: "carrier_supports_ss_over_ut_bool"
    bool_value: true
  }
  config {
    key: "carrier_ussd_method_int"
    int_value: 2
  }
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "carrier_wfc_ims_available_bool"
    bool_value: true
  }
  config {
    key: "default_vm_number_string"
    text_value: "+31654501233"
  }
  config {
    key: "enabledMMS"
    bool_value: false
  }
  config {
    key: "hide_enhanced_4g_lte_bool"
    bool_value: true
  }
  config {
    key: "ims.ipsec_authentication_algorithms_int_array"
    int_array {
      item: 1
    }
  }
  config {
    key: "ims.ipsec_encryption_algorithms_int_array"
    int_array {
      item: 0
      item: 2
    }
  }
  config {
    key: "ims.ipv4_sip_mtu_size_cellular_int"
    int_value: 1300
  }
  config {
    key: "ims.ipv6_sip_mtu_size_cellular_int"
    int_value: 1300
  }
  config {
    key: "ims.registration_retry_max_timer_millis_int"
    int_value: 300000
  }
  config {
    key: "ims_reasoninfo_mapping_string_array"
    text_array {
      item: "510|Call completed elsewhere|1014"
      item: "*|Call is dropped due to Wi-Fi signal is degraded|1407"
    }
  }
  config {
    key: "imsss.network_initiated_ussd_over_ims_supported_bool"
    bool_value: false
  }
  config {
    key: "imsss.ut_as_server_port_int"
    int_value: 8080
  }
  config {
    key: "imsss.ut_iptype_home_int"
    int_value: 0
  }
  config {
    key: "imsss.ut_requires_ims_registration_bool"
    bool_value: true
  }
  config {
    key: "imsss.xcap_over_ut_supported_rats_int_array"
    int_array {
      item: 6
      item: 3
      item: 1
      item: 2
    }
  }
  config {
    key: "imsvoice.audio_codec_capability_payload_types_bundle"
    bundle {
      config {
        key: "imsvoice.amrnb_payload_type_int_array"
        int_array {
          item: 102
        }
      }
      config {
        key: "imsvoice.amrwb_payload_type_int_array"
        int_array {
          item: 104
        }
      }
      config {
        key: "imsvoice.dtmfnb_payload_type_int_array"
        int_array {
          item: 97
        }
      }
      config {
        key: "imsvoice.dtmfwb_payload_type_int_array"
        int_array {
          item: 96
        }
      }
      config {
        key: "imsvoice.evs_payload_type_int_array"
        int_array {
          item: 127
        }
      }
    }
  }
  config {
    key: "imsvoice.conference_factory_uri_string"
    text_value: "conference@conference.ims.mnc004.mcc204.3gppnetwork.org"
  }
  config {
    key: "imsvoice.conference_subscribe_type_int"
    int_value: 0
  }
  config {
    key: "imsvoice.minimum_session_expires_timer_sec_int"
    int_value: 600
  }
  config {
    key: "imsvoice.ringback_timer_millis_int"
    int_value: 180000
  }
  config {
    key: "imsvoice.ringing_timer_millis_int"
    int_value: 180000
  }
  config {
    key: "imswfc.emergency_call_over_emergency_pdn_bool"
    bool_value: true
  }
  config {
    key: "iwlan.child_sa_rekey_hard_timer_sec_int"
    int_value: 43300
  }
  config {
    key: "iwlan.child_sa_rekey_soft_timer_sec_int"
    int_value: 43200
  }
  config {
    key: "iwlan.diffie_hellman_groups_int_array"
    int_array {
      item: 2
      item: 14
      item: 15
      item: 16
    }
  }
  config {
    key: "iwlan.ike_rekey_hard_timer_in_sec"
    int_value: 43300
  }
  config {
    key: "iwlan.ike_rekey_soft_timer_sec_int"
    int_value: 43200
  }
  config {
    key: "iwlan.key_error_policy_config_string"
    text_value: "[{\"ApnName\": \"*\",\"ErrorTypes\": [{\"ErrorType\": \"IKE_PROTOCOL_ERROR_TYPE\",\"ErrorDetails\": [\"9002\"],\"RetryArray\": [\"1800\", \"-1\"],\"UnthrottlingEvents\": [\"APM_ENABLE_EVENT\", \"WIFI_DISABLE_EVENT\", \"WIFI_AP_CHANGED_EVENT\", \"WIFI_CALLING_DISABLE_EVENT\"]}]}]"
  }
  config {
    key: "maxImageHeight"
    int_value: 1944
  }
  config {
    key: "maxImageWidth"
    int_value: 2592
  }
  config {
    key: "maxMessageSize"
    int_value: 1048576
  }
  config {
    key: "qns.block_iwlan_in_international_roaming_without_wwan_bool"
    bool_value: true
  }
  config {
    key: "qns.idle_eutran_rsrp_int_array"
    int_array {
      item: -104
      item: -118
    }
  }
  config {
    key: "qns.idle_geran_rssi_int_array"
    int_array {
      item: -94
      item: -102
    }
  }
  config {
    key: "qns.idle_utran_rscp_int_array"
    int_array {
      item: -105
      item: -112
    }
  }
  config {
    key: "qns.ims_wlan_hysteresis_timer_ms_int_array"
    int_array {
      item: 5000
      item: 5000
      item: 5000
    }
  }
  config {
    key: "qns.ims_wwan_hysteresis_timer_ms_int_array"
    int_array {
      item: 5000
      item: 5000
      item: 5000
    }
  }
  config {
    key: "qns.sos_transport_type_int"
    int_value: 2
  }
  config {
    key: "qns.voice_eutran_rsrp_int_array"
    int_array {
      item: -104
      item: -118
    }
  }
  config {
    key: "qns.voice_geran_rssi_int_array"
    int_array {
      item: -94
      item: -102
    }
  }
  config {
    key: "qns.voice_utran_rscp_int_array"
    int_array {
      item: -105
      item: -112
    }
  }
  config {
    key: "qns.xcap_rat_preference_int"
    int_value: 2
  }
  config {
    key: "show_4g_for_lte_data_icon_bool"
    bool_value: true
  }
  config {
    key: "wfc_spn_format_idx_int"
    int_value: 11
  }
}
last_updated {
  seconds: 1692898787
}
