canonical_name: "mobifone_vn"
version: 57000000001
apns {
  apn {
    name: "Mobi-wap-gprs 2"
    value: "m-wap"
    type: DEFAULT
    type: SUPL
    user: "mms"
    password: "mms"
    authtype: 1
  }
  apn {
    name: "Mobi-wap-gprs 1"
    value: "m-wap"
    type: DEFAULT
    type: SUPL
    proxy: "203.162.21.107"
    port: "8080"
    user: "mms"
    password: "mms"
    authtype: 1
  }
  apn {
    name: "Mobi-gprs-mms"
    value: "m-i090"
    type: MMS
    user: "mms"
    password: "mms"
    authtype: 1
    mmsc: "http://203.162.21.114/mmsc"
    mmsc_proxy: "203.162.21.114"
    mmsc_proxy_port: "8080"
  }
}
configs {
  config {
    key: "carrier_nr_availabilities_int_array"
    int_array {
      item: 1
    }
  }
}
last_updated {
  seconds: 1713418446
}
