canonical_name: "skylo_zz"
version: 60000000002
apns {
  apn {
    name: "Skylo"
    value: "pixel.ntn"
    type: DEFAULT
    user_visible: false
    user_editable: false
    14: 4
    15: 4
  }
}
configs {
}
last_updated {
  seconds: 1706100402
}
