canonical_name: "spectrummso_us"
version: 62000000001
apns {
  apn {
    name: "Spectrum"
    value: "spectrum"
    type: DEFAULT
    protocol: IPV4V6
  }
}
configs {
  config {
    key: "5g_nr_ssrsrp_thresholds_int_array"
    int_array {
      item: -125
      item: -119
      item: -110
      item: -104
    }
  }
  config {
    key: "always_show_primary_signal_bar_in_opportunistic_network_boolean"
    bool_value: true
  }
  config {
    key: "boosted_lte_earfcns_string_array"
    text_array {
      item: "600-1199"
      item: "1950-2399"
    }
  }
  config {
    key: "carrier_nr_availabilities_int_array"
    int_array {
      item: 2
    }
  }
  config {
    key: "imsemergency.emergency_domain_preference_int_array"
    int_array {
      item: 2
      item: 1
    }
  }
  config {
    key: "imsemergency.emergency_domain_preference_roaming_int_array"
    int_array {
      item: 2
      item: 1
    }
  }
  config {
    key: "imsemergency.emergency_over_ims_supported_rats_int_array"
    int_array {
      item: 3
    }
  }
  config {
    key: "imsss.xcap_over_ut_supported_rats_int_array"
    int_array {
    }
  }
  config {
    key: "imsvoice.audio_codec_capability_payload_types_bundle"
    bundle {
      config {
        key: "imsvoice.amrnb_payload_type_int_array"
        int_array {
          item: 98
          item: 103
        }
      }
      config {
        key: "imsvoice.amrwb_payload_type_int_array"
        int_array {
          item: 100
          item: 105
        }
      }
      config {
        key: "imsvoice.dtmfnb_payload_type_int_array"
        int_array {
          item: 97
        }
      }
      config {
        key: "imsvoice.dtmfwb_payload_type_int_array"
        int_array {
          item: 96
        }
      }
    }
  }
  config {
    key: "lte_earfcns_rsrp_boost_int"
    int_value: 6
  }
  config {
    key: "lte_rsrp_thresholds_int_array"
    int_array {
      item: -115
      item: -105
      item: -95
      item: -85
    }
  }
  config {
    key: "opportunistic.5g_data_switch_exit_hysteresis_time_long"
    long_value: 2000
  }
  config {
    key: "opportunistic.5g_data_switch_hysteresis_time_long"
    long_value: 2000
  }
  config {
    key: "opportunistic.entry_threshold_ss_rsrp_int"
    int_value: -111
  }
  config {
    key: "opportunistic.entry_threshold_ss_rsrq_double"
    double_value: -18.5
  }
  config {
    key: "opportunistic.exit_threshold_ss_rsrp_int"
    int_value: -120
  }
  config {
    key: "opportunistic.exit_threshold_ss_rsrq_double"
    double_value: -18.5
  }
  config {
    key: "opportunistic_network_data_switch_exit_hysteresis_time_long"
    long_value: 2000
  }
  config {
    key: "opportunistic_network_data_switch_hysteresis_time_long"
    long_value: 2000
  }
  config {
    key: "opportunistic_network_entry_threshold_rsrp_int"
    int_value: -111
  }
  config {
    key: "opportunistic_network_entry_threshold_rssnr_int"
    int_value: -100
  }
  config {
    key: "opportunistic_network_exit_threshold_rsrp_int"
    int_value: -120
  }
  config {
    key: "opportunistic_network_exit_threshold_rssnr_int"
    int_value: -110
  }
  config {
    key: "ping_test_before_data_switch_bool"
    bool_value: false
  }
}
last_updated {
  seconds: 1725936038
}
