canonical_name: "2degrees_nz"
version: 50000000003
apns {
  apn {
    name: "2Degrees Internet"
    value: "internet"
    type: DEFAULT
    type: SUPL
  }
  apn {
    name: "2Degrees MMS"
    value: "mms"
    type: MMS
    mmsc: "http://mms.2degreesmobile.net.nz:48090"
    mmsc_proxy: "118.148.1.118"
    mmsc_proxy_port: "8080"
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|18|20"
    user_visible: false
  }
}
configs {
  config {
    key: "ims.ipv4_sip_mtu_size_cellular_int"
    int_value: 1500
  }
  config {
    key: "ims.ipv6_sip_mtu_size_cellular_int"
    int_value: 1500
  }
  config {
    key: "roaming_operator_string_array"
    text_array {
      item: "53001"
    }
  }
  config {
    key: "show_4g_for_lte_data_icon_bool"
    bool_value: true
  }
}
last_updated {
  seconds: 1688093790
}
