canonical_name: "astca_as"
version: 50000000003
apns {
  apn {
    name: "ASTCA"
    value: "internet.astca"
    type: DEFAULT
    authtype: 1
    user_editable: false
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
}
last_updated {
  seconds: 1688093790
}
