canonical_name: "carolinawest_us"
version: 50000000003
apns {
  apn {
    name: "Carolina West Wireless"
    value: "home.cww.com"
    type: DEFAULT
    type: SUPL
    type: CBS
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_editable: false
  }
  apn {
    name: "Carolina West Tethering"
    value: "tethering.cww.com"
    type: DUN
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_editable: false
  }
  apn {
    name: "Carolina West Wireless MMS"
    value: "mms"
    type: MMS
    mmsc: "http://mms.cwwmms.com/cww/mms.php"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_editable: false
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "httpParams"
    text_value: "X-MDN: ##LINE1##"
  }
  config {
    key: "maxImageHeight"
    int_value: 2432
  }
  config {
    key: "maxImageWidth"
    int_value: 4320
  }
  config {
    key: "maxMessageSize"
    int_value: 1048576
  }
  config {
    key: "maxSubjectLength"
    int_value: 80
  }
  config {
    key: "recipientLimit"
    int_value: 20
  }
  config {
    key: "smsToMmsTextThreshold"
    int_value: 1
  }
}
last_updated {
  seconds: 1688093790
}
