canonical_name: "celluarone_us"
version: 50000000003
apns {
  apn {
    name: "IMS"
    value: "ims.cellularoneaz.net"
    type: IMS
    bearer_bitmask: "14|18|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
  apn {
    name: "Cellular One NEAZ ISP"
    value: "isp.cellularoneaz.net"
    type: DEFAULT
    type: SUPL
  }
  apn {
    name: "Cellular One ClearSky MMS"
    value: "wap.c1csky.net"
    type: MMS
    mmsc: "http://mmsc.c1neaz.csky.us:6672"
    mmsc_proxy: "209.4.229.94"
    mmsc_proxy_port: "9401"
  }
}
configs {
  config {
    key: "ims.ipv4_sip_mtu_size_cellular_int"
    int_value: 1300
  }
  config {
    key: "ims.ipv6_sip_mtu_size_cellular_int"
    int_value: 1300
  }
}
last_updated {
  seconds: 1688093790
}
