canonical_name: "chinamobile_hk"
version: 50000000001
apns {
  apn {
    name: "CMHK MMS"
    value: "cmhk"
    type: MMS
    mmsc: "http://mms.hk.chinamobile.com/mms"
  }
  apn {
    name: "CMHK Data"
    value: "cmhk"
    type: DEFAULT
    type: SUPL
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "support_tdscdma_roaming_networks_string_array"
    text_array {
      item: "46000"
      item: "46002"
      item: "46007"
      item: "46008"
    }
  }
}
last_updated {
  seconds: 1680233416
}
