canonical_name: "consumercellulartmo_us"
version: 50000000570
apns {
  apn {
    name: "Consumer Cellular"
    value: "wholesale"
    type: DEFAULT
    type: MMS
    type: SUPL
    type: HIPRI
    mmsc: "http://wholesale.mmsmvno.com/mms/wapenc"
  }
  apn {
    name: "Consumer Cellular IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV6
    mtu: 1440
    user_visible: false
    always_on: true
  }
  apn {
    name: "Consumer Cellular IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "18"
    protocol: IPV6
    roaming_protocol: IPV6
    mtu: 1440
    user_visible: false
    always_on: true
  }
}
configs {
  config {
    key: "carrier_default_wfc_ims_enabled_bool"
    bool_value: true
  }
  config {
    key: "carrier_default_wfc_ims_mode_int"
    int_value: 1
  }
  config {
    key: "carrier_default_wfc_ims_roaming_enabled_bool"
    bool_value: true
  }
  config {
    key: "carrier_default_wfc_ims_roaming_mode_int"
    int_value: 2
  }
  config {
    key: "carrier_ims_gba_required_bool"
    bool_value: true
  }
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "carrier_vt_available_bool"
    bool_value: false
  }
  config {
    key: "carrier_wfc_ims_available_bool"
    bool_value: true
  }
  config {
    key: "emergency_number_prefix_string_array"
    text_array {
      item: "*272"
    }
  }
  config {
    key: "maxImageHeight"
    int_value: 1944
  }
  config {
    key: "maxImageWidth"
    int_value: 2592
  }
  config {
    key: "maxMessageSize"
    int_value: 1048576
  }
  config {
    key: "mmi_two_digit_number_pattern_string_array"
    text_array {
      item: "0"
      item: "00"
      item: "*0"
      item: "*1"
      item: "*2"
      item: "*3"
      item: "*4"
      item: "*5"
      item: "*6"
      item: "*7"
      item: "*8"
      item: "*9"
      item: "#0"
      item: "#1"
      item: "#2"
      item: "#3"
      item: "#4"
      item: "#5"
      item: "#6"
      item: "#7"
      item: "#8"
      item: "#9"
    }
  }
  config {
    key: "rtt_supported_bool"
    bool_value: true
  }
  config {
    key: "volte_replacement_rat_int"
    int_value: 3
  }
  config {
    key: "wfc_carrier_name_override_by_pnn_bool"
    bool_value: true
  }
  config {
    key: "wfc_operator_error_codes_string_array"
    text_array {
      item: "REG09|0"
    }
  }
  config {
    key: "wfc_spn_format_idx_int"
    int_value: 1
  }
}
last_updated {
  seconds: 1688093790
}
