canonical_name: "eastlink_ca"
version: 50000000001
apns {
  apn {
    name: "Eastlink MMS"
    value: "mms.mobi.eastlink.ca"
    type: MMS
    mmsc: "http://mmss.mobi.eastlink.ca"
    mmsc_proxy: "10.232.12.49"
    mmsc_proxy_port: "8080"
  }
  apn {
    name: "Eastlink Internet"
    value: "wisp.mobi.eastlink.ca"
    type: DEFAULT
    user_editable: false
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "gps.es_extension_sec"
    text_value: "300"
  }
  config {
    key: "hide_enhanced_4g_lte_bool"
    bool_value: true
  }
  config {
    key: "maxImageHeight"
    int_value: 1944
  }
  config {
    key: "maxImageWidth"
    int_value: 2592
  }
  config {
    key: "maxMessageSize"
    int_value: 1048576
  }
  config {
    key: "maxSubjectLength"
    int_value: 80
  }
  config {
    key: "recipientLimit"
    int_value: 20
  }
  config {
    key: "smsToMmsTextThreshold"
    int_value: 6
  }
}
last_updated {
  seconds: 1679645347
}
