canonical_name: "elisa1_fi"
version: 50000000001
apns {
  apn {
    name: "Saunalahti Internet"
    value: "internet.saunalahti"
    type: DEFAULT
    type: SUPL
  }
  apn {
    name: "Saunalahti MMS"
    value: "mms.saunalahti.fi"
    type: MMS
    mmsc: "http://mms.saunalahti.fi:8002/"
    mmsc_proxy: "62.142.4.197"
    mmsc_proxy_port: "8080"
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "bsf.bsf_server_fqdn_string"
    text_value: "bsf.ims.mnc005.mcc244.pub.3gppnetwork.org"
  }
  config {
    key: "bsf.bsf_server_port_int"
    int_value: 9001
  }
  config {
    key: "hide_enhanced_4g_lte_bool"
    bool_value: true
  }
  config {
    key: "imsss.ut_as_server_fqdn_string"
    text_value: "ap.ims.mnc005.mcc244.pub.3gppnetwork.org"
  }
  config {
    key: "imsss.ut_as_server_port_int"
    int_value: 9002
  }
  config {
    key: "imsvoice.conference_factory_uri_string"
    text_value: "7888@ims.mnc005.mcc244.3gppnetwork.org"
  }
}
last_updated {
  seconds: 1684458421
}
