canonical_name: "evolve_us"
version: 50000000001
apns {
  apn {
    name: "INTERNET"
    value: "internet"
    type: DEFAULT
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_editable: false
  }
  apn {
    name: "MMS"
    value: "mms"
    type: MMS
    mmsc: "http://mms01.evolvecellular.com"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_editable: false
  }
  apn {
    name: "TETHERING"
    value: "tethering"
    type: DUN
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_editable: false
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "carrier_name_override_bool"
    bool_value: true
  }
  config {
    key: "carrier_name_string"
    text_value: "Evolve"
  }
  config {
    key: "hide_enhanced_4g_lte_bool"
    bool_value: true
  }
}
last_updated {
  seconds: 1683865158
}
