canonical_name: "fastweb_it"
version: 50000000001
apns {
  apn {
    name: "Fastweb"
    value: "apn.fastweb.it"
    type: DEFAULT
    type: MMS
    type: SUPL
    mmsc: "http://mms.fastweb.it/mms/wapenc"
    mmsc_proxy: "85.18.189.217"
    mmsc_proxy_port: "8080"
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "hide_enhanced_4g_lte_bool"
    bool_value: true
  }
  config {
    key: "maxImageHeight"
    int_value: 1944
  }
  config {
    key: "maxImageWidth"
    int_value: 2592
  }
  config {
    key: "maxMessageSize"
    int_value: 1048576
  }
  config {
    key: "show_4g_for_lte_data_icon_bool"
    bool_value: true
  }
}
last_updated {
  seconds: 1679645347
}
