canonical_name: "gci_us"
version: 50000000003
apns {
  apn {
    name: "GCI WEB"
    value: "web.gci"
    type: DEFAULT
    type: SUPL
    user_editable: false
  }
  apn {
    name: "HOS"
    value: "hos.gci"
    type: MMS
    proxy: "24.237.158.34"
    port: "9201"
    mmsc: "http://mmsc.gci.net"
    mmsc_proxy: "24.237.158.34"
    mmsc_proxy_port: "9201"
    user_editable: false
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "maxImageHeight"
    int_value: 1944
  }
  config {
    key: "maxImageWidth"
    int_value: 2592
  }
  config {
    key: "maxMessageSize"
    int_value: 1048576
  }
}
last_updated {
  seconds: 1688093790
}
