canonical_name: "hotmobile_il"
version: 50000000001
apns {
  apn {
    name: "HOT mobile PC"
    value: "pc.hotm"
    type: DUN
    user_visible: false
  }
  apn {
    name: "HOT mobile Internet"
    value: "net.hotm"
    type: DEFAULT
    type: SUPL
  }
  apn {
    name: "HOT mobile MMS"
    value: "mms.hotm"
    type: MMS
    mmsc: "http://mms.hotmobile.co.il"
    mmsc_proxy: "80.246.131.99"
    mmsc_proxy_port: "80"
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "hide_enhanced_4g_lte_bool"
    bool_value: true
  }
  config {
    key: "non_roaming_operator_string_array"
    text_array {
      item: "42503"
    }
  }
  config {
    key: "sim_country_iso_override_string"
    text_value: "il"
  }
}
last_updated {
  seconds: 1684458421
}
