canonical_name: "jazztel_es"
version: 50000000001
apns {
  apn {
    name: "jazzinternet"
    value: "jazzinternet"
    type: DEFAULT
    type: SUPL
  }
  apn {
    name: "MMS"
    value: "jazzmms"
    type: MMS
    authtype: 1
    mmsc: "http://jazztelmms.com/servlets/mms"
  }
  apn {
    name: "jazzinternet"
    value: ""
    type: IA
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|18|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "carrier_use_ims_first_for_emergency_bool"
    bool_value: false
  }
  config {
    key: "maxImageHeight"
    int_value: 1944
  }
  config {
    key: "maxImageWidth"
    int_value: 2592
  }
  config {
    key: "maxMessageSize"
    int_value: 512000
  }
  config {
    key: "non_roaming_operator_string_array"
    text_array {
      item: "21401"
      item: "21402"
      item: "21403"
      item: "21404"
      item: "21405"
      item: "21406"
      item: "21407"
      item: "21408"
      item: "21409"
      item: "214010"
      item: "214011"
      item: "214012"
      item: "214013"
      item: "214014"
      item: "214015"
      item: "214016"
      item: "214017"
      item: "214018"
      item: "214019"
      item: "214020"
    }
  }
  config {
    key: "show_4g_for_lte_data_icon_bool"
    bool_value: true
  }
  config {
    key: "unloggable_numbers_string_array"
    text_array {
      item: "900018018"
    }
  }
  config {
    key: "wfc_spn_format_idx_int"
    int_value: 1
  }
}
last_updated {
  seconds: 1683865158
}
