canonical_name: "m1_sg"
version: 50000000005
apns {
  apn {
    name: "Sunsurf Mobile"
    value: "sunsurf"
    type: DEFAULT
    type: SUPL
  }
  apn {
    name: "M1 MMS(3G)"
    value: "miworld"
    type: MMS
    user: "65"
    password: "user123"
    authtype: 1
    mmsc: "http://mmsgw:8002"
    mmsc_proxy: "172.16.14.10"
    mmsc_proxy_port: "8080"
  }
  apn {
    name: "M1 IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "carrier_volte_available_bool"
    bool_value: false
  }
  config {
    key: "hide_enhanced_4g_lte_bool"
    bool_value: false
  }
}
last_updated {
  seconds: 1688093790
}
