canonical_name: "maxis_my"
version: 50000000004
apns {
  apn {
    name: "Maxis Internet"
    value: "max4g"
    type: DEFAULT
    type: MMS
    type: SUPL
    user: "maxis"
    password: "wap"
    authtype: 1
    mmsc: "http://172.16.74.100:10021/mmsc"
    mmsc_proxy: "202.75.133.49"
    mmsc_proxy_port: "80"
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "carrier_volte_available_bool"
    bool_value: false
  }
}
last_updated {
  seconds: 1688093790
}
