canonical_name: "metropcs_us"
version: 50000000668
apns {
  apn {
    name: "MetroPCS Tethering"
    value: "pcweb.metropcs.com"
    type: DUN
    protocol: IPV4V6
    user_visible: false
  }
  apn {
    name: "MetroPCS"
    value: ""
    type: IA
    protocol: IPV6
    mtu: 1440
    user_visible: false
  }
  apn {
    name: "MetroPCS"
    value: "fast.metropcs.com"
    type: DEFAULT
    type: MMS
    type: SUPL
    type: HIPRI
    bearer_bitmask: "1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|17|20"
    mmsc: "http://metropcs.mmsmvno.com/mms/wapenc"
    protocol: IPV6
    mtu: 1440
    user_editable: false
  }
  apn {
    name: "MetroPCS MMS"
    value: "TMUS"
    type: MMS
    bearer_bitmask: "18"
    mmsc: "http://metropcs.mmsmvno.com/mms/wapenc"
    protocol: IPV6
    roaming_protocol: IPV6
    user_visible: false
  }
  apn {
    name: "MetroPCS IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV6
    mtu: 1440
    user_visible: false
    always_on: true
  }
  apn {
    name: "MetroPCS IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "18"
    protocol: IPV6
    roaming_protocol: IPV6
    mtu: 1440
    user_visible: false
    always_on: true
  }
}
configs {
  config {
    key: "5g_icon_configuration_string"
    text_value: "connected_mmwave:5G,connected:5G,not_restricted_rrc_idle:5G,not_restricted_rrc_con:5G"
  }
  config {
    key: "5g_icon_display_grace_period_string"
    text_value: ""
  }
  config {
    key: "5g_nr_ssrsrp_thresholds_int_array"
    int_array {
      item: -111
      item: -90
      item: -80
      item: -65
    }
  }
  config {
    key: "additional_nr_advanced_bands_int_array"
    int_array {
    }
  }
  config {
    key: "bsf.bsf_server_fqdn_string"
    text_value: "bsf.msg.pc.t-mobile.com"
  }
  config {
    key: "bsf.bsf_server_port_int"
    int_value: 443
  }
  config {
    key: "bsf.bsf_transport_type_int"
    int_value: 3
  }
  config {
    key: "call_composer_picture_server_url_string"
    text_value: ""
  }
  config {
    key: "carrier_certificate_string_array"
    text_array {
      item: "3D1A4BEF6EE7AF7D34D120E7B1AAC0DD245585DE6237CF100F68333AFACFF562:com.tmobile.grsuapp"
      item: "6892793FC413019D2DF609DFED7AF622D0F2D8FCF96EFA7E3FB87EEA34E10B93:com.nuance.nmc.sihome.metropcs,com.metropcs.service.vvm,com.tmobile.metrorbt"
      item: "7B68FD9D4E7610C9CB35FC0C6CC06EA04C6906E3DFA9F48F9A05460AF36BFFFC"
    }
  }
  config {
    key: "carrier_default_data_roaming_enabled_bool"
    bool_value: false
  }
  config {
    key: "carrier_default_wfc_ims_enabled_bool"
    bool_value: false
  }
  config {
    key: "carrier_default_wfc_ims_mode_int"
    int_value: 2
  }
  config {
    key: "carrier_default_wfc_ims_roaming_enabled_bool"
    bool_value: false
  }
  config {
    key: "carrier_default_wfc_ims_roaming_mode_int"
    int_value: 2
  }
  config {
    key: "carrier_ims_gba_required_bool"
    bool_value: true
  }
  config {
    key: "carrier_supports_ss_over_ut_bool"
    bool_value: true
  }
  config {
    key: "carrier_ussd_method_int"
    int_value: 0
  }
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "carrier_vowifi_tty_supported_bool"
    bool_value: false
  }
  config {
    key: "carrier_vt_available_bool"
    bool_value: false
  }
  config {
    key: "carrier_wfc_ims_available_bool"
    bool_value: true
  }
  config {
    key: "data_limit_threshold_bytes_long"
    long_value: -1
  }
  config {
    key: "editable_voicemail_number_setting_bool"
    bool_value: true
  }
  config {
    key: "emergency_number_prefix_string_array"
    text_array {
      item: ""
    }
  }
  config {
    key: "enable_carrier_display_name_resolver_bool"
    bool_value: false
  }
  config {
    key: "enable_nr_advanced_for_roaming_bool"
    bool_value: false
  }
  config {
    key: "gba_ua_tls_cipher_suite_int"
    int_value: 0
  }
  config {
    key: "gsm_roaming_networks_string_array"
    text_array {
    }
  }
  config {
    key: "hide_enhanced_4g_lte_bool"
    bool_value: false
  }
  config {
    key: "hide_tty_hco_vco_with_rtt"
    bool_value: false
  }
  config {
    key: "ignore_rtt_mode_setting_bool"
    bool_value: true
  }
  config {
    key: "ims.enable_presence_capability_exchange_bool"
    bool_value: false
  }
  config {
    key: "ims.enable_presence_publish_bool"
    bool_value: false
  }
  config {
    key: "ims.geolocation_pidf_in_sip_invite_support_int_array"
    int_array {
      item: 3
      item: 1
    }
  }
  config {
    key: "ims.geolocation_pidf_in_sip_register_support_int_array"
    int_array {
      item: 3
      item: 1
    }
  }
  config {
    key: "ims.gruu_enabled_bool"
    bool_value: true
  }
  config {
    key: "ims.ims_user_agent_string"
    text_value: "T-Mobile EPSFB-ePDG-IR94-RTT-ussd #MANUFACTURE#/#MODEL# #BUILD#"
  }
  config {
    key: "ims.request_uri_type_int"
    int_value: 1
  }
  config {
    key: "ims.sip_preferred_transport_int"
    int_value: 1
  }
  config {
    key: "ims_reasoninfo_mapping_string_array"
    text_array {
      item: "510|Call completed elsewhere|1014"
    }
  }
  config {
    key: "imsemergency.emergency_registration_timer_millis_int"
    int_value: 1000
  }
  config {
    key: "imsemergency.retry_emergency_on_ims_pdn_bool"
    bool_value: true
  }
  config {
    key: "imsss.network_initiated_ussd_over_ims_supported_bool"
    bool_value: false
  }
  config {
    key: "imsss.ut_as_server_fqdn_string"
    text_value: "xcap.msg.pc.t-mobile.com"
  }
  config {
    key: "imsss.ut_as_server_port_int"
    int_value: 443
  }
  config {
    key: "imsss.ut_server_based_services_int_array"
    int_array {
      item: 0
      item: 19
      item: 12
      item: 3
      item: 14
      item: 18
      item: 11
      item: 13
      item: 5
      item: 20
      item: 7
      item: 17
      item: 2
      item: 1
      item: 4
      item: 21
      item: 6
      item: 15
      item: 16
      item: 9
      item: 8
    }
  }
  config {
    key: "imsss.ut_terminal_based_services_int_array"
    int_array {
      item: 10
    }
  }
  config {
    key: "imsss.ut_transport_type_int"
    int_value: 3
  }
  config {
    key: "imsvoice.audio_inactivity_call_end_reasons_int_array"
    int_array {
      item: 0
      item: 2
    }
  }
  config {
    key: "imsvoice.audio_rtp_inactivity_timer_millis_int"
    int_value: 30000
  }
  config {
    key: "imsvoice.conference_factory_uri_string"
    text_value: "8881112663@msg.pc.t-mobile.com"
  }
  config {
    key: "imsvoice.dedicated_bearer_wait_timer_millis_int"
    int_value: 20000
  }
  config {
    key: "imsvoice.evs_payload_description_bundle"
    bundle {
      config {
        key: "127"
        bundle {
          config {
            key: "imsvoice.evs_codec_attribute_bitrate_int_array"
            int_array {
              item: 0
              item: 4
            }
          }
          config {
            key: "imsvoice.evs_codec_attribute_ch_aw_recv_int"
            int_value: 2
          }
        }
      }
    }
  }
  config {
    key: "imsvoice.include_caller_id_service_codes_in_sip_invite_bool"
    bool_value: true
  }
  config {
    key: "imsvoice.mo_call_request_timeout_millis_int"
    int_value: 0
  }
  config {
    key: "imsvoice.ringback_timer_millis_int"
    int_value: 128000
  }
  config {
    key: "imsvt.video_as_bandwidth_kbps_int"
    int_value: 560
  }
  config {
    key: "imsvt.video_rs_bandwidth_bps_int"
    int_value: 5200
  }
  config {
    key: "imsvt.video_rtp_dscp_int"
    int_value: 34
  }
  config {
    key: "imswfc.emergency_call_over_emergency_pdn_bool"
    bool_value: false
  }
  config {
    key: "iwlan.diffie_hellman_groups_int_array"
    int_array {
      item: 14
    }
  }
  config {
    key: "iwlan.epdg_address_priority_int_array"
    int_array {
      item: 0
      item: 1
    }
  }
  config {
    key: "iwlan.epdg_plmn_priority_int_array"
    int_array {
      item: 3
      item: 1
    }
  }
  config {
    key: "iwlan.epdg_static_address_string"
    text_value: "epdg.epc.mnc260.mcc310.pub.3gppnetwork.org"
  }
  config {
    key: "iwlan.key_error_policy_config_string"
    text_value: "[{\"ApnName\": \"*\",\"ErrorTypes\": [{\"ErrorType\": \"IKE_PROTOCOL_ERROR_TYPE\",\"ErrorDetails\": [\"10500\"],\"RetryArray\": [\"3600\",\"7200\",\"10800\"],\"UnthrottlingEvents\": [\"APM_ENABLE_EVENT\",\"WIFI_DISABLE_EVENT\",\"WIFI_CALLING_DISABLE_EVENT\"]},{\"ErrorType\": \"IKE_PROTOCOL_ERROR_TYPE\",\"ErrorDetails\": [\"11001\",\"11011\"],\"RetryArray\": [],\"UnthrottlingEvents\": []}]}]"
  }
  config {
    key: "iwlan_handover_policy_string_array"
    text_array {
      item: "source=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN|UNKNOWN, target=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN, type=disallowed, capabilities=EIMS|MMS|XCAP|CBS"
      item: "source=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN|UNKNOWN, target=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN, roaming=true, type=disallowed, capabilities=IMS"
      item: "source=IWLAN|UNKNOWN, target=GERAN|UTRAN, type=disallowed, capabilities=IMS"
      item: "source=GERAN|UTRAN, target=IWLAN, type=disallowed, capabilities=IMS"
      item: "source=EUTRAN|NGRAN|IWLAN, target=EUTRAN|NGRAN|IWLAN, type=allowed, capabilities=IMS"
    }
  }
  config {
    key: "maxImageHeight"
    int_value: 1944
  }
  config {
    key: "maxImageWidth"
    int_value: 2592
  }
  config {
    key: "maxMessageSize"
    int_value: 1048576
  }
  config {
    key: "min_udp_port_4500_nat_timeout_sec_int"
    int_value: 600
  }
  config {
    key: "mmi_two_digit_number_pattern_string_array"
    text_array {
      item: ""
    }
  }
  config {
    key: "mmsCloseConnection"
    bool_value: false
  }
  config {
    key: "mmsRoamingAutoRetrieveByDefault"
    bool_value: true
  }
  config {
    key: "non_roaming_operator_string_array"
    text_array {
    }
  }
  config {
    key: "nr_advanced_threshold_bandwidth_khz_int"
    int_value: 40000
  }
  config {
    key: "prefer_2g_bool"
    bool_value: true
  }
  config {
    key: "preferred_ike_protocol_int"
    int_value: 0
  }
  config {
    key: "qns.idle_eutran_rsrp_int_array"
    int_array {
      item: -109
      item: -114
    }
  }
  config {
    key: "qns.idle_geran_rssi_int_array"
    int_array {
      item: -95
      item: -105
    }
  }
  config {
    key: "qns.idle_ngran_ssrsrp_int_array"
    int_array {
      item: -109
      item: -114
    }
  }
  config {
    key: "qns.idle_utran_ecno_int_array"
    int_array {
      item: -10
      item: -15
    }
  }
  config {
    key: "qns.idle_utran_rscp_int_array"
    int_array {
      item: -100
      item: -110
    }
  }
  config {
    key: "qns.idle_wifi_rssi_int_array"
    int_array {
      item: -70
      item: -80
    }
  }
  config {
    key: "qns.ims_wlan_hysteresis_timer_ms_int_array"
    int_array {
      item: 10000
      item: 10000
      item: 10000
    }
  }
  config {
    key: "qns.ims_wwan_hysteresis_timer_ms_int_array"
    int_array {
      item: 10000
      item: 10000
      item: 10000
    }
  }
  config {
    key: "qns.mms_rat_preference_int"
    int_value: 2
  }
  config {
    key: "qns.video_eutran_rsrp_int_array"
    int_array {
      item: -109
      item: -114
    }
  }
  config {
    key: "qns.video_ngran_ssrsrp_int_array"
    int_array {
      item: -109
      item: -114
    }
  }
  config {
    key: "qns.video_wifi_rssi_int_array"
    int_array {
      item: -70
      item: -80
    }
  }
  config {
    key: "qns.voice_eutran_rsrp_int_array"
    int_array {
      item: -109
      item: -114
    }
  }
  config {
    key: "qns.voice_ngran_ssrsrp_int_array"
    int_array {
      item: -109
      item: -114
    }
  }
  config {
    key: "qns.voice_wifi_rssi_int_array"
    int_array {
      item: -70
      item: -80
    }
  }
  config {
    key: "read_only_apn_types_string_array"
    text_array {
      item: "dun"
    }
  }
  config {
    key: "recipientLimit"
    int_value: 2147483647
  }
  config {
    key: "rtt_downgrade_supported_bool"
    bool_value: false
  }
  config {
    key: "rtt_supported_bool"
    bool_value: true
  }
  config {
    key: "show_data_connected_roaming_notification"
    bool_value: false
  }
  config {
    key: "smsToMmsTextThreshold"
    int_value: -1
  }
  config {
    key: "support_video_conference_call_bool"
    bool_value: false
  }
  config {
    key: "use_wfc_home_network_mode_in_roaming_network_bool"
    bool_value: true
  }
  config {
    key: "volte_replacement_rat_int"
    int_value: 3
  }
  config {
    key: "wfc_carrier_name_override_by_pnn_bool"
    bool_value: false
  }
  config {
    key: "wfc_operator_error_codes_string_array"
    text_array {
      item: "REG09|0"
    }
  }
  config {
    key: "wfc_spn_format_idx_int"
    int_value: 1
  }
  config {
    key: "wifi.avoid_5ghz_softap_for_laa_bool"
    bool_value: false
  }
  config {
    key: "wifi.avoid_5ghz_wifi_direct_for_laa_bool"
    bool_value: false
  }
  config {
    key: "wifi.carrier_profiles_version_int"
    int_value: -1
  }
  config {
    key: "wifi.passpoint_profiles_string_array"
    text_array {
    }
  }
}
last_updated {
  seconds: 1688093790
}
