canonical_name: "orange_gp"
version: 50000000001
apns {
  apn {
    name: "Orange World Cara\303\257be"
    value: "orangeweb"
    type: DEFAULT
    type: SUPL
    user_editable: false
  }
  apn {
    name: "Orange MMS Cara\303\257be"
    value: "orangewap"
    type: MMS
    user: "orange"
    password: "orange"
    authtype: 1
    mmsc: "http://mms.orangecaraibe.com/servlets/mms"
    mmsc_proxy: "10.0.0.10"
    mmsc_proxy_port: "8080"
    user_editable: false
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "carrier_certificate_string_array"
    text_array {
      item: "b67affcda89e3193b1595036d7c6cdbe22be5ca24c9f6cf93fc6b48f91d7310d:com.orange.caraibe.orangeetmoicaraibe,com.orange.caraibe.soshcaraibe,com.orange.update,com.orange.phone"
    }
  }
  config {
    key: "config_plans_package_override_string"
    text_value: "com.orange.caraibe.orangeetmoicaraibe"
  }
  config {
    key: "non_roaming_operator_string_array"
    text_array {
      item: "20801"
      item: "20815"
    }
  }
}
last_updated {
  seconds: 1679645347
}
