canonical_name: "orange_re"
version: 50000000004
apns {
  apn {
    name: "Orange World re"
    value: "orangerun"
    type: DEFAULT
    type: SUPL
    user: "orange"
    password: "orange"
  }
  apn {
    name: "Orange MMS R\303\251union"
    value: "orangerun.acte"
    type: MMS
    user: "orange"
    password: "orange"
    mmsc: "http://mms.orange.re"
    mmsc_proxy: "192.168.10.200"
    mmsc_proxy_port: "8080"
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|18|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "wfc_spn_format_idx_int"
    int_value: 1
  }
}
last_updated {
  seconds: 1688093790
}
