canonical_name: "orange_sk"
version: 50000000001
apns {
  apn {
    name: "Orange SK"
    value: "internet"
    type: DEFAULT
  }
  apn {
    name: "Orange SK MMS"
    value: "mms"
    type: MMS
    user: "wap"
    password: "wap"
    authtype: 1
    mmsc: "http://imms.orange.sk"
    mmsc_proxy: "213.151.208.145"
    mmsc_proxy_port: "8799"
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "carrier_certificate_string_array"
    text_array {
      item: "B67AFFCDA89E3193B1595036D7C6CDBE22BE5CA24C9F6CF93FC6B48F91D7310D:com.orange.phone,com.orange.update"
      item: "6AE20C0E468B99D1F3D35A7CB959AB64CBCEE802461CE9D38F099C90D245BFBF:sk.orange.android.orangego"
    }
  }
  config {
    key: "config_plans_package_override_string"
    text_value: "sk.orange.android.orangego"
  }
  config {
    key: "show_4g_for_lte_data_icon_bool"
    bool_value: true
  }
}
last_updated {
  seconds: 1679645347
}
