canonical_name: "partner_il"
version: 50000000003
apns {
  apn {
    name: "3G Portal"
    value: "uwap.orange.co.il"
    type: DEFAULT
    type: MMS
    type: SUPL
    mmsc: "http://192.168.220.15/servlets/mms"
    mmsc_proxy: "192.118.11.55"
    mmsc_proxy_port: "8080"
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
}
last_updated {
  seconds: 1688093790
}
