canonical_name: "plus_pl"
version: 50000000001
apns {
  apn {
    name: "Plus Internet"
    value: "plus"
    type: DEFAULT
    type: SUPL
  }
  apn {
    name: "Plus MMS"
    value: "mms"
    type: MMS
    mmsc: "http://mms.plusgsm.pl:8002"
    mmsc_proxy: "212.2.96.16"
    mmsc_proxy_port: "8080"
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "carrier_certificate_string_array"
    text_array {
      item: "e3266a6cf0b5e2ae1cf2727f321441e4e07c5adcf328296ed23b819760fa61e1:com.n7mobile.plusapps,com.n7mobile.pluswidget"
      item: "8a825148825f2c8502caad446b5582793b0cfda1cd220581ea80b11ad833c55e:com.n7mobile.plusapps,com.n7mobile.pluswidget"
    }
  }
}
last_updated {
  seconds: 1679645347
}
