canonical_name: "sky_gb"
version: 50000000003
apns {
  apn {
    name: "SKY MMS"
    value: "mms.mobile.sky"
    type: MMS
    mmsc: "http://185.110.178.96:38090/was"
    mmsc_proxy: "185.110.178.97"
    mmsc_proxy_port: "9028"
  }
  apn {
    name: "SKY Internet"
    value: "mobile.sky"
    type: DEFAULT
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "non_roaming_operator_string_array"
    text_array {
      item: "23410"
      item: "23426"
      item: "23430"
      item: "23431"
      item: "23432"
      item: "23433"
      item: "23434"
      item: "23486"
    }
  }
  config {
    key: "prefer_2g_bool"
    bool_value: false
  }
  config {
    key: "sim_country_iso_override_string"
    text_value: "gb"
  }
}
last_updated {
  seconds: 1688093790
}
