canonical_name: "strata_us"
version: 50000000003
apns {
  apn {
    name: "Rinainternet"
    value: "rinainternet.rinawireless.com"
    type: DEFAULT
    type: MMS
    type: DUN
    mmsc: "http://mms.rinawireless.com"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_editable: false
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
}
last_updated {
  seconds: 1688093790
}
