canonical_name: "tango_us"
version: 50000000003
apns {
  apn {
    name: "globaldata"
    value: "globaldata"
    type: DEFAULT
    type: IA
    type: SUPL
    type: MMS
    type: FOTA
    type: HIPRI
    mmsc: "http://mms.mobileuc.global/"
    mmsc_proxy: "37.18.129.98"
    mmsc_proxy_port: "8008"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_editable: false
  }
  apn {
    name: "globalhotspot"
    value: "globalhotspot"
    type: DUN
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_editable: false
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
}
last_updated {
  seconds: 1688093790
}
