canonical_name: "viaero_us"
version: 50000000003
apns {
  apn {
    name: "Viaero Connect"
    value: "internet.vedge.com"
    type: DEFAULT
    type: SUPL
  }
  apn {
    name: "Viaero MMS"
    value: "mms"
    type: MMS
    mmsc: "http://mms.viaero.com"
    mmsc_proxy: "10.168.3.23"
    mmsc_proxy_port: "9401"
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "maxImageHeight"
    int_value: 1944
  }
  config {
    key: "maxImageWidth"
    int_value: 2592
  }
  config {
    key: "maxMessageSize"
    int_value: 1048576
  }
}
last_updated {
  seconds: 1688093790
}
