canonical_name: "yettel_hu"
version: 50000000003
apns {
  apn {
    name: "Telenor MMS"
    value: "mms"
    type: MMS
    mmsc: "http://mmsc.telenor.hu/"
    mmsc_proxy: "84.225.255.1"
    mmsc_proxy_port: "8080"
  }
  apn {
    name: "Telenor Online"
    value: "online"
    type: DEFAULT
    type: SUPL
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "show_4g_for_lte_data_icon_bool"
    bool_value: true
  }
}
last_updated {
  seconds: 1688093790
}
