canonical_name: "bite_lv"
version: 56000000010
apns {
  apn {
    name: "Bite LV Internet"
    value: "internet"
    type: DEFAULT
    type: SUPL
  }
  apn {
    name: "Bite LV MMS"
    value: "mms"
    type: MMS
    user: "mms@mms"
    password: "mms"
    authtype: 1
    mmsc: "http://mmsc/servlets/mms"
    mmsc_proxy: "192.168.150.2"
    mmsc_proxy_port: "8080"
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|18|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
  apn {
    name: "hos"
    value: "hos"
    type: XCAP
    protocol: IPV4V6
    roaming_protocol: IPV4V6
  }
}
configs {
  config {
    key: "carrier_default_wfc_ims_enabled_bool"
    bool_value: true
  }
  config {
    key: "carrier_default_wfc_ims_mode_int"
    int_value: 1
  }
  config {
    key: "carrier_default_wfc_ims_roaming_enabled_bool"
    bool_value: true
  }
  config {
    key: "carrier_default_wfc_ims_roaming_mode_int"
    int_value: 1
  }
  config {
    key: "carrier_supports_ss_over_ut_bool"
    bool_value: true
  }
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "carrier_wfc_ims_available_bool"
    bool_value: true
  }
  config {
    key: "ims_reasoninfo_mapping_string_array"
    text_array {
      item: "338|busy everywhere|1017"
    }
  }
  config {
    key: "imsemergency.emergency_over_ims_supported_rats_int_array"
    int_array {
      item: 3
    }
  }
  config {
    key: "imsss.xcap_over_ut_supported_rats_int_array"
    int_array {
      item: 6
      item: 3
      item: 5
      item: 1
      item: 2
    }
  }
  config {
    key: "imsvoice.audio_codec_capability_payload_types_bundle"
    bundle {
      config {
        key: "imsvoice.amrnb_payload_type_int_array"
        int_array {
          item: 98
          item: 103
        }
      }
      config {
        key: "imsvoice.amrwb_payload_type_int_array"
        int_array {
          item: 100
          item: 105
        }
      }
      config {
        key: "imsvoice.dtmfnb_payload_type_int_array"
        int_array {
          item: 97
        }
      }
      config {
        key: "imsvoice.dtmfwb_payload_type_int_array"
        int_array {
          item: 96
        }
      }
    }
  }
  config {
    key: "iwlan.diffie_hellman_groups_int_array"
    int_array {
      item: 16
    }
  }
  config {
    key: "iwlan.ike_remote_id_type_int"
    int_value: 11
  }
  config {
    key: "iwlan_handover_policy_string_array"
    text_array {
      item: "source=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN|UNKNOWN, target=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN, type=disallowed, capabilities=EIMS|MMS|XCAP|CBS"
      item: "source=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN|UNKNOWN, target=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN, roaming=true, type=disallowed, capabilities=IMS"
      item: "source=IWLAN|UNKNOWN, target=GERAN|UTRAN, type=disallowed, capabilities=IMS"
      item: "source=GERAN|UTRAN, target=IWLAN, type=disallowed, capabilities=IMS"
      item: "source=EUTRAN|NGRAN|IWLAN, target=EUTRAN|NGRAN|IWLAN, type=allowed, capabilities=IMS"
    }
  }
  config {
    key: "wfc_spn_format_idx_int"
    int_value: 1
  }
}
last_updated {
  seconds: 1709690423
}
