canonical_name: "orange_es"
version: 56000000014
apns {
  apn {
    name: "Orange Internet M\303\263vil"
    value: ""
    type: IA
  }
  apn {
    name: "Orange Internet M\303\263vil"
    value: "orangeworld"
    type: DEFAULT
    user: "orange"
    password: "orange"
    authtype: 1
    user_editable: false
  }
  apn {
    name: "Orange Es IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|18|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    mtu: 1400
    user_visible: false
  }
  apn {
    name: "Orange MMS"
    value: "orangemms"
    type: MMS
    user: "orange"
    password: "orange"
    authtype: 1
    mmsc: "http://mms.orange.es"
    mmsc_proxy: "172.22.188.25"
    mmsc_proxy_port: "8080"
    user_editable: false
  }
  apn {
    name: "Orange Internet PC"
    value: "internet"
    type: DUN
    user: "orange"
    password: "orange"
    authtype: 0
    user_editable: false
  }
}
configs {
  config {
    key: "carrier_allow_transfer_ims_call_bool"
    bool_value: true
  }
  config {
    key: "carrier_certificate_string_array"
    text_array {
      item: "B67AFFCDA89E3193B1595036D7C6CDBE22BE5CA24C9F6CF93FC6B48F91D7310D:com.orange.phone,com.orange.miorange,com.orange.bluu.jazztel,com.orange.miamena,com.orange.update"
    }
  }
  config {
    key: "carrier_default_wfc_ims_roaming_enabled_bool"
    bool_value: true
  }
  config {
    key: "carrier_nr_availabilities_int_array"
    int_array {
      item: 1
      item: 2
    }
  }
  config {
    key: "carrier_supports_ss_over_ut_bool"
    bool_value: true
  }
  config {
    key: "carrier_ussd_method_int"
    int_value: 2
  }
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "carrier_wfc_ims_available_bool"
    bool_value: true
  }
  config {
    key: "config_plans_package_override_string"
    text_value: "com.orange.miorange"
  }
  config {
    key: "default_vm_number_string"
    text_value: "242"
  }
  config {
    key: "display_hd_plus_icon_bool"
    bool_value: true
  }
  config {
    key: "hide_enhanced_4g_lte_bool"
    bool_value: true
  }
  config {
    key: "hide_redundant_options_menu_on_stk_input_screen_bool"
    bool_value: true
  }
  config {
    key: "ims.ims_user_agent_string"
    text_value: "#MANUFACTURE# #MODEL# Android #AV# #BUILD# EU02369"
  }
  config {
    key: "ims.ipv4_sip_mtu_size_cellular_int"
    int_value: 1300
  }
  config {
    key: "ims.ipv6_sip_mtu_size_cellular_int"
    int_value: 1300
  }
  config {
    key: "ims.request_uri_type_int"
    int_value: 1
  }
  config {
    key: "ims_reasoninfo_mapping_string_array"
    text_array {
      item: "510|Call completed elsewhere|1014"
      item: "*|Call is dropped due to Wi-Fi signal is degraded|1407"
    }
  }
  config {
    key: "imssms.sms_over_ims_supported_rats_int_array"
    int_array {
    }
  }
  config {
    key: "imsss.network_initiated_ussd_over_ims_supported_bool"
    bool_value: false
  }
  config {
    key: "imsss.ut_server_based_services_int_array"
    int_array {
    }
  }
  config {
    key: "imsss.xcap_over_ut_supported_rats_int_array"
    int_array {
    }
  }
  config {
    key: "imsvoice.amrnb_payload_description_bundle"
    bundle {
      config {
        key: "100"
        bundle {
          config {
            key: "imsvoice.amr_codec_attribute_modeset_int_array"
            int_array {
              item: 0
              item: 3
              item: 6
            }
          }
        }
      }
      config {
        key: "101"
        bundle {
          config {
            key: "imsvoice.amr_codec_attribute_modeset_int_array"
            int_array {
              item: 0
              item: 3
              item: 6
            }
          }
          config {
            key: "imsvoice.amr_codec_attribute_payload_format_int"
            int_value: 1
          }
        }
      }
    }
  }
  config {
    key: "imsvoice.amrwb_payload_description_bundle"
    bundle {
      config {
        key: "99"
        bundle {
          config {
            key: "imsvoice.amr_codec_attribute_payload_format_int"
            int_value: 1
          }
        }
      }
    }
  }
  config {
    key: "imsvoice.audio_codec_capability_payload_types_bundle"
    bundle {
      config {
        key: "imsvoice.amrnb_payload_type_int_array"
        int_array {
          item: 100
          item: 101
        }
      }
      config {
        key: "imsvoice.amrwb_payload_type_int_array"
        int_array {
          item: 98
          item: 99
        }
      }
      config {
        key: "imsvoice.dtmfnb_payload_type_int_array"
        int_array {
          item: 106
        }
      }
      config {
        key: "imsvoice.dtmfwb_payload_type_int_array"
        int_array {
          item: 105
        }
      }
      config {
        key: "imsvoice.evs_payload_type_int_array"
        int_array {
          item: 96
          item: 97
        }
      }
    }
  }
  config {
    key: "imsvoice.evs_payload_description_bundle"
    bundle {
      config {
        key: "96"
        bundle {
          config {
            key: "imsvoice.evs_codec_attribute_bandwidth_int"
            int_value: 2
          }
          config {
            key: "imsvoice.evs_codec_attribute_bitrate_int_array"
            int_array {
              item: 3
              item: 6
            }
          }
        }
      }
      config {
        key: "97"
        bundle {
          config {
            key: "imsvoice.evs_codec_attribute_bitrate_int_array"
            int_array {
              item: 0
              item: 6
            }
          }
        }
      }
    }
  }
  config {
    key: "imsvoice.minimum_session_expires_timer_sec_int"
    int_value: 600
  }
  config {
    key: "imsvoice.mo_call_request_timeout_millis_int"
    int_value: 3000
  }
  config {
    key: "imsvoice.oip_source_from_header_bool"
    bool_value: true
  }
  config {
    key: "imsvoice.ringback_timer_millis_int"
    int_value: 60000
  }
  config {
    key: "imsvoice.ringing_timer_millis_int"
    int_value: 60000
  }
  config {
    key: "iwlan.add_ke_to_child_session_rekey_bool"
    bool_value: true
  }
  config {
    key: "iwlan.child_sa_rekey_hard_timer_sec_int"
    int_value: 64900
  }
  config {
    key: "iwlan.child_sa_rekey_soft_timer_sec_int"
    int_value: 64800
  }
  config {
    key: "iwlan.diffie_hellman_groups_int_array"
    int_array {
      item: 14
      item: 5
    }
  }
  config {
    key: "iwlan.ike_rekey_hard_timer_in_sec"
    int_value: 64900
  }
  config {
    key: "iwlan.ike_rekey_soft_timer_sec_int"
    int_value: 64800
  }
  config {
    key: "iwlan.key_error_policy_config_string"
    text_value: "[{\"ApnName\": \"*\",\"ErrorTypes\": [{\"ErrorType\": \"IKE_PROTOCOL_ERROR_TYPE\",\"ErrorDetails\": [\"*\"],\"RetryArray\": [\"4\", \"8\", \"43200\", \"-1\"],\"UnthrottlingEvents\": [\"WIFI_DISABLE_EVENT\"]}, {\"ErrorType\": \"IKE_PROTOCOL_ERROR_TYPE\",\"ErrorDetails\": [\"9000\", \"11001\", \"11011\"],\"RetryArray\": [\"43200\"],\"UnthrottlingEvents\": [\"APM_ENABLE_EVENT\", \"WIFI_DISABLE_EVENT\", \"WIFI_AP_CHANGED_EVENT\", \"WIFI_CALLING_DISABLE_EVENT\"]}, {\"ErrorType\": \"IKE_PROTOCOL_ERROR_TYPE\",\"ErrorDetails\": [\"9006\"],\"RetryArray\": [\"86400\"],\"UnthrottlingEvents\": [\"APM_ENABLE_EVENT\", \"WIFI_DISABLE_EVENT\", \"WIFI_AP_CHANGED_EVENT\", \"WIFI_CALLING_DISABLE_EVENT\"]}, {\"ErrorType\": \"IKE_PROTOCOL_ERROR_TYPE\",\"ErrorDetails\": [\"36\"],\"RetryArray\": [\"4\", \"8\", \"43200\", \"-1\"],\"UnthrottlingEvents\": [\"WIFI_DISABLE_EVENT\"],\"HandoverAttemptCount\": \"3\"}]}]"
  }
  config {
    key: "maxImageHeight"
    int_value: 1944
  }
  config {
    key: "maxImageWidth"
    int_value: 2592
  }
  config {
    key: "maxMessageSize"
    int_value: 1048576
  }
  config {
    key: "qns.idle_wifi_rssi_int_array"
    int_array {
      item: -65
      item: -75
    }
  }
  config {
    key: "qns.idle_wifi_rssi_without_cellular_int_array"
    int_array {
      item: -85
      item: -90
    }
  }
  config {
    key: "qns.voice_wifi_rssi_int_array"
    int_array {
      item: -65
      item: -75
    }
  }
  config {
    key: "qns.voice_wifi_rssi_without_cellular_int_array"
    int_array {
      item: -85
      item: -90
    }
  }
  config {
    key: "qns.xcap_transport_type_int"
    int_value: 0
  }
  config {
    key: "show_4g_for_lte_data_icon_bool"
    bool_value: true
  }
  config {
    key: "unloggable_numbers_string_array"
    text_array {
      item: "900018018"
      item: "016"
      item: "021"
      item: "024"
      item: "028"
      item: "116000"
      item: "116111"
      item: "900202010"
    }
  }
  config {
    key: "use_wfc_home_network_mode_in_roaming_network_bool"
    bool_value: true
  }
  config {
    key: "wfc_spn_format_idx_int"
    int_value: 1
  }
}
last_updated {
  seconds: 1709519152
}
