canonical_name: "salt_li"
version: 56000000001
apns {
  apn {
    name: "Internet"
    value: "internet-ofl"
    type: DEFAULT
    type: SUPL
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_editable: false
  }
}
configs {
  config {
    key: "enabledMMS"
    bool_value: false
  }
}
last_updated {
  seconds: 1708520788
}
