canonical_name: "vodafone_qa"
version: 56000000005
apns {
  apn {
    name: "Voda internet"
    value: "web.vodafone.com.qa"
    type: DEFAULT
    type: SUPL
  }
  apn {
    name: "VFQ MMS"
    value: "vodafone.com.qa"
    type: MMS
    mmsc: "http://mms.vodafone.com.qa/mmsc"
    mmsc_proxy: "10.101.97.102"
    mmsc_proxy_port: "80"
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
  apn {
    name: "XCAP"
    value: "xcap"
    type: XCAP
    protocol: IPV4V6
    roaming_protocol: IPV4V6
  }
}
configs {
  config {
    key: "additional_settings_caller_id_visibility_bool"
    bool_value: false
  }
  config {
    key: "bsf.bsf_server_fqdn_string"
    text_value: "bsf.ims.mnc002.mcc427.pub.3gppnetwork.org"
  }
  config {
    key: "carrier_supports_ss_over_ut_bool"
    bool_value: true
  }
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "imsemergency.emergency_over_ims_supported_rats_int_array"
    int_array {
      item: 3
    }
  }
  config {
    key: "imsss.ut_as_server_fqdn_string"
    text_value: "xcap.ims.mnc002.mcc427.pub.3gppnetwork.org"
  }
  config {
    key: "imsvoice.audio_codec_capability_payload_types_bundle"
    bundle {
      config {
        key: "imsvoice.amrnb_payload_type_int_array"
        int_array {
          item: 98
          item: 103
        }
      }
      config {
        key: "imsvoice.amrwb_payload_type_int_array"
        int_array {
          item: 100
          item: 105
        }
      }
      config {
        key: "imsvoice.dtmfnb_payload_type_int_array"
        int_array {
          item: 97
        }
      }
      config {
        key: "imsvoice.dtmfwb_payload_type_int_array"
        int_array {
          item: 96
        }
      }
    }
  }
}
last_updated {
  seconds: 1709116024
}
