canonical_name: "48_ie"
version: 62000000001
apns {
  apn {
    name: "48 Internet"
    value: "48months.liffeytelecom.com"
    type: DEFAULT
    type: MMS
    type: SUPL
    user: "User"
    authtype: 1
    mmsc: "http://mmc1/servlets/mms"
    mmsc_proxy: "10.1.11.19"
    mmsc_proxy_port: "8080"
  }
}
configs {
}
last_updated {
  seconds: 1724912472
}
