canonical_name: "lum_ca"
version: 56000000004
apns {
  apn {
    name: "Lum"
    value: "pda.stm.sk.ca"
    type: DEFAULT
    type: MMS
    type: SUPL
    type: XCAP
    mmsc: "http://mms.sasktel.com/"
    mmsc_proxy: "mig.sasktel.com"
    mmsc_proxy_port: "80"
    protocol: IPV4V6
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|18|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "5g_icon_configuration_string"
    text_value: "connected_mmwave:5G_Plus,connected:5G,not_restricted_rrc_idle:5G,not_restricted_rrc_con:5G"
  }
  config {
    key: "additional_nr_advanced_bands_int_array"
    int_array {
      item: 78
    }
  }
  config {
    key: "bsf.bsf_server_fqdn_string"
    text_value: "bsf.ims.sasktel.com"
  }
  config {
    key: "bsf.bsf_server_port_int"
    int_value: 443
  }
  config {
    key: "bsf.bsf_transport_type_int"
    int_value: 3
  }
  config {
    key: "carrier_default_wfc_ims_mode_int"
    int_value: 1
  }
  config {
    key: "carrier_nr_availabilities_int_array"
    int_array {
      item: 1
    }
  }
  config {
    key: "carrier_supports_ss_over_ut_bool"
    bool_value: true
  }
  config {
    key: "carrier_ussd_method_int"
    int_value: 1
  }
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "carrier_wfc_ims_available_bool"
    bool_value: true
  }
  config {
    key: "enable_nr_advanced_for_roaming_bool"
    bool_value: false
  }
  config {
    key: "hide_enhanced_4g_lte_bool"
    bool_value: true
  }
  config {
    key: "ims.gruu_enabled_bool"
    bool_value: true
  }
  config {
    key: "ims.phone_context_domain_name_string"
    text_value: "ims.sasktel.com"
  }
  config {
    key: "ims.registration_expiry_timer_sec_int"
    int_value: 86400
  }
  config {
    key: "ims.registration_subscribe_expiry_timer_sec_int"
    int_value: 43200
  }
  config {
    key: "imsemergency.emergency_over_ims_supported_rats_int_array"
    int_array {
      item: 3
    }
  }
  config {
    key: "imsemergency.emergency_registration_timer_millis_int"
    int_value: 10000
  }
  config {
    key: "imsserviceentitlement.entitlement_server_url_string"
    text_value: "https://aes.mnc780.mcc302.pub.3gppnetwork.org"
  }
  config {
    key: "imsserviceentitlement.show_vowifi_webview_bool"
    bool_value: true
  }
  config {
    key: "imsss.ut_as_server_fqdn_string"
    text_value: "naf.ims.sasktel.com"
  }
  config {
    key: "imsss.ut_as_server_port_int"
    int_value: 443
  }
  config {
    key: "imsss.ut_transport_type_int"
    int_value: 3
  }
  config {
    key: "imsss.xcap_over_ut_supported_rats_int_array"
    int_array {
      item: 6
      item: 3
      item: 5
      item: 1
      item: 2
    }
  }
  config {
    key: "imsvoice.audio_codec_capability_payload_types_bundle"
    bundle {
      config {
        key: "imsvoice.amrnb_payload_type_int_array"
        int_array {
          item: 98
          item: 103
        }
      }
      config {
        key: "imsvoice.amrwb_payload_type_int_array"
        int_array {
          item: 100
          item: 105
        }
      }
      config {
        key: "imsvoice.dtmfnb_payload_type_int_array"
        int_array {
          item: 97
        }
      }
      config {
        key: "imsvoice.dtmfwb_payload_type_int_array"
        int_array {
          item: 96
        }
      }
    }
  }
  config {
    key: "imsvoice.conference_factory_uri_string"
    text_value: "conference@ibc.sasktel.com"
  }
  config {
    key: "imsvoice.conference_subscribe_type_int"
    int_value: 0
  }
  config {
    key: "imsvoice.ringback_timer_millis_int"
    int_value: 182000
  }
  config {
    key: "imsvoice.ringing_timer_millis_int"
    int_value: 180000
  }
  config {
    key: "imsvoice.session_expires_timer_sec_int"
    int_value: 3600
  }
  config {
    key: "imsvoice.srvcc_type_int_array"
    int_array {
      item: 0
      item: 3
    }
  }
  config {
    key: "iwlan.child_sa_rekey_hard_timer_sec_int"
    int_value: 28800
  }
  config {
    key: "iwlan.dpd_timer_sec_int"
    int_value: 60
  }
  config {
    key: "iwlan.ike_rekey_hard_timer_in_sec"
    int_value: 86400
  }
  config {
    key: "maxImageHeight"
    int_value: 1944
  }
  config {
    key: "maxImageWidth"
    int_value: 2592
  }
  config {
    key: "maxMessageSize"
    int_value: 614400
  }
  config {
    key: "non_roaming_operator_string_array"
    text_array {
      item: "302"
    }
  }
  config {
    key: "qns.condition_rove_in_idle_wifi_pref_home_string_array"
    text_array {
      item: "Condition:WIFI_GOOD"
    }
  }
  config {
    key: "qns.condition_rove_in_idle_wifi_pref_roam_string_array"
    text_array {
      item: "Condition:WIFI_GOOD"
    }
  }
  config {
    key: "qns.condition_rove_out_idle_wifi_pref_home_string_array"
    text_array {
      item: "Condition:WIFI_BAD"
    }
  }
  config {
    key: "qns.condition_rove_out_idle_wifi_pref_roam_string_array"
    text_array {
      item: "Condition:WIFI_BAD"
    }
  }
  config {
    key: "qns.override_cell_pref_to_ims_pref_home"
    bool_value: true
  }
  config {
    key: "sim_country_iso_override_string"
    text_value: "ca"
  }
  config {
    key: "wfc_emergency_address_carrier_app_string"
    text_value: "com.android.imsserviceentitlement/.WfcActivationActivity"
  }
  config {
    key: "wfc_spn_format_idx_int"
    int_value: 1
  }
  config {
    key: "wifi.carrier_profiles_version_int"
    int_value: 1
  }
  config {
    key: "wifi.network_profiles_string_array"
    text_array {
      item: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><WifiNetwork><SSID>SaskTel Select Wi-Fi 1</SSID><Credential><SIM><EAPType>23</EAPType></SIM></Credential></WifiNetwork>"
    }
  }
}
last_updated {
  seconds: 1707895823
}
