canonical_name: "mobily_sa"
version: 56000000005
apns {
  apn {
    name: "Mobily WEB"
    value: "web1"
    type: DEFAULT
    type: SUPL
  }
  apn {
    name: "Mobily prepaid - GPRS"
    value: "wap2"
    type: DEFAULT
    type: SUPL
    proxy: "10.3.2.133"
    port: "8080"
  }
  apn {
    name: "Mobily postpaid - GPRS"
    value: "wap1"
    type: DEFAULT
    type: SUPL
    proxy: "10.3.2.133"
    port: "8080"
  }
  apn {
    name: "Mobily WEB 2"
    value: "web2"
    type: DEFAULT
    type: SUPL
  }
  apn {
    name: "Mobily MMS Postpaid"
    value: "mms1"
    type: MMS
    mmsc: "http://10.3.3.133:9090/was"
    mmsc_proxy: "10.3.2.133"
    mmsc_proxy_port: "8080"
  }
  apn {
    name: "Mobily MMS Prepaid"
    value: "mms2"
    type: MMS
    mmsc: "http://10.3.3.133:9090/was"
    mmsc_proxy: "10.3.2.133"
    mmsc_proxy_port: "8080"
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|18|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "carrier_wfc_ims_available_bool"
    bool_value: true
  }
  config {
    key: "imsemergency.emergency_over_ims_supported_rats_int_array"
    int_array {
      item: 3
    }
  }
  config {
    key: "imsss.xcap_over_ut_supported_rats_int_array"
    int_array {
    }
  }
  config {
    key: "imsvoice.audio_codec_capability_payload_types_bundle"
    bundle {
      config {
        key: "imsvoice.amrnb_payload_type_int_array"
        int_array {
          item: 98
          item: 103
        }
      }
      config {
        key: "imsvoice.amrwb_payload_type_int_array"
        int_array {
          item: 100
          item: 105
        }
      }
      config {
        key: "imsvoice.dtmfnb_payload_type_int_array"
        int_array {
          item: 97
        }
      }
      config {
        key: "imsvoice.dtmfwb_payload_type_int_array"
        int_array {
          item: 96
        }
      }
    }
  }
  config {
    key: "iwlan.epdg_address_priority_int_array"
    int_array {
      item: 0
    }
  }
  config {
    key: "iwlan.epdg_static_address_string"
    text_value: "epdg.mobily.com.sa"
  }
  config {
    key: "qns.support_wfc_during_airplane_mode_bool"
    bool_value: false
  }
  config {
    key: "wfc_spn_format_idx_int"
    int_value: 1
  }
}
last_updated {
  seconds: 1706100361
}
