canonical_name: "movistar_mx"
version: 56000000002
apns {
  apn {
    name: "Movistar INTERNET"
    value: "internet.movistar.mx"
    type: DEFAULT
    type: SUPL
    user: "movistar"
    password: "movistar"
    authtype: 1
  }
  apn {
    name: "Movistar MMS"
    value: "mms.movistar.mx"
    type: MMS
    user: "movistar"
    password: "movistar"
    authtype: 1
    mmsc: "http://mms.movistar.mx"
    mmsc_proxy: "10.2.20.1"
    mmsc_proxy_port: "80"
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
  apn {
    name: "XCAP"
    value: "xcap"
    type: XCAP
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "bsf.bsf_server_fqdn_string"
    text_value: "bsf.ims.mnc030.mcc334.pub.3gppnetwork.org"
  }
  config {
    key: "bsf.bsf_server_port_int"
    int_value: 8080
  }
  config {
    key: "carrier_nr_availabilities_int_array"
    int_array {
      item: 1
    }
  }
  config {
    key: "carrier_supports_ss_over_ut_bool"
    bool_value: true
  }
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "imsss.ut_as_server_fqdn_string"
    text_value: "naf.ims.mnc030.mcc334.pub.3gppnetwork.org"
  }
  config {
    key: "imsss.ut_as_server_port_int"
    int_value: 8090
  }
  config {
    key: "imsss.xcap_over_ut_supported_rats_int_array"
    int_array {
      item: 6
      item: 3
    }
  }
  config {
    key: "imsvoice.conference_factory_uri_string"
    text_value: "conference@factory.ims.movistar.mx"
  }
}
last_updated {
  seconds: 1709690405
}
