canonical_name: "salt_li"
version: 60000000004
apns {
  apn {
    name: "Internet"
    value: "internet-ofl"
    type: DEFAULT
    type: SUPL
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_editable: false
  }
}
configs {
  config {
    key: "carrier_nr_availabilities_int_array"
    int_array {
      item: 1
    }
  }
  config {
    key: "enabledMMS"
    bool_value: false
  }
}
last_updated {
  seconds: 1722173359
}
