canonical_name: "giffgaff_gb"
version: 56000000004
apns {
  apn {
    name: "giffgaff"
    value: "giffgaff.com"
    type: DEFAULT
    type: DUN
    type: MMS
    type: SUPL
    type: HIPRI
    type: XCAP
    user: "giffgaff"
    password: "password"
    mmsc: "http://mmsc.mediamessaging.co.uk:8002"
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|18|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "carrier_default_wfc_ims_enabled_bool"
    bool_value: true
  }
  config {
    key: "carrier_default_wfc_ims_mode_int"
    int_value: 1
  }
  config {
    key: "carrier_supports_ss_over_ut_bool"
    bool_value: true
  }
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "carrier_wfc_ims_available_bool"
    bool_value: true
  }
  config {
    key: "default_vm_number_string"
    text_value: "443"
  }
  config {
    key: "hide_lte_plus_data_icon_bool"
    bool_value: false
  }
  config {
    key: "iwlan.diffie_hellman_groups_int_array"
    int_array {
      item: 14
    }
  }
  config {
    key: "non_roaming_operator_string_array"
    text_array {
      item: "23420"
      item: "23426"
      item: "23430"
      item: "23431"
      item: "23432"
      item: "23433"
      item: "23434"
      item: "23486"
    }
  }
  config {
    key: "prefer_2g_bool"
    bool_value: false
  }
  config {
    key: "radio_restart_failure_causes_int_array"
    int_array {
      item: 55
    }
  }
  config {
    key: "read_only_apn_types_string_array"
    text_array {
    }
  }
  config {
    key: "show_4g_for_lte_data_icon_bool"
    bool_value: true
  }
  config {
    key: "show_wifi_calling_icon_in_status_bar_bool"
    bool_value: true
  }
  config {
    key: "smsToMmsTextThreshold"
    int_value: 10
  }
  config {
    key: "wfc_spn_format_idx_int"
    int_value: 1
  }
}
last_updated {
  seconds: 1709690405
}
