canonical_name: "melita_mt"
version: 62000000002
apns {
  apn {
    name: "melitaweb"
    value: "web.melita"
    type: DEFAULT
    type: SUPL
    authtype: 0
    protocol: IPV4V6
    roaming_protocol: IPV4V6
  }
}
configs {
}
last_updated {
  seconds: 1723848877
}
