canonical_name: "telekom_mk"
version: 56000000003
apns {
  apn {
    name: "T-Mobile MK Internet"
    value: ""
    type: IA
  }
  apn {
    name: "T-Mobile MK Internet"
    value: "internet"
    type: DEFAULT
    type: SUPL
    user: "internet"
    password: "t-mobile"
  }
  apn {
    name: "T-Mobile MK MMS"
    value: "mms"
    type: MMS
    user: "mms"
    password: "mms"
    mmsc: "http://mms.t-mobile.com.mk"
    mmsc_proxy: "62.162.155.227"
    mmsc_proxy_port: "8080"
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
  apn {
    name: "Telekom XCAP"
    value: "hos"
    type: XCAP
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "carrier_nr_availabilities_int_array"
    int_array {
      item: 1
    }
  }
  config {
    key: "carrier_supports_ss_over_ut_bool"
    bool_value: true
  }
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "display_hd_audio_property_bool"
    bool_value: false
  }
  config {
    key: "hide_enhanced_4g_lte_bool"
    bool_value: true
  }
  config {
    key: "maxImageHeight"
    int_value: 1944
  }
  config {
    key: "maxImageWidth"
    int_value: 2592
  }
  config {
    key: "maxMessageSize"
    int_value: 102400
  }
}
last_updated {
  seconds: 1709690405
}
