canonical_name: "claro_br"
version: 60000000001
apns {
  apn {
    name: "Java Session"
    value: "java.claro.com.br"
    type: DEFAULT
    type: SUPL
    user: "claro"
    password: "claro"
  }
  apn {
    name: "Claro Foto"
    value: "mms.claro.com.br"
    type: MMS
    user: "claro"
    password: "claro"
    authtype: 1
    mmsc: "http://mms.claro.com.br"
    mmsc_proxy: "200.169.126.10"
    mmsc_proxy_port: "8799"
  }
  apn {
    name: "Claro IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "show_4g_for_lte_data_icon_bool"
    bool_value: true
  }
}
last_updated {
  seconds: 1720164562
}
