canonical_name: "lebara_gb"
version: 56000000003
apns {
  apn {
    name: "Lebara Internet"
    value: "uk.lebara.mobi"
    type: DEFAULT
    type: MMS
    type: SUPL
    user: "wap"
    password: "wap"
    authtype: 1
    mmsc: "http://mms.lebara.co.uk/servlets/mms"
    mmsc_proxy: "212.183.137.12"
    mmsc_proxy_port: "8799"
    user_editable: false
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|18|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "carrier_nr_availabilities_int_array"
    int_array {
    }
  }
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "carrier_wfc_ims_available_bool"
    bool_value: true
  }
  config {
    key: "default_vm_number_string"
    text_value: "121"
  }
  config {
    key: "feature_access_codes_string_array"
    text_array {
      item: "153"
      item: "132"
      item: "45"
    }
  }
  config {
    key: "hide_enhanced_4g_lte_bool"
    bool_value: true
  }
  config {
    key: "read_only_apn_types_string_array"
    text_array {
      item: "*"
    }
  }
  config {
    key: "show_4g_for_lte_data_icon_bool"
    bool_value: true
  }
  config {
    key: "smsToMmsTextThreshold"
    int_value: 10
  }
  config {
    key: "wfc_spn_format_idx_int"
    int_value: 1
  }
}
last_updated {
  seconds: 1709690394
}
