canonical_name: "netcomgroup_fr"
version: 62000000001
apns {
  apn {
    name: "wordnet.com"
    value: "wordnet.com"
    type: DEFAULT
    type: SUPL
    protocol: IPV4V6
  }
  apn {
    name: "apnmms"
    value: "apnmms.com"
    type: MMS
    mmsc: "http://mms.np.fr"
    mmsc_proxy: "10.4.65.10"
    mmsc_proxy_port: "8080"
  }
}
configs {
}
last_updated {
  seconds: 1723685388
}
