canonical_name: "smart_ph"
version: 56000000002
apns {
  apn {
    name: "SMARTLTE"
    value: "smartlte"
    type: DEFAULT
    type: SUPL
  }
  apn {
    name: "SMART INTERNET"
    value: "internet"
    type: DEFAULT
    type: SUPL
  }
  apn {
    name: "Smart GPRS"
    value: "Smart1"
    type: DEFAULT
    type: SUPL
    proxy: "10.102.61.46"
    port: "8080"
  }
  apn {
    name: "Smart MMS"
    value: "mms"
    type: MMS
    mmsc: "http://10.102.61.238:8002"
    mmsc_proxy: "10.102.61.46"
    mmsc_proxy_port: "8080"
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "carrier_nr_availabilities_int_array"
    int_array {
    }
  }
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "hide_enhanced_4g_lte_bool"
    bool_value: true
  }
}
last_updated {
  seconds: 1709690394
}
