canonical_name: "talkmobile_gb"
version: 56000000010
apns {
  apn {
    name: "Talkmob WAP"
    value: "talkmobile.co.uk"
    type: DEFAULT
    type: MMS
    type: SUPL
    user: "wap"
    password: "wap"
    authtype: 1
    mmsc: "http://mms.talkmobile.co.uk/servlets/mms"
    mmsc_proxy: "212.183.137.12"
    mmsc_proxy_port: "8799"
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|18|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
  apn {
    name: "XCAP"
    value: "xcap"
    type: XCAP
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "carrier_nr_availabilities_int_array"
    int_array {
    }
  }
  config {
    key: "carrier_supports_ss_over_ut_bool"
    bool_value: true
  }
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "carrier_wfc_ims_available_bool"
    bool_value: true
  }
  config {
    key: "default_vm_number_string"
    text_value: "121"
  }
  config {
    key: "feature_access_codes_string_array"
    text_array {
      item: "153"
      item: "132"
      item: "45"
    }
  }
  config {
    key: "ims.ipv4_sip_mtu_size_cellular_int"
    int_value: 1280
  }
  config {
    key: "ims.ipv6_sip_mtu_size_cellular_int"
    int_value: 1280
  }
  config {
    key: "ims.registration_event_package_supported_bool"
    bool_value: false
  }
  config {
    key: "imsemergency.emergency_over_ims_supported_rats_int_array"
    int_array {
      item: 3
    }
  }
  config {
    key: "imsss.network_initiated_ussd_over_ims_supported_bool"
    bool_value: false
  }
  config {
    key: "imsss.ut_iptype_home_int"
    int_value: 0
  }
  config {
    key: "imsss.ut_iptype_roaming_int"
    int_value: 0
  }
  config {
    key: "imsss.xcap_over_ut_supported_rats_int_array"
    int_array {
    }
  }
  config {
    key: "imsvoice.audio_codec_capability_payload_types_bundle"
    bundle {
      config {
        key: "imsvoice.amrnb_payload_type_int_array"
        int_array {
          item: 102
        }
      }
      config {
        key: "imsvoice.amrwb_payload_type_int_array"
        int_array {
          item: 104
        }
      }
      config {
        key: "imsvoice.dtmfnb_payload_type_int_array"
        int_array {
          item: 97
        }
      }
      config {
        key: "imsvoice.dtmfwb_payload_type_int_array"
        int_array {
          item: 96
        }
      }
    }
  }
  config {
    key: "imsvoice.conference_subscribe_type_int"
    int_value: 0
  }
  config {
    key: "imsvoice.minimum_session_expires_timer_sec_int"
    int_value: 600
  }
  config {
    key: "imsvoice.ringback_timer_millis_int"
    int_value: 180000
  }
  config {
    key: "imsvoice.ringing_timer_millis_int"
    int_value: 180000
  }
  config {
    key: "imsvoice.session_refresh_method_int"
    int_value: 0
  }
  config {
    key: "imsvoice.session_refresher_type_int"
    int_value: 0
  }
  config {
    key: "show_4g_for_lte_data_icon_bool"
    bool_value: true
  }
  config {
    key: "smsToMmsTextThreshold"
    int_value: 10
  }
  config {
    key: "wfc_spn_format_idx_int"
    int_value: 1
  }
}
last_updated {
  seconds: 1715212422
}
