canonical_name: "walmart_mx"
version: 62000000001
apns {
  apn {
    name: "Walmart MX"
    value: "internet.wm.com"
    type: DEFAULT
  }
  apn {
    name: "Walmart MX IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    user_visible: false
  }
}
configs {
}
last_updated {
  seconds: 1722472090
}
