canonical_name: "ais_th"
version: 50000000003
apns {
  apn {
    name: "AIS Internet"
    value: "internet"
    type: DEFAULT
    type: SUPL
    authtype: 0
  }
  apn {
    name: "AIS MMS"
    value: "multimedia"
    type: MMS
    mmsc: "http://mms.mobilelife.co.th"
    mmsc_proxy: "203.170.229.34"
    mmsc_proxy_port: "8080"
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "roaming_operator_string_array"
    text_array {
      item: "520"
    }
  }
}
last_updated {
  seconds: 1688093790
}
