canonical_name: "altice_us"
version: 50000000001
apns {
  apn {
    name: "Optimum Internet"
    value: "altice"
    type: DEFAULT
    type: SUPL
    type: FOTA
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_editable: false
  }
  apn {
    name: "Optimum MMS"
    value: "mms"
    type: MMS
    mmsc: "http://mms.altice.com/mmsc/MMS"
    user_editable: false
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "hide_enhanced_4g_lte_bool"
    bool_value: true
  }
}
last_updated {
  seconds: 1683865158
}
