canonical_name: "asda_gb"
version: 50000000001
apns {
  apn {
    name: "ASDA internet"
    value: "my.internet"
    type: DEFAULT
    type: MMS
    type: SUPL
    proxy: "212.183.137.12"
    port: "8799"
    user: "wap"
    password: "wap"
    authtype: 1
    mmsc: "http://mms.ad.vodafone.co.uk/servlets/mms"
    mmsc_proxy: "212.183.137.12"
    mmsc_proxy_port: "8799"
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "default_vm_number_string"
    text_value: "121"
  }
  config {
    key: "feature_access_codes_string_array"
    text_array {
      item: "153"
      item: "132"
      item: "45"
    }
  }
  config {
    key: "hide_enhanced_4g_lte_bool"
    bool_value: true
  }
  config {
    key: "show_4g_for_lte_data_icon_bool"
    bool_value: true
  }
  config {
    key: "smsToMmsTextThreshold"
    int_value: 10
  }
}
last_updated {
  seconds: 1684458421
}
