canonical_name: "giga_sg"
version: 50000000004
apns {
  apn {
    name: "giga"
    value: "giga"
    type: DEFAULT
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "carrier_volte_available_bool"
    bool_value: false
  }
  config {
    key: "gsm_cdma_calls_can_be_hd_audio"
    bool_value: true
  }
}
last_updated {
  seconds: 1688093790
}
