canonical_name: "globe_ph"
version: 50000000003
apns {
  apn {
    name: "myGlobe Internet"
    value: "internet.globe.com.ph"
    type: DEFAULT
    type: SUPL
  }
  apn {
    name: "myGlobe INET"
    value: "http.globe.com.ph"
    type: DEFAULT
    type: SUPL
  }
  apn {
    name: "myGlobe Connect"
    value: "www.globe.com.ph"
    type: DEFAULT
    type: SUPL
    proxy: "203.177.42.214"
    port: "8080"
  }
  apn {
    name: "myGlobe MMS"
    value: "mms.globe.com.ph"
    type: MMS
    mmsc: "http://192.40.100.22:10021/mmsc"
    mmsc_proxy: "203.177.42.214"
    mmsc_proxy_port: "8080"
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
}
last_updated {
  seconds: 1688093790
}
