canonical_name: "iliad_it"
version: 50000000001
apns {
  apn {
    name: "iliad"
    value: "iliad"
    type: DEFAULT
    type: MMS
    mmsc: "http://mms.iliad.it"
  }
}
configs {
  config {
    key: "carrier_certificate_string_array"
    text_array {
      item: "8227db5476f1d42a17bead90b73c8624b262152edad34ebd8f7e6472a47c6e03"
    }
  }
  config {
    key: "hide_enhanced_4g_lte_bool"
    bool_value: false
  }
  config {
    key: "sim_country_iso_override_string"
    text_value: "it"
  }
}
last_updated {
  seconds: 1652473085
}
