canonical_name: "manxcontract_im"
version: 50000000003
apns {
  apn {
    name: "internet"
    value: "internet"
    type: DEFAULT
    type: SUPL
  }
  apn {
    name: "MMS"
    value: "mms.manxpronto.net"
    type: MMS
    user: "mms"
    password: "mms"
    mmsc: "http://mms.manxpronto.net:8002"
    mmsc_proxy: "195.10.99.46"
    mmsc_proxy_port: "8080"
    user_editable: false
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "default_vm_number_string"
    text_value: "121"
  }
  config {
    key: "show_4g_for_lte_data_icon_bool"
    bool_value: true
  }
}
last_updated {
  seconds: 1688093790
}
