canonical_name: "meo_pt"
version: 50000000004
apns {
  apn {
    name: "tmn internet"
    value: ""
    type: IA
  }
  apn {
    name: "internet"
    value: "internet"
    type: DEFAULT
    type: SUPL
    type: DUN
    user_editable: false
  }
  apn {
    name: "mms"
    value: "mmsc.tmn.pt"
    type: MMS
    user: "tmn"
    password: "tmnnet"
    authtype: 1
    mmsc: "http://mmsc/"
    mmsc_proxy: "10.111.2.16"
    mmsc_proxy_port: "8080"
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "show_4g_for_lte_data_icon_bool"
    bool_value: true
  }
}
last_updated {
  seconds: 1688093790
}
