canonical_name: "o2_cz"
version: 50000000001
apns {
  apn {
    name: "O2 internet"
    value: "internet"
    type: DEFAULT
    type: SUPL
  }
  apn {
    name: "O2 MMS"
    value: "mms"
    type: MMS
    mmsc: "http://mms.o2active.cz:8002"
    mmsc_proxy: "160.218.160.218"
    mmsc_proxy_port: "8080"
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "show_4g_for_lte_data_icon_bool"
    bool_value: true
  }
}
last_updated {
  seconds: 1679645347
}
