canonical_name: "o2_sk"
version: 50000000001
apns {
  apn {
    name: "O2 internet"
    value: "o2internet"
    type: DEFAULT
    type: SUPL
  }
  apn {
    name: "O2 MMS"
    value: "o2mms"
    type: MMS
    mmsc: "http://mms.o2world.sk:8002"
    mmsc_proxy: "10.97.1.11"
    mmsc_proxy_port: "8080"
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "show_4g_for_lte_data_icon_bool"
    bool_value: true
  }
}
last_updated {
  seconds: 1679645347
}
