canonical_name: "ooredoo_qa"
version: 50000000001
apns {
  apn {
    name: "Internet"
    value: "data"
    type: DEFAULT
    type: SUPL
    authtype: 1
  }
  apn {
    name: "MMS"
    value: "data"
    type: MMS
    mmsc: "http://mmsr.ooredoomms.qa"
    mmsc_proxy: "10.23.8.3"
    mmsc_proxy_port: "8080"
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
}
last_updated {
  seconds: 1679645347
}
