canonical_name: "orange_pl"
version: 50000000001
apns {
  apn {
    name: "Orange Internet"
    value: "Internet"
    type: DEFAULT
    type: SUPL
    user: "internet"
    password: "internet"
    authtype: 1
  }
  apn {
    name: "Orange MMS"
    value: "mms"
    type: MMS
    user: "mms"
    password: "mms"
    authtype: 1
    mmsc: "http://mms.orange.pl"
    mmsc_proxy: "192.168.6.104"
    mmsc_proxy_port: "8080"
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "call_barring_default_service_class_int"
    int_value: 0
  }
  config {
    key: "carrier_certificate_string_array"
    text_array {
      item: "B67AFFCDA89E3193B1595036D7C6CDBE22BE5CA24C9F6CF93FC6B48F91D7310D:com.orange.phone,pl.orange.mojeorange,com.orange.update"
      item: "B71C30C980EE10E1C53FE17F21323D4A518F1BFFCC2917DF26A9098364AA9B26:com.orange.rn.dop"
    }
  }
  config {
    key: "config_plans_package_override_string"
    text_value: "pl.orange.mojeorange"
  }
  config {
    key: "hide_enhanced_4g_lte_bool"
    bool_value: true
  }
  config {
    key: "show_4g_for_lte_data_icon_bool"
    bool_value: true
  }
}
last_updated {
  seconds: 1679645347
}
