canonical_name: "orange_lu"
version: 50000000002
apns {
  apn {
    name: "Orange"
    value: "orange.lu"
    type: DEFAULT
    type: MMS
    type: SUPL
    mmsc: "http://mms.orange.lu"
    mmsc_proxy: "212.88.139.44"
    mmsc_proxy_port: "8080"
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|18|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "wfc_spn_format_idx_int"
    int_value: 1
  }
}
last_updated {
  seconds: 1683249920
}
