canonical_name: "orange_ro"
version: 50000000001
apns {
  apn {
    name: "Orange Internet"
    value: ""
    type: IA
  }
  apn {
    name: "Orange MMS"
    value: "mms"
    type: MMS
    user: "mms"
    password: "mms"
    authtype: 1
    mmsc: "http://wap.mms.orange.ro:8002"
    mmsc_proxy: "62.217.247.252"
    mmsc_proxy_port: "8799"
  }
  apn {
    name: "Orange Internet"
    value: "net"
    type: DEFAULT
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
}
last_updated {
  seconds: 1679645347
}
