canonical_name: "pelephone_il"
version: 50000000003
apns {
  apn {
    name: "Multimedia Pelephone"
    value: "mms.pelephone.net.il"
    type: MMS
    user: "pcl@3g"
    password: "pcl"
    authtype: 3
    mmsc: "http://mmsu.pelephone.net.il"
    mmsc_proxy: "10.170.252.104"
    mmsc_proxy_port: "9093"
  }
  apn {
    name: "Sphone Pelephone"
    value: "sphone.pelephone.net.il"
    type: DEFAULT
    type: SUPL
    user: "pcl@3g"
    password: "pcl"
    authtype: 2
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
}
last_updated {
  seconds: 1688093790
}
