canonical_name: "post_lu"
version: 50000000005
apns {
  apn {
    name: "POST Internet"
    value: "web.pt.lu"
    type: DEFAULT
    type: IA
    type: SUPL
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|18|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
  apn {
    name: "POST MMS"
    value: "mms.pt.lu"
    type: MMS
    mmsc: "http://mmsc.pt.lu"
    mmsc_proxy: "194.154.192.88"
    mmsc_proxy_port: "8080"
  }
}
configs {
  config {
    key: "carrier_default_wfc_ims_mode_int"
    int_value: 1
  }
  config {
    key: "wfc_spn_format_idx_int"
    int_value: 1
  }
}
last_updated {
  seconds: 1688093790
}
