canonical_name: "salt_ch"
version: 50000000003
apns {
  apn {
    name: "Salt Internet"
    value: "internet"
    type: DEFAULT
    type: SUPL
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|18|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "enabledMMS"
    bool_value: false
  }
  config {
    key: "wfc_spn_format_idx_int"
    int_value: 1
  }
}
last_updated {
  seconds: 1684458421
}
