canonical_name: "skinny_nz"
version: 50000000006
apns {
  apn {
    name: "Data"
    value: "wapaccess.co.nz"
    type: DEFAULT
    type: SUPL
    type: MMS
    type: DUN
    mmsc: "http://lsmmsc.xtra.co.nz"
    mmsc_proxy: "210.55.11.73"
    mmsc_proxy_port: "80"
    user_editable: false
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|18|20"
    protocol: IPV6
    roaming_protocol: IPV4V6
    user_visible: false
  }
  apn {
    name: "SOS"
    value: "sos"
    type: EMERGENCY
    protocol: IPV6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "default_vm_number_string"
    text_value: "+64204864236"
  }
  config {
    key: "maxImageHeight"
    int_value: 1944
  }
  config {
    key: "maxImageWidth"
    int_value: 2592
  }
  config {
    key: "maxMessageSize"
    int_value: 614400
  }
  config {
    key: "show_4g_for_lte_data_icon_bool"
    bool_value: true
  }
  config {
    key: "supportMmsContentDisposition"
    bool_value: false
  }
  config {
    key: "wfc_spn_format_idx_int"
    int_value: 1
  }
}
last_updated {
  seconds: 1688093790
}
