canonical_name: "stc_kw"
version: 50000000001
apns {
  apn {
    name: "VIVA - KW"
    value: "viva"
    type: DEFAULT
    type: MMS
    type: SUPL
    authtype: 0
    mmsc: "http://172.16.128.80:38090/was"
    mmsc_proxy: "172.16.128.228"
    mmsc_proxy_port: "8080"
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
}
last_updated {
  seconds: 1685582922
}
