canonical_name: "tchibo_de"
version: 50000000003
apns {
  apn {
    name: "Tchibo Internet"
    value: "webmobil1"
    type: DEFAULT
    type: MMS
    type: SUPL
    mmsc: "http://10.81.0.7:8002"
    mmsc_proxy: "82.113.100.8"
    mmsc_proxy_port: "8080"
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "default_vm_number_string"
    text_value: "+491793000333"
  }
  config {
    key: "hide_ims_apn_bool"
    bool_value: true
  }
  config {
    key: "hide_lte_plus_data_icon_bool"
    bool_value: false
  }
  config {
    key: "maxImageHeight"
    int_value: 1944
  }
  config {
    key: "maxImageWidth"
    int_value: 2592
  }
  config {
    key: "maxMessageSize"
    int_value: 614400
  }
  config {
    key: "prefer_2g_bool"
    bool_value: true
  }
  config {
    key: "show_4g_for_lte_data_icon_bool"
    bool_value: true
  }
}
last_updated {
  seconds: 1688093790
}
