canonical_name: "telekom_hr"
version: 50000000003
apns {
  apn {
    name: "Internet"
    value: "internet.ht.hr"
    type: DEFAULT
    type: SUPL
    authtype: 1
    protocol: IPV4V6
  }
  apn {
    name: "HOS"
    value: "hos"
    type: MMS
    authtype: 1
    mmsc: "http://mms.t-mobile.hr/servlets/mms"
    mmsc_proxy: "10.12.0.4"
    mmsc_proxy_port: "8080"
    protocol: IPV4V6
    user_editable: false
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "display_hd_audio_property_bool"
    bool_value: false
  }
  config {
    key: "mmi_two_digit_number_pattern_string_array"
    text_array {
      item: "92"
      item: "93"
      item: "94"
      item: "95"
      item: "96"
    }
  }
}
last_updated {
  seconds: 1688093790
}
