canonical_name: "telekom_ro"
version: 50000000001
apns {
  apn {
    name: "Cosmote Connect Mobile"
    value: ""
    type: IA
  }
  apn {
    name: "Cosmote Connect Mobile"
    value: "broadband"
    type: DEFAULT
    type: SUPL
  }
  apn {
    name: "Cosmote MMS"
    value: "mms"
    type: MMS
    user: "mms"
    password: "mms"
    authtype: 1
    mmsc: "http://mmsc1.mms.cosmote.ro:8002"
    mmsc_proxy: "10.252.1.62"
    mmsc_proxy_port: "8080"
  }
  apn {
    name: "web\'n\'walk"
    value: "wnw"
    type: DEFAULT
    type: SUPL
    user: "wnw"
    password: "wnw"
    authtype: 1
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "display_hd_audio_property_bool"
    bool_value: false
  }
  config {
    key: "hide_enhanced_4g_lte_bool"
    bool_value: true
  }
  config {
    key: "show_4g_for_lte_data_icon_bool"
    bool_value: true
  }
}
last_updated {
  seconds: 1683249920
}
