canonical_name: "truemove_th"
version: 50000000004
apns {
  apn {
    name: "TRUE-H INTERNET"
    value: "internet"
    type: DEFAULT
    type: SUPL
    user: "true"
    password: "true"
    authtype: 1
  }
  apn {
    name: "TRUE-H MMS"
    value: "hmms"
    type: MMS
    user: "true"
    password: "true"
    authtype: 1
    mmsc: "http://mms.trueh.com:8002/"
    mmsc_proxy: "10.4.7.39"
    mmsc_proxy_port: "8080"
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "carrier_volte_available_bool"
    bool_value: false
  }
  config {
    key: "roaming_operator_string_array"
    text_array {
      item: "520"
    }
  }
}
last_updated {
  seconds: 1688093790
}
