canonical_name: "u264ao_at"
version: 50000000002
apns {
}
configs {
  config {
    key: "carrier_app_required_during_setup_bool"
    bool_value: true
  }
  config {
    key: "carrier_name_override_bool"
    bool_value: true
  }
  config {
    key: "carrier_name_string"
    text_value: "Google Fi"
  }
  config {
    key: "carrier_ussd_method_int"
    int_value: 1
  }
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "config_telephony_use_own_number_for_voicemail_bool"
    bool_value: true
  }
  config {
    key: "ims.ims_user_agent_string"
    text_value: "T-Mobile EPSFB-ePDG-RTT-ussd #MANUFACTURE#/#MODEL# #BUILD#"
  }
  config {
    key: "ims_reasoninfo_mapping_string_array"
    text_array {
      item: "510|Call completed elsewhere|1014"
      item: "*|Call is dropped due to Wi-Fi signal is degraded|1407"
    }
  }
}
last_updated {
  seconds: 1684458421
}
