canonical_name: "umobile_my"
version: 50000000001
apns {
  apn {
    name: "U Mobile Internet"
    value: "my3g"
    type: DEFAULT
    type: MMS
    type: SUPL
    mmsc: "http://10.30.3.11/servlets/mms"
    mmsc_proxy: "10.30.5.11"
    mmsc_proxy_port: "8080"
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|18|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
}
last_updated {
  seconds: 1678234028
}
