canonical_name: "vodafone_in"
version: 50000000359
apns {
  apn {
    name: "Vodafone"
    value: "www"
    type: DEFAULT
    type: SUPL
    protocol: IPV4V6
    roaming_protocol: IPV4V6
  }
  apn {
    name: "Vodafone_MMS"
    value: "portalnmms"
    type: MMS
    mmsc: "http://mms1.live.vodafone.in/mms/"
    mmsc_proxy: "10.10.1.100"
    mmsc_proxy_port: "9401"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|18|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "additional_settings_caller_id_visibility_bool"
    bool_value: false
  }
  config {
    key: "allow_hold_call_during_emergency_bool"
    bool_value: true
  }
  config {
    key: "carrier_nr_availabilities_int_array"
    int_array {
    }
  }
  config {
    key: "carrier_ussd_method_int"
    int_value: 1
  }
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "hide_enhanced_4g_lte_bool"
    bool_value: false
  }
  config {
    key: "ims.ims_user_agent_string"
    text_value: "#MANUFACTURE#_#MODEL#_#BUILD#"
  }
  config {
    key: "imsemergency.emergency_over_ims_supported_rats_int_array"
    int_array {
    }
  }
  config {
    key: "imssms.sms_over_ims_supported_rats_int_array"
    int_array {
    }
  }
  config {
    key: "imsss.ut_server_based_services_int_array"
    int_array {
      item: 3
      item: 20
      item: 18
      item: 5
      item: 16
      item: 17
      item: 13
      item: 1
      item: 8
      item: 15
      item: 14
      item: 19
      item: 7
      item: 12
      item: 9
      item: 11
      item: 6
      item: 2
      item: 4
      item: 0
      item: 21
    }
  }
  config {
    key: "imsss.ut_terminal_based_services_int_array"
    int_array {
      item: 10
    }
  }
  config {
    key: "imsss.xcap_over_ut_supported_rats_int_array"
    int_array {
    }
  }
  config {
    key: "imsvoice.audio_codec_capability_payload_types_bundle"
    bundle {
      config {
        key: "imsvoice.amrnb_payload_type_int_array"
        int_array {
          item: 98
          item: 103
        }
      }
      config {
        key: "imsvoice.amrwb_payload_type_int_array"
        int_array {
          item: 100
          item: 105
        }
      }
      config {
        key: "imsvoice.dtmfnb_payload_type_int_array"
        int_array {
          item: 97
        }
      }
      config {
        key: "imsvoice.dtmfwb_payload_type_int_array"
        int_array {
          item: 96
        }
      }
    }
  }
  config {
    key: "imsvoice.prack_supported_for_18x_bool"
    bool_value: true
  }
  config {
    key: "imsvoice.ringback_timer_millis_int"
    int_value: 60000
  }
  config {
    key: "imsvoice.ringing_timer_millis_int"
    int_value: 60000
  }
  config {
    key: "is_ims_conference_size_enforced_bool"
    bool_value: true
  }
  config {
    key: "prevent_clir_activation_and_deactivation_code_bool"
    bool_value: true
  }
  config {
    key: "roaming_operator_string_array"
    text_array {
      item: "404"
      item: "405"
    }
  }
  config {
    key: "smart_forwarding_config_component_name_string"
    text_value: "com.qti.xdivert/com.qti.xdivert.XDivertSetting"
  }
  config {
    key: "wfc_spn_format_idx_int"
    int_value: 1
  }
}
last_updated {
  seconds: 1688093790
}
