canonical_name: "yoigo_es"
version: 50000000007
apns {
  apn {
    name: "Yoigo Internet"
    value: ""
    type: IA
  }
  apn {
    name: "Yoigo Internet"
    value: "internet"
    type: DEFAULT
    type: SUPL
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "carrier_volte_available_bool"
    bool_value: false
  }
  config {
    key: "default_vm_number_string"
    text_value: "633"
  }
  config {
    key: "enabledMMS"
    bool_value: false
  }
  config {
    key: "hide_enhanced_4g_lte_bool"
    bool_value: false
  }
  config {
    key: "non_roaming_operator_string_array"
    text_array {
      item: "21401"
      item: "21402"
      item: "21403"
      item: "21405"
      item: "21406"
      item: "21407"
      item: "21408"
      item: "21409"
      item: "214010"
      item: "214011"
      item: "214012"
      item: "214013"
      item: "214014"
      item: "214015"
      item: "214016"
      item: "214017"
      item: "214018"
      item: "214019"
      item: "214020"
      item: "214021"
    }
  }
  config {
    key: "show_4g_for_lte_data_icon_bool"
    bool_value: true
  }
  config {
    key: "unloggable_numbers_string_array"
    text_array {
      item: "900018018"
    }
  }
}
last_updated {
  seconds: 1688093790
}
