canonical_name: "free_re"
version: 57000000002
apns {
  apn {
    name: "Free Re"
    value: "free.re"
    type: DEFAULT
    type: DUN
    type: SUPL
    type: MMS
    mmsc: "http://mms.free.re"
    protocol: IPV4V6
  }
}
configs {
  config {
    key: "imsemergency.emergency_domain_preference_int_array"
    int_array {
      item: 2
      item: 1
    }
  }
  config {
    key: "imsemergency.emergency_domain_preference_roaming_int_array"
    int_array {
      item: 2
      item: 1
    }
  }
  config {
    key: "read_only_apn_types_string_array"
    text_array {
    }
  }
}
last_updated {
  seconds: 1710391116
}
