canonical_name: "maxis_my"
version: 56000000011
apns {
  apn {
    name: "Maxis Internet"
    value: "unet"
    type: DEFAULT
    type: MMS
    type: SUPL
    user: "maxis"
    password: "wap"
    authtype: 1
    mmsc: "http://172.16.74.100:10021/mmsc"
    mmsc_proxy: "202.75.133.49"
    mmsc_proxy_port: "80"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
  apn {
    name: "hos"
    value: "hos"
    type: XCAP
    protocol: IPV4V6
    roaming_protocol: IPV4V6
  }
}
configs {
  config {
    key: "bsf.bsf_server_fqdn_string"
    text_value: "bsf.ims.mnc012.mcc502.pub.3gppnetwork.org"
  }
  config {
    key: "bsf.bsf_server_port_int"
    int_value: 8091
  }
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "imsemergency.emergency_over_ims_supported_rats_int_array"
    int_array {
      item: 3
    }
  }
  config {
    key: "imsss.ut_as_server_fqdn_string"
    text_value: "xcap.ims.mnc012.mcc502.pub.3gppnetwork.org"
  }
  config {
    key: "imsss.ut_as_server_port_int"
    int_value: 8090
  }
  config {
    key: "imsss.xcap_over_ut_supported_rats_int_array"
    int_array {
      item: 6
      item: 3
      item: 5
      item: 1
      item: 2
    }
  }
  config {
    key: "imsvoice.audio_codec_capability_payload_types_bundle"
    bundle {
      config {
        key: "imsvoice.amrnb_payload_type_int_array"
        int_array {
          item: 98
          item: 103
        }
      }
      config {
        key: "imsvoice.amrwb_payload_type_int_array"
        int_array {
          item: 100
          item: 105
        }
      }
      config {
        key: "imsvoice.dtmfnb_payload_type_int_array"
        int_array {
          item: 97
        }
      }
      config {
        key: "imsvoice.dtmfwb_payload_type_int_array"
        int_array {
          item: 96
        }
      }
    }
  }
  config {
    key: "show_4g_for_lte_data_icon_bool"
    bool_value: true
  }
}
last_updated {
  seconds: 1708635157
}
