canonical_name: "orange_pl"
version: 56000000007
apns {
  apn {
    name: "Orange Internet"
    value: "Internet"
    type: DEFAULT
    type: SUPL
    user: "internet"
    password: "internet"
    authtype: 1
  }
  apn {
    name: "Orange MMS"
    value: "mms"
    type: MMS
    user: "mms"
    password: "mms"
    authtype: 1
    mmsc: "http://mms.orange.pl"
    mmsc_proxy: "192.168.6.104"
    mmsc_proxy_port: "8080"
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|18|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
  apn {
    name: "hos"
    value: "hos"
    type: XCAP
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "call_barring_default_service_class_int"
    int_value: 0
  }
  config {
    key: "carrier_certificate_string_array"
    text_array {
      item: "B67AFFCDA89E3193B1595036D7C6CDBE22BE5CA24C9F6CF93FC6B48F91D7310D:com.orange.phone,pl.orange.mojeorange,com.orange.update"
      item: "B71C30C980EE10E1C53FE17F21323D4A518F1BFFCC2917DF26A9098364AA9B26:com.orange.rn.dop"
    }
  }
  config {
    key: "carrier_supports_ss_over_ut_bool"
    bool_value: true
  }
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "carrier_wfc_ims_available_bool"
    bool_value: true
  }
  config {
    key: "config_plans_package_override_string"
    text_value: "pl.orange.mojeorange"
  }
  config {
    key: "hide_enhanced_4g_lte_bool"
    bool_value: true
  }
  config {
    key: "ims.request_uri_type_int"
    int_value: 1
  }
  config {
    key: "imsemergency.emergency_over_ims_supported_rats_int_array"
    int_array {
      item: 3
    }
  }
  config {
    key: "imsss.xcap_over_ut_supported_rats_int_array"
    int_array {
      item: 5
      item: 6
      item: 3
      item: 1
      item: 2
    }
  }
  config {
    key: "imsvoice.amrnb_payload_description_bundle"
    bundle {
      config {
        key: "101"
        bundle {
          config {
            key: "imsvoice.amr_codec_attribute_payload_format_int"
            int_value: 1
          }
        }
      }
    }
  }
  config {
    key: "imsvoice.amrwb_payload_description_bundle"
    bundle {
      config {
        key: "99"
        bundle {
          config {
            key: "imsvoice.amr_codec_attribute_payload_format_int"
            int_value: 1
          }
        }
      }
    }
  }
  config {
    key: "imsvoice.audio_codec_capability_payload_types_bundle"
    bundle {
      config {
        key: "imsvoice.amrnb_payload_type_int_array"
        int_array {
          item: 100
          item: 101
        }
      }
      config {
        key: "imsvoice.amrwb_payload_type_int_array"
        int_array {
          item: 98
          item: 99
        }
      }
      config {
        key: "imsvoice.dtmfnb_payload_type_int_array"
        int_array {
          item: 106
        }
      }
      config {
        key: "imsvoice.dtmfwb_payload_type_int_array"
        int_array {
          item: 105
        }
      }
      config {
        key: "imsvoice.evs_payload_type_int_array"
        int_array {
          item: 96
          item: 97
        }
      }
    }
  }
  config {
    key: "imsvoice.evs_payload_description_bundle"
    bundle {
      config {
        key: "96"
        bundle {
          config {
            key: "imsvoice.evs_codec_attribute_bandwidth_int"
            int_value: 2
          }
          config {
            key: "imsvoice.evs_codec_attribute_bitrate_int_array"
            int_array {
              item: 3
              item: 6
            }
          }
        }
      }
      config {
        key: "97"
        bundle {
          config {
            key: "imsvoice.evs_codec_attribute_bitrate_int_array"
            int_array {
              item: 0
              item: 6
            }
          }
        }
      }
    }
  }
  config {
    key: "show_4g_for_lte_data_icon_bool"
    bool_value: true
  }
  config {
    key: "wfc_spn_format_idx_int"
    int_value: 1
  }
}
last_updated {
  seconds: 1708635157
}
