canonical_name: "smartfren_id"
version: 60000000001
apns {
  apn {
    name: "Smartfren4G"
    value: "smartfren4G"
    type: DEFAULT
    type: SUPL
    authtype: 1
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
}
last_updated {
  seconds: 1720164562
}
